<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { obtenerReporteAlmacen, urlPdfReporteAlmacen } from '../services/reporteAlmacen'
import type { ItemReporteAlmacen } from '../interfaces/reporteAlmacen.interface'
const currentYear=new Date().getFullYear(),year=ref(currentYear),query=ref(''),items=ref<ItemReporteAlmacen[]>([]),loading=ref(false),error=ref(''),totalItems=ref(0),totalQuantity=ref(0),totalValue=ref(0)
const years=Array.from({length:12},(_,i)=>currentYear-i),filtered=computed(()=>{const q=query.value.trim().toLocaleLowerCase('es');return q?items.value.filter(x=>[x.almacen,x.codigo_avalon,x.descripcion,x.unidad_medida].some(v=>v.toLocaleLowerCase('es').includes(q))):items.value}),filteredValue=computed(()=>filtered.value.reduce((sum,x)=>sum+x.valor_total,0)),filteredQuantity=computed(()=>filtered.value.reduce((sum,x)=>sum+x.saldo,0))
async function load(){loading.value=true;error.value='';try{const r=await obtenerReporteAlmacen(year.value);items.value=r.items;totalItems.value=r.total_items;totalQuantity.value=r.total_cantidad;totalValue.value=r.total_valorizado}catch(e){error.value=e instanceof Error?e.message:'No se pudo cargar el reporte.'}finally{loading.value=false}}
function download(){window.open(urlPdfReporteAlmacen(year.value),'_blank','noopener')}
const number=(v=0)=>new Intl.NumberFormat('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(v),money=(v=0)=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(v)
onMounted(load)
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / Administración / Utilitarios / Reporte de almacén</nav><header class="hero"><div class="mark">RA</div><div><small>MIA · UTILITARIOS</small><h1>Reporte anual de almacén</h1><p>Ítems ingresados sin movimiento a la fecha, agrupados por ejercicio.</p></div><label>Año fiscal<select v-model="year" @change="load"><option v-for="item in years" :key="item" :value="item">{{item}}</option></select></label><button @click="download">Descargar PDF</button></header><p v-if="error" class="flash">{{error}}</p><section class="summary"><article><div class="icon">#</div><div><small>ÍTEMS REGISTRADOS</small><b>{{totalItems}}</b></div></article><article><div class="icon quantity">∑</div><div><small>CANTIDAD ACUMULADA</small><b>{{number(totalQuantity)}}</b></div></article><article><div class="icon value">S/</div><div><small>VALOR TOTAL</small><b>{{money(totalValue)}}</b></div></article></section><section class="report"><header><div><small>INVENTARIO SIN MOVIMIENTO</small><h2>Detalle del ejercicio {{year}}</h2></div><label>Buscar<input v-model.trim="query" placeholder="Código, descripción o almacén"></label></header><div v-if="loading" class="empty">Generando reporte…</div><div v-else-if="!filtered.length" class="empty">No se encontraron ítems para el año seleccionado.</div><div v-else class="table-wrap"><table><thead><tr><th>#</th><th>Almacén</th><th>Código Avalon</th><th>Descripción del ítem</th><th>Unidad</th><th class="right">Cantidad</th><th class="right">Valor total</th></tr></thead><tbody><tr v-for="(item,index) in filtered" :key="`${item.almacen}-${item.codigo_avalon}`"><td>{{index+1}}</td><td><span class="warehouse">{{item.almacen}}</span></td><td><b>{{item.codigo_avalon}}</b></td><td>{{item.descripcion}}</td><td>{{item.unidad_medida}}</td><td class="right">{{number(item.saldo)}}</td><td class="right money">{{money(item.valor_total)}}</td></tr></tbody><tfoot><tr><td colspan="5">TOTAL {{query?`FILTRADO (${filtered.length} ítems)`:`DEL EJERCICIO ${year}`}}</td><td class="right">{{number(filteredQuantity)}}</td><td class="right">{{money(filteredValue)}}</td></tr></tfoot></table></div></section><p class="note">Los importes provienen de los movimientos Avalon agrupados por almacén, código, descripción y unidad de medida.</p></div></template>
<style scoped>
.page{--accent:#d64f83;color:#35464e}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--accent);text-decoration:none}.hero{padding:20px 23px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--accent);border-radius:12px;background:#fff}.mark{width:52px;height:52px;display:grid;place-items:center;border-radius:11px;color:#fff;background:var(--accent);font-size:.65rem;font-weight:800}.hero small,.summary small,.report small{color:var(--accent);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.3rem}.hero p{margin:0;color:#7e8a90;font-size:.67rem}.hero label{margin-left:auto;display:grid;gap:3px;font-size:.47rem}.hero select,.report input{padding:8px;border:1px solid #d7dfe2;border-radius:6px;background:#fff;font:inherit;font-size:.55rem}.hero button{padding:9px 12px;border:0;border-radius:6px;color:#fff;background:var(--accent);font-size:.52rem}.flash{padding:9px;border-radius:7px;color:#a64046;background:#fff0f0;font-size:.6rem}.summary{margin-top:11px;display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.summary article{padding:13px;display:flex;align-items:center;gap:10px;border-radius:9px;background:#fff}.summary article>div:last-child{display:grid}.summary b{font-size:.85rem}.icon{width:34px;height:34px;display:grid;place-items:center;border-radius:8px;color:#fff;background:var(--accent);font-size:.6rem;font-weight:800}.icon.quantity{background:#3a9a79}.icon.value{background:#536c91}.report{margin-top:10px;padding:15px;border-radius:10px;background:#fff}.report>header{display:flex;align-items:center}.report h2{margin:2px 0;font-size:.78rem}.report label{margin-left:auto;display:grid;gap:3px;font-size:.47rem}.report input{width:260px}.empty{padding:45px;text-align:center;font-size:.58rem}.table-wrap{margin-top:12px;overflow:auto}table{width:100%;border-collapse:collapse;font-size:.5rem}th,td{padding:9px 8px;border-bottom:1px solid #e7ebed;text-align:left;white-space:nowrap}th{color:#68767d;background:#f4f7f8;font-size:.44rem;text-transform:uppercase}td:nth-child(4){min-width:260px;white-space:normal}.right{text-align:right}.money{color:#2d765d;font-weight:700}.warehouse{padding:4px 6px;border-radius:8px;color:#536c91;background:#eaf0f8;font-size:.43rem}tfoot td{border:0;color:#fff;background:#455b6d;font-weight:800}.note{margin:8px 2px;color:#879399;font-size:.47rem}@media(max-width:850px){.hero{flex-wrap:wrap}.hero label{margin-left:0}.summary{grid-template-columns:1fr}.report>header{align-items:flex-start;flex-direction:column;gap:8px}.report label,.report input{width:100%;margin-left:0}}
</style>
