<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import type { Inversion, InversionPayload } from '../interfaces/inversion.interface'
import { cambiarEstadoInversion, guardarInversion, listarInversiones } from '../services/inversiones'
const rows=ref<Inversion[]>([]),criterio=ref(''),page=ref(1),lastPage=ref(1),total=ref(0),loading=ref(false),saving=ref(false),modal=ref(false),editing=ref<number|null>(null),error=ref(''),success=ref('')
const form=reactive<InversionPayload>({nombre:'',descripcion:''}),message=(e:unknown)=>e instanceof Error?e.message:'No se pudo completar la operación.'
async function load(next=1){loading.value=true;error.value='';try{const r=await listarInversiones(criterio.value,next);rows.value=r.data;page.value=r.current_page;lastPage.value=r.last_page;total.value=r.total}catch(e){error.value=message(e)}finally{loading.value=false}}
function open(item?:Inversion){editing.value=item?.id??null;form.nombre=item?.nombre??'';form.descripcion=item?.descripcion??'';error.value='';modal.value=true}
async function save(){if(!form.nombre.trim()||!form.descripcion.trim()){error.value='El nombre y la descripción son obligatorios.';return}saving.value=true;error.value='';try{await guardarInversion(editing.value,{nombre:form.nombre.trim().toUpperCase(),descripcion:form.descripcion.trim().toUpperCase()});modal.value=false;success.value=`Inversión ${editing.value?'actualizada':'registrada'} correctamente.`;await load(editing.value?page.value:1)}catch(e){error.value=message(e)}finally{saving.value=false}}
async function toggle(item:Inversion){if(!confirm(`¿Desea ${item.estado?'desactivar':'activar'} la inversión ${item.nombre}?`))return;error.value='';try{const r=await cambiarEstadoInversion(item.id);item.estado=r.estado;success.value=r.message||'Estado actualizado correctamente.'}catch(e){error.value=message(e)}}
function clear(){criterio.value='';load(1)}
onMounted(()=>load())
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/presupuesto">Presupuesto</RouterLink> / Inversiones</nav><header class="hero"><div class="mark">IN</div><div><small>MIA · PRESUPUESTO · MAESTROS</small><h1>Inversiones</h1><p>Administra las inversiones utilizadas en la formulación y ejecución presupuestal.</p></div><strong>{{total}} registros</strong><button @click="open()">+ Nueva inversión</button></header><p v-if="success" class="flash success">✓ {{success}}</p><p v-if="error&&!modal" class="flash error">{{error}}</p><form class="filters" @submit.prevent="load(1)"><input v-model.trim="criterio" placeholder="Buscar por nombre o descripción"><button>Buscar</button><button type="button" class="soft" @click="clear">Limpiar</button></form><section class="card"><div v-if="loading" class="empty">Consultando inversiones…</div><div v-else-if="!rows.length" class="empty">No se encontraron inversiones.</div><div v-else class="scroll"><table><thead><tr><th>ID</th><th>Nombre</th><th>Descripción</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><tr v-for="item in rows" :key="item.id"><td>#{{item.id}}</td><td><b>{{item.nombre}}</b></td><td>{{item.descripcion}}</td><td><span :class="item.estado?'active':'inactive'">{{item.estado?'ACTIVO':'INACTIVO'}}</span></td><td class="actions"><button class="edit" @click="open(item)">Editar</button><button :class="item.estado?'disable':'enable'" @click="toggle(item)">{{item.estado?'Desactivar':'Activar'}}</button></td></tr></tbody></table></div><footer v-if="lastPage>1"><button :disabled="page<=1" @click="load(page-1)">Anterior</button><span>{{page}} / {{lastPage}}</span><button :disabled="page>=lastPage" @click="load(page+1)">Siguiente</button></footer></section><div v-if="modal" class="backdrop" @mousedown.self="modal=false"><form class="dialog" @submit.prevent="save"><header><div><small>MAESTRO DE INVERSIONES</small><h2>{{editing?'Editar':'Nueva'}} inversión</h2></div><button type="button" @click="modal=false">×</button></header><p v-if="error" class="flash error">{{error}}</p><label>Nombre *<input v-model="form.nombre" maxlength="45" @input="form.nombre=form.nombre.toUpperCase()"></label><label>Descripción *<input v-model="form.descripcion" maxlength="45" @input="form.descripcion=form.descripcion.toUpperCase()"></label><footer><button type="button" class="soft" @click="modal=false">Cancelar</button><button :disabled="saving">{{saving?'Guardando…':'Guardar'}}</button></footer></form></div></div></template>
<style scoped>
.page{--a:#d64f83;color:#35464e}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--a);text-decoration:none}.hero{padding:20px 23px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:50px;height:50px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero>div:nth-child(2){flex:1}.hero small,.dialog small{color:var(--a);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.3rem}.hero p{margin:0;color:#7e8a90;font-size:.67rem}.hero strong{padding:6px 9px;border-radius:12px;color:var(--a);background:#fbeaf1;font-size:.52rem}button{padding:9px 12px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.52rem;cursor:pointer}.flash{padding:9px;border-radius:7px;font-size:.6rem}.success{color:#287052;background:#edf9f3}.error{color:#a64046;background:#fff0f0}.filters{margin-top:11px;padding:13px;display:flex;gap:7px;background:#fff}.filters input{flex:1;padding:8px;border:1px solid #d7dfe2;border-radius:6px}.soft{color:#64727a!important;background:#edf1f3!important}.card{margin-top:11px;border-radius:10px;background:#fff;overflow:hidden}.scroll{overflow:auto}table{width:100%;min-width:750px;border-collapse:collapse;font-size:.52rem}th,td{padding:10px;border-bottom:1px solid #e7ecee;text-align:left}th{color:#fff;background:#5b6e8e}.active,.inactive{display:inline-block;padding:4px 7px;border-radius:10px;font-size:.43rem;font-weight:700}.active{color:#287154;background:#e6f7ee}.inactive{color:#9d4046;background:#fdebed}.actions{display:flex;gap:5px}.actions button{padding:6px 8px}.edit{color:#79500b;background:#ffe7bd}.disable{color:#9d4046;background:#fdebed}.enable{color:#287154;background:#e6f7ee}.empty{padding:45px;text-align:center}.card>footer{padding:11px;display:flex;justify-content:center;align-items:center;gap:8px;font-size:.5rem}.backdrop{position:fixed;z-index:100;inset:0;padding:20px;display:grid;place-items:center;background:#172b3d88}.dialog{width:min(550px,100%);padding:20px;box-sizing:border-box;border-radius:12px;background:#fff}.dialog>header{display:flex}.dialog h2{margin:2px 0 12px}.dialog>header button{margin-left:auto;color:#59666c;background:none;font-size:1.2rem}.dialog label{display:grid;gap:5px;margin-top:10px;font-size:.53rem}.dialog input{padding:9px;border:1px solid #d7dfe2;border-radius:6px}.dialog footer{margin-top:18px;display:flex;justify-content:flex-end;gap:6px}@media(max-width:700px){.hero{flex-wrap:wrap}.filters{flex-wrap:wrap}.filters input{flex-basis:100%}}
</style>
