<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { consultarBalanceComprobacion, obtenerOpcionesBalanceComprobacion } from '../services/balanceComprobacion'
import type { BalanceComprobacionData, ColumnaBalance, FiltrosBalanceComprobacion, MesBalanceComprobacion } from '../interfaces/balanceComprobacion.interface'
const columnas:ColumnaBalance[]=['apertura_debe','apertura_haber','mov_acum_debe','mov_acum_haber','mov_mes_debe','mov_mes_haber','saldo_mayor_debe','saldo_mayor_haber','cargas_debe','cargas_haber','inv_activo','inv_pasivo','res_nat_perdida','res_nat_ganancia','res_func_perdida','res_func_ganancia']
const grupos=[['APERTURA','Debe','Haber'],['MOVIMIENTO ACUMULADO','Debe','Haber'],['MOVIMIENTO DEL MES','Debe','Haber'],['SALDOS DEL MAYOR','Debe','Haber'],['CARGAS TRANSFERIDAS','Debe','Haber'],['INVENTARIOS','Activo','Pasivo'],['RESULTADOS POR NATURALEZA','Pérdida','Ganancia'],['RESULTADOS POR FUNCIÓN','Pérdida','Ganancia']]
const filtros=reactive<FiltrosBalanceComprobacion>({mes:null,digitos:null}),anio=ref<number|null>(null),meses=ref<MesBalanceComprobacion[]>([]),digitos=ref<number[]>([]),data=ref<BalanceComprobacionData|null>(null),loading=ref(false),consultado=ref(false),error=ref('')
const message=(v:unknown)=>v instanceof Error?v.message:'No se pudo completar la consulta.'
const money=(v:number)=>new Intl.NumberFormat('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))
async function load(){loading.value=true;try{const r=await obtenerOpcionesBalanceComprobacion();anio.value=r.anio_vigente;meses.value=r.meses;digitos.value=r.digitos_disponibles.filter(d=>d<=r.digitos_plan);data.value=r.data}catch(v){error.value=message(v)}finally{loading.value=false}}
async function search(){error.value='';if(!filtros.mes||!filtros.digitos)return void(error.value='Seleccione el mes y el número de dígitos.');loading.value=true;consultado.value=true;try{data.value=(await consultarBalanceComprobacion(filtros)).data}catch(v){error.value=message(v);data.value=null}finally{loading.value=false}}
function clear(){filtros.mes=null;filtros.digitos=null;data.value=null;consultado.value=false;error.value=''}
onMounted(load)
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/contabilidad/proceso-contable">Proceso contable</RouterLink> / Balance de comprobación</nav><header class="hero"><div class="mark">BC</div><div><small>MIA · CONTABILIDAD · PROCESO</small><h1>Balance de comprobación</h1><p>Analiza apertura, movimientos, saldos del mayor, inventarios y resultados.</p></div></header><p v-if="error" class="flash">{{error}}</p><form class="filters" @submit.prevent="search"><label>Periodo<input :value="anio??'—'" readonly></label><label>Mes *<select v-model="filtros.mes"><option :value="null">Seleccione</option><option v-for="m in meses" :key="m.id" :value="m.mes">{{m.mes_label}}</option></select></label><label>Número de dígitos *<select v-model="filtros.digitos"><option :value="null">Seleccione</option><option v-for="d in digitos" :key="d" :value="d">{{d}} dígitos</option></select></label><footer><button type="button" class="soft" @click="clear">Limpiar</button><button :disabled="loading">{{loading?'Consultando…':'Consultar'}}</button></footer></form><div v-if="loading" class="empty">Calculando el balance de comprobación…</div><div v-else-if="consultado&&!data?.rows.length" class="empty">No se encontraron datos para los filtros seleccionados.</div><div v-else-if="!data" class="empty">Seleccione el mes y el número de dígitos para consultar.</div><main v-else><header class="summary"><div><b>Periodo</b><span>{{data.anio}} / {{data.mes}}</span></div><div><b>Nivel contable</b><span>{{data.digitos}} dígitos</span></div><div><b>Cuentas</b><span>{{data.rows.length}}</span></div></header><div class="scroll"><table><thead><tr><th rowspan="2">Cta.</th><th rowspan="2">Denominación</th><th v-for="g in grupos" :key="g[0]" colspan="2">{{g[0]}}</th></tr><tr><template v-for="g in grupos" :key="`${g[0]}-sub`"><th>{{g[1]}}</th><th>{{g[2]}}</th></template></tr></thead><tbody><tr v-for="row in data.rows" :key="row.cta_contable"><td><b>{{row.cta_contable}}</b></td><td>{{row.descripcion}}</td><td v-for="c in columnas" :key="c" class="num">{{money(row[c])}}</td></tr></tbody><tfoot><tr class="total"><td colspan="2">TOTALES</td><td v-for="c in columnas" :key="c" class="num">{{money(data.totales[c])}}</td></tr><tr v-for="fila in data.footer" :key="fila.descripcion" class="footer"><td colspan="2">{{fila.descripcion}}</td><td v-for="c in columnas" :key="c" class="num">{{money(fila[c])}}</td></tr></tfoot></table></div></main></div></template>
<style scoped>
.page{--a:#268c86;color:#35464e}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--a);text-decoration:none}.hero{padding:20px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:48px;height:48px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero small{color:var(--a);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.3rem}.hero p{margin:0;color:#7e8a90;font-size:.67rem}.flash{padding:9px;color:#a64046;background:#fff0f0}.filters{margin-top:12px;padding:15px;display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:8px;background:#fff}.filters label{display:grid;gap:5px;font-size:.49rem}.filters select,.filters input{min-width:0;padding:9px;border:1px solid #d7dfe2;border-radius:6px;background:#fff;font:inherit;font-size:.52rem}.filters input{background:#f3f6f7}.filters footer{display:flex;align-items:end;justify-content:flex-end;gap:6px}.filters button{padding:9px 12px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.52rem}.soft{color:#64727a!important;background:#edf1f3!important}.empty{margin-top:12px;padding:45px;text-align:center;background:#fff}.summary{margin-top:14px;padding:12px;display:grid;grid-template-columns:repeat(3,1fr);gap:8px;background:#fff}.summary div{display:grid;gap:3px;font-size:.52rem}.summary b{color:#728087}.scroll{margin-top:12px;overflow:auto;background:#fff}table{width:100%;min-width:2300px;border-collapse:collapse;font-size:.47rem}th,td{padding:6px 5px;border:1px solid #dce3e5;text-align:left;white-space:nowrap}thead{color:#fff;background:#34495e}thead th{text-align:center}thead th:nth-child(2){min-width:220px}.num{text-align:right;font-family:monospace}tbody tr:nth-child(even){background:#f7f9f9}.total{color:#fff;background:#2c3e50;font-weight:700}.total td:first-child,.footer td:first-child{text-align:right}.footer{background:#d5dbdb;font-weight:700}@media(max-width:700px){.filters,.summary{grid-template-columns:1fr}.filters footer{justify-content:flex-start}}
</style>
