<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { consultarConsistencias, obtenerMesesConsistencias, obtenerOpcionesConsistencias } from '../services/consistencias'
import type { ConsistenciasData, ConsistenciasFiltros, MesConsistencia } from '../interfaces/consistencias.interface'
const filtros=reactive<ConsistenciasFiltros>({anio:null,mes_inicio:null,mes_fin:null}),anios=ref<number[]>([]),meses=ref<MesConsistencia[]>([]),data=ref<ConsistenciasData|null>(null),loading=ref(false),consultado=ref(false),error=ref('')
const message=(v:unknown)=>v instanceof Error?v.message:'No se pudo completar la consulta.'
const money=(v:number)=>new Intl.NumberFormat('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))
const cuadrado=computed(()=>data.value?Math.abs(data.value.totalGeneralDebe-data.value.totalGeneralHaber)<.01:false)
async function load(){loading.value=true;try{const r=await obtenerOpcionesConsistencias();anios.value=r.anios;meses.value=r.meses??[];data.value=r.data}catch(v){error.value=message(v)}finally{loading.value=false}}
async function changeYear(){filtros.mes_inicio=null;filtros.mes_fin=null;meses.value=filtros.anio?await obtenerMesesConsistencias(filtros.anio):[]}
async function search(){if(!filtros.anio||!filtros.mes_inicio||!filtros.mes_fin)return void(error.value='Seleccione el año y el rango de meses.');if(filtros.mes_inicio>filtros.mes_fin)return void(error.value='El mes inicial no puede ser mayor que el mes final.');loading.value=true;consultado.value=true;error.value='';try{const r=await consultarConsistencias(filtros);data.value=r.data}catch(v){error.value=message(v)}finally{loading.value=false}}
function clear(){Object.assign(filtros,{anio:null,mes_inicio:null,mes_fin:null});meses.value=[];data.value=null;consultado.value=false;error.value=''}
onMounted(load)
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/contabilidad/proceso-contable">Proceso contable</RouterLink> / Consistencias</nav><header class="hero"><div class="mark">CO</div><div><small>MIA · CONTABILIDAD · PROCESO</small><h1>Consistencias contables</h1><p>Valida la cuadratura Debe/Haber de los comprobantes registrados en el periodo.</p></div></header><p v-if="error" class="flash">{{error}}</p><form class="filters" @submit.prevent="search"><label>Año *<select v-model="filtros.anio" @change="changeYear"><option :value="null">Seleccione</option><option v-for="a in anios" :key="a" :value="a">{{a}}</option></select></label><label>Mes inicial *<select v-model="filtros.mes_inicio"><option :value="null">Seleccione</option><option v-for="m in meses" :key="m.mes" :value="m.mes">{{m.mes_label}}</option></select></label><label>Mes final *<select v-model="filtros.mes_fin"><option :value="null">Seleccione</option><option v-for="m in meses" :key="m.mes" :value="m.mes">{{m.mes_label}}</option></select></label><footer><button type="button" class="soft" @click="clear">Limpiar</button><button :disabled="loading">{{loading?'Validando…':'Consultar'}}</button></footer></form><div v-if="loading" class="empty">Validando consistencias…</div><div v-else-if="consultado&&!data" class="empty">No se encontraron comprobantes para el periodo.</div><div v-else-if="!consultado" class="empty">Seleccione el periodo que desea validar.</div><main v-else-if="data"><aside :class="cuadrado?'status good':'status warning'"><b>{{cuadrado?'Contabilidad cuadrada':'Se encontraron diferencias'}}</b><span>Diferencia: S/ {{money(data.totalGeneralDebe-data.totalGeneralHaber)}}</span></aside><section v-for="tipo in data.dataPorTipo" :key="tipo.tipo_codigo" class="type"><header>{{tipo.tipo_codigo}} - {{tipo.tipo_nombre}}</header><article v-for="comp in tipo.comprobantes" :key="comp.id??`${comp.numero}-${comp.fecha}`"><h2>N.° {{comp.numero}} · {{comp.fecha}} · {{comp.glosa}}</h2><p>{{comp.origen}} · Documento: {{comp.fecha_doc||'—'}}</p><div class="scroll"><table><thead><tr><th>Cuenta</th><th>Nombre de la cuenta</th><th>Debe S/</th><th>Haber S/</th></tr></thead><tbody><tr v-for="det in comp.detalles" :key="`${comp.numero}-${det.cta_contable}`"><td><b>{{det.cta_contable}}</b></td><td>{{det.descripcion_cuenta}}</td><td class="num">{{money(det.debe)}}</td><td class="num">{{money(det.haber)}}</td></tr><tr v-if="!comp.detalles.length"><td colspan="4">Sin detalle</td></tr></tbody><tfoot><tr><th colspan="2">Total comprobante #{{comp.numero}}</th><td class="num">{{money(comp.total_debe)}}</td><td class="num">{{money(comp.total_haber)}}</td></tr></tfoot></table></div></article></section><footer class="grand"><b>Total general</b><span>S/ {{money(data.totalGeneralDebe)}}</span><span>S/ {{money(data.totalGeneralHaber)}}</span></footer></main></div></template>
<style scoped>
.page{--a:#d08b32;color:#35464e}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--a);text-decoration:none}.hero{padding:20px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:48px;height:48px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero small{color:var(--a);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.3rem}.hero p{margin:0;color:#7e8a90;font-size:.67rem}.flash{padding:9px;color:#a64046;background:#fff0f0}.filters{margin-top:12px;padding:15px;display:grid;grid-template-columns:repeat(3,1fr);gap:9px;background:#fff}.filters label{display:grid;gap:5px;font-size:.49rem}.filters select{padding:9px;border:1px solid #d7dfe2;border-radius:6px;background:#fff;font:inherit;font-size:.52rem}.filters footer{grid-column:1/-1;display:flex;justify-content:flex-end;gap:6px}.filters button{padding:9px 12px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.52rem}.soft{color:#64727a!important;background:#edf1f3!important}.empty{margin-top:12px;padding:45px;text-align:center;background:#fff}.status{margin-top:12px;padding:12px;display:flex;justify-content:space-between;border-radius:8px;font-size:.58rem}.good{color:#287052;background:#e9f8f0}.warning{color:#995057;background:#fff0f0}.type{margin-top:15px;background:#fff}.type>header{padding:10px;color:#fff;background:#334b58;font-size:.62rem;font-weight:700}.type article h2{margin:10px 10px 2px;padding-left:7px;border-left:4px solid #4694bf;font-size:.57rem}.type article p{margin:0 10px 7px;color:#7d898e;font-size:.48rem}.scroll{overflow:auto}table{width:100%;min-width:620px;border-collapse:collapse;font-size:.5rem}th,td{padding:8px;border:1px solid #e1e7ea;text-align:left}thead{color:#fff;background:#4e6570}tfoot{background:#e4e8ea}.num{text-align:right;font-family:monospace}.grand{padding:12px;display:grid;grid-template-columns:1fr 150px 150px;color:#fff;background:#334b58;text-align:right;font:700 .58rem monospace}.grand b{text-align:left}@media(max-width:620px){.filters{grid-template-columns:1fr}.status{display:grid;gap:5px}.grand{grid-template-columns:1fr}}
</style>
