<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { consultarSaldos, obtenerMesesConsultaSaldos, obtenerOpcionesConsultaSaldos } from '../services/consultaSaldos'
import type { ConsultaSaldosData, FiltrosConsultaSaldos, MesConsultaSaldo } from '../interfaces/consultaSaldos.interface'
const filtros=reactive<FiltrosConsultaSaldos>({anio:null,mes:null}),anios=ref<number[]>([]),meses=ref<MesConsultaSaldo[]>([]),data=ref<ConsultaSaldosData|null>(null),loading=ref(false),consultado=ref(false),error=ref('')
const message=(v:unknown)=>v instanceof Error?v.message:'No se pudo completar la consulta.'
const money=(v:number)=>new Intl.NumberFormat('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))
const indent=(nivel:number)=>`${Math.min(Math.max(nivel-1,0),8)*14}px`
async function load(){loading.value=true;try{const r=await obtenerOpcionesConsultaSaldos();anios.value=r.anios;meses.value=r.meses??[];data.value=r.data}catch(v){error.value=message(v)}finally{loading.value=false}}
async function changeYear(){filtros.mes=null;meses.value=[];data.value=null;if(!filtros.anio)return;try{meses.value=await obtenerMesesConsultaSaldos(filtros.anio)}catch(v){error.value=message(v)}}
async function search(){error.value='';if(!filtros.anio||!filtros.mes)return void(error.value='Seleccione el año y el mes.');loading.value=true;consultado.value=true;try{data.value=(await consultarSaldos(filtros)).data}catch(v){error.value=message(v);data.value=null}finally{loading.value=false}}
function clear(){filtros.anio=null;filtros.mes=null;meses.value=[];data.value=null;consultado.value=false;error.value=''}
onMounted(load)
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/contabilidad/proceso-contable">Proceso contable</RouterLink> / Consulta de saldos</nav><header class="hero"><div class="mark">CS</div><div><small>MIA · CONTABILIDAD · PROCESO</small><h1>Consulta de saldos por periodo</h1><p>Revisa saldos deudores, acreedores y finales acumulados en la jerarquía contable.</p></div></header><p v-if="error" class="flash">{{error}}</p><form class="filters" @submit.prevent="search"><label>Año *<select v-model="filtros.anio" @change="changeYear"><option :value="null">Seleccione</option><option v-for="a in anios" :key="a" :value="a">{{a}}</option></select></label><label>Mes *<select v-model="filtros.mes"><option :value="null">Seleccione</option><option v-for="m in meses" :key="m.id" :value="m.mes">{{m.mes_label}}</option></select></label><footer><button type="button" class="soft" @click="clear">Limpiar</button><button :disabled="loading">{{loading?'Consultando…':'Consultar'}}</button></footer></form><div v-if="loading" class="empty">Consultando saldos del periodo…</div><div v-else-if="consultado&&!data" class="empty warning">No se encontraron datos para el periodo seleccionado.</div><div v-else-if="!data" class="empty">Seleccione un año y un mes para consultar los saldos.</div><main v-else><header class="summary"><div><b>Consulta de saldos</b><span>{{data.periodo.mes_label}} {{data.anio}}</span></div><div><b>Total de cuentas</b><span>{{data.cuentas.length}}</span></div></header><div class="scroll"><table><thead><tr><th>Cuenta</th><th>Descripción</th><th class="num">Saldo debe</th><th class="num">Saldo haber</th><th class="num">Saldo final</th></tr></thead><tbody><tr v-for="cue in data.cuentas" :key="cue.cta_contable" :class="{parent:cue.es_padre,leaf:!cue.es_padre}"><td><span :style="{paddingLeft:indent(cue.nivel)}">{{cue.cta_contable}}</span></td><td><span :style="{paddingLeft:indent(cue.nivel)}">{{cue.descripcion}}</span></td><td class="num">{{money(cue.saldo_debe)}}</td><td class="num">{{money(cue.saldo_haber)}}</td><td class="num"><b>{{money(cue.saldo_final)}}</b></td></tr></tbody></table></div></main></div></template>
<style scoped>
.page{--a:#238e9c;color:#35464e}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--a);text-decoration:none}.hero{padding:20px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:48px;height:48px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero small{color:var(--a);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.3rem}.hero p{margin:0;color:#7e8a90;font-size:.67rem}.flash{padding:9px;color:#a64046;background:#fff0f0}.filters{margin-top:12px;padding:15px;display:grid;grid-template-columns:1fr 1fr 2fr;gap:8px;background:#fff}.filters label{display:grid;gap:5px;font-size:.49rem}.filters select{min-width:0;padding:9px;border:1px solid #d7dfe2;border-radius:6px;background:#fff;font:inherit;font-size:.52rem}.filters footer{display:flex;align-items:end;justify-content:flex-end;gap:6px}.filters button{padding:9px 12px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.52rem}.soft{color:#64727a!important;background:#edf1f3!important}.empty{margin-top:12px;padding:45px;text-align:center;background:#fff}.warning{color:#986920;background:#fff9e8}.summary{margin-top:14px;padding:12px;display:grid;grid-template-columns:1fr 1fr;gap:8px;background:#e8f5f6}.summary div{display:grid;gap:3px;font-size:.52rem}.summary b{color:#60777a}.summary span{text-transform:uppercase;font-size:.6rem}.scroll{max-height:600px;overflow:auto;background:#fff}table{width:100%;min-width:750px;border-collapse:collapse;font-size:.5rem}th,td{padding:8px;border:1px solid #e1e7ea;text-align:left}thead{position:sticky;top:0;z-index:2;color:#fff;background:#354a55}.num{text-align:right;font-family:monospace}.parent{font-weight:600;background:#f0f2f2}.leaf{font-size:.48rem}.leaf:hover{background:#f5fafb}@media(max-width:700px){.filters,.summary{grid-template-columns:1fr}.filters footer{justify-content:flex-start}}
</style>
