<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { consultarEgp, obtenerOpcionesEgp } from '../services/estadoGananciasPerdidas'
import type { EstadoGananciasPerdidasData, FiltrosEgp, MesEgp } from '../interfaces/estadoGananciasPerdidas.interface'
const orden=['01','02','03'],titulos:Record<string,string>={'01':'1. RESULTADOS DE OPERACIÓN','02':'2. RESULTADOS DE EXPLOTACIÓN','03':'3. RESULTADOS ANTES DEL IMPUESTO A LA RENTA'}
const filtros=reactive<FiltrosEgp>({mes:null,tipo:'F',saldos:'A'}),anio=ref<number|null>(null),meses=ref<MesEgp[]>([]),data=ref<EstadoGananciasPerdidasData|null>(null),loading=ref(false),consultado=ref(false),error=ref('')
const grupos=computed(()=>orden.map(c=>[c,data.value?.grupos[c]] as const).filter((x):x is readonly [string,NonNullable<typeof x[1]>]=>Boolean(x[1])))
const message=(v:unknown)=>v instanceof Error?v.message:'No se pudo completar la consulta.'
const money=(v:number)=>new Intl.NumberFormat('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))
async function load(){loading.value=true;try{const r=await obtenerOpcionesEgp();anio.value=r.anio_vigente;meses.value=r.meses;data.value=r.data}catch(v){error.value=message(v)}finally{loading.value=false}}
async function search(){error.value='';if(!filtros.mes)return void(error.value='Seleccione el mes del reporte.');loading.value=true;consultado.value=true;try{data.value=(await consultarEgp(filtros)).data}catch(v){error.value=message(v);data.value=null}finally{loading.value=false}}
function clear(){filtros.mes=null;filtros.tipo='F';filtros.saldos='A';data.value=null;consultado.value=false;error.value=''}
onMounted(load)
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/contabilidad/proceso-contable">Proceso contable</RouterLink> / Estado de ganancias y pérdidas</nav><header class="hero"><div class="mark">EG</div><div><small>MIA · CONTABILIDAD · PROCESO</small><h1>Estado de ganancias y pérdidas</h1><p>Consulta resultados por función o naturaleza con saldos mensuales o acumulados.</p></div></header><p v-if="error" class="flash">{{error}}</p><form class="filters" @submit.prevent="search"><label>Periodo<input :value="anio??'—'" readonly></label><label>Mes *<select v-model="filtros.mes"><option :value="null">Seleccione</option><option v-for="m in meses" :key="m.id" :value="m.mes">{{m.mes_label}}</option></select></label><label>Tipo *<select v-model="filtros.tipo"><option value="F">Por función</option><option value="N">Por naturaleza</option></select></label><label>Saldos *<select v-model="filtros.saldos"><option value="A">Acumulados</option><option value="M">Mensual</option></select></label><footer><button type="button" class="soft" @click="clear">Limpiar</button><button :disabled="loading">{{loading?'Consultando…':'Consultar'}}</button></footer></form><div v-if="loading" class="empty">Calculando el estado de resultados…</div><div v-else-if="consultado&&!data" class="empty">No se encontraron datos para los filtros seleccionados.</div><div v-else-if="!data" class="empty">Seleccione el mes, el tipo de reporte y la modalidad de saldos.</div><main v-else><header class="summary"><div><b>Reporte</b><span>Por {{data.tipo_reporte==='F'?'función':'naturaleza'}}</span></div><div><b>Saldos</b><span>{{data.saldos==='M'?'Mensuales':'Acumulados'}}</span></div><div><b>Periodo</b><span>{{data.anio}} / {{data.mes}}</span></div></header><div class="scroll"><table><thead><tr><th>Cuenta</th><th>Descripción</th><th class="num">Saldo</th></tr></thead><tbody v-for="([codigo,grupo]) in grupos" :key="codigo"><tr class="section"><td colspan="3">{{titulos[codigo]??grupo.label}}</td></tr><tr v-for="row in grupo.rows" :key="`${codigo}-${row.codigo}`"><td><b>{{row.codigo}}</b></td><td>{{row.nombre}}</td><td class="num" :class="{negative:row.saldo<0}">{{money(row.saldo)}}</td></tr><tr class="total"><td colspan="2">TOTAL {{grupo.label}}</td><td class="num">{{money(grupo.total)}}</td></tr></tbody></table></div><div class="scroll resume"><table><thead><tr><th>RESUMEN</th><th class="num">Saldo</th></tr></thead><tbody><tr><td>RESULTADOS DE OPERACIÓN</td><td class="num">{{money(data.resumen.resultado_operacion)}}</td></tr><tr><td>RESULTADOS DE EXPLOTACIÓN</td><td class="num">{{money(data.resumen.resultado_explotacion)}}</td></tr><tr><td>RESULTADOS ANTES DEL IMPUESTO A LA RENTA</td><td class="num">{{money(data.resumen.resultado_antes_impuesto)}}</td></tr><tr class="total result"><td>TOTAL RESULTADO</td><td class="num">{{money(data.resumen.total_resultado)}}</td></tr></tbody></table></div></main></div></template>
<style scoped>
.page{--a:#b94c4f;color:#35464e}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--a);text-decoration:none}.hero{padding:20px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:48px;height:48px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero small{color:var(--a);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.3rem}.hero p{margin:0;color:#7e8a90;font-size:.67rem}.flash{padding:9px;color:#a64046;background:#fff0f0}.filters{margin-top:12px;padding:15px;display:grid;grid-template-columns:repeat(4,1fr) auto;gap:8px;background:#fff}.filters label{display:grid;gap:5px;font-size:.49rem}.filters select,.filters input{min-width:0;padding:9px;border:1px solid #d7dfe2;border-radius:6px;background:#fff;font:inherit;font-size:.52rem}.filters input{background:#f3f6f7}.filters footer{display:flex;align-items:end;justify-content:flex-end;gap:6px}.filters button{padding:9px 12px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.52rem}.soft{color:#64727a!important;background:#edf1f3!important}.empty{margin-top:12px;padding:45px;text-align:center;background:#fff}.summary{margin-top:14px;padding:12px;display:grid;grid-template-columns:repeat(3,1fr);gap:8px;background:#fff}.summary div{display:grid;gap:3px;font-size:.52rem}.summary b{color:#728087}.summary span{text-transform:capitalize}.scroll{margin-top:12px;overflow:auto;background:#fff}table{width:100%;min-width:650px;border-collapse:collapse;font-size:.52rem}th,td{padding:8px;border:1px solid #e1e7ea;text-align:left}thead{color:#fff;background:#354a55}.num{text-align:right;font-family:monospace}.negative{color:#a64046}.section{color:#fff;background:#2c3e50;font-weight:700}.total{background:#d5dbdb;font-weight:700}.total td:first-child{text-align:right}.resume{max-width:760px;margin-left:auto}.resume tbody tr{font-weight:700}.result{color:#fff;background:#2c3e50}@media(max-width:850px){.filters{grid-template-columns:repeat(2,1fr)}.filters footer{grid-column:1/-1}.summary{grid-template-columns:1fr}}@media(max-width:500px){.filters{grid-template-columns:1fr}}
</style>
