<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { consultarLibroInventarios, obtenerOpcionesLibroInventarios } from '../services/libroInventarios'
import type { DatosLibroInventarios, FiltrosLibroInventarios, MesLibroInventarios } from '../interfaces/libroInventarios.interface'
const filtros=reactive<FiltrosLibroInventarios>({mes:null,digitos:null}),anio=ref<number|null>(null),meses=ref<MesLibroInventarios[]>([]),digitos=ref<number[]>([]),data=ref<DatosLibroInventarios|null>(null),loading=ref(false),consultado=ref(false),error=ref('')
const labels:Record<string,string>={ACTIVO:'I. ACTIVO',PASIVO:'II. PASIVO',PATRIMONIO:'III. PATRIMONIO'}
const secciones=computed(()=>Object.entries(data.value??{}))
const message=(v:unknown)=>v instanceof Error?v.message:'No se pudo completar la consulta.'
const money=(v:number)=>new Intl.NumberFormat('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))
async function load(){loading.value=true;try{const r=await obtenerOpcionesLibroInventarios();anio.value=r.anio_vigente;meses.value=r.meses;digitos.value=r.digitos_disponibles.filter(d=>d<=r.digitos_plan);data.value=r.data}catch(v){error.value=message(v)}finally{loading.value=false}}
async function search(){error.value='';if(!filtros.mes||!filtros.digitos)return void(error.value='Seleccione el mes y el número de dígitos.');loading.value=true;consultado.value=true;try{data.value=(await consultarLibroInventarios(filtros)).data}catch(v){error.value=message(v);data.value=null}finally{loading.value=false}}
function clear(){filtros.mes=null;filtros.digitos=null;data.value=null;consultado.value=false;error.value=''}
onMounted(load)
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/contabilidad/proceso-contable">Proceso contable</RouterLink> / Libro de inventarios y balances</nav><header class="hero"><div class="mark">LI</div><div><small>MIA · CONTABILIDAD · PROCESO</small><h1>Libro de inventarios y balances</h1><p>Consulta los saldos clasificados en activo, pasivo y patrimonio.</p></div></header><p v-if="error" class="flash">{{error}}</p><form class="filters" @submit.prevent="search"><label>Periodo<input :value="anio??'—'" readonly></label><label>Mes *<select v-model="filtros.mes"><option :value="null">Seleccione</option><option v-for="m in meses" :key="m.id" :value="m.mes">{{m.mes_label}}</option></select></label><label>Número de dígitos *<select v-model="filtros.digitos"><option :value="null">Seleccione</option><option v-for="d in digitos" :key="d" :value="d">{{d}} dígitos</option></select></label><footer><button type="button" class="soft" @click="clear">Limpiar</button><button :disabled="loading">{{loading?'Consultando…':'Consultar'}}</button></footer></form><div v-if="loading" class="empty">Consolidando inventarios y balances…</div><div v-else-if="consultado&&!secciones.length" class="empty">No se encontraron datos para los filtros seleccionados.</div><div v-else-if="!secciones.length" class="empty">Seleccione el mes y el número de dígitos para consultar.</div><main v-else><header class="summary"><div><b>Periodo</b><span>{{anio}}</span></div><div><b>Nivel del plan</b><span>{{filtros.digitos}} dígitos</span></div><div><b>Secciones</b><span>{{secciones.length}}</span></div></header><div class="scroll"><table><thead><tr><th colspan="2">Cuenta / Descripción</th><th colspan="2" class="center">Saldos</th></tr><tr><th>Cuenta</th><th>Descripción</th><th class="num">Debe</th><th class="num">Haber</th></tr></thead><tbody v-for="([nombre,seccion]) in secciones" :key="nombre"><tr class="section"><td colspan="4">{{labels[nombre]??nombre}}</td></tr><tr v-for="row in seccion.rows" :key="row.cta_contable"><td><b>{{row.cta_contable}}</b></td><td>{{row.descripcion}}</td><td class="num">{{row.debe>0?money(row.debe):''}}</td><td class="num">{{row.haber>0?money(row.haber):''}}</td></tr><tr class="total"><td colspan="2">TOTAL {{nombre}}</td><td class="num">{{money(seccion.total_debe)}}</td><td class="num">{{money(seccion.total_haber)}}</td></tr></tbody></table></div><div class="scroll resume"><table><thead><tr><th colspan="3" class="center">RESUMEN</th></tr><tr><th></th><th class="num">Debe</th><th class="num">Haber</th></tr></thead><tbody><tr v-for="([nombre,seccion]) in secciones" :key="nombre"><td><b>{{labels[nombre]??nombre}}</b></td><td class="num">{{seccion.neto>0?money(seccion.neto):''}}</td><td class="num">{{seccion.neto<0?money(-seccion.neto):''}}</td></tr></tbody></table></div></main></div></template>
<style scoped>
.page{--a:#3d72a9;color:#35464e}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--a);text-decoration:none}.hero{padding:20px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:48px;height:48px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero small{color:var(--a);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.3rem}.hero p{margin:0;color:#7e8a90;font-size:.67rem}.flash{padding:9px;color:#a64046;background:#fff0f0}.filters{margin-top:12px;padding:15px;display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:8px;background:#fff}.filters label{display:grid;gap:5px;font-size:.49rem}.filters select,.filters input{min-width:0;padding:9px;border:1px solid #d7dfe2;border-radius:6px;background:#fff;font:inherit;font-size:.52rem}.filters input{background:#f3f6f7}.filters footer{display:flex;align-items:end;justify-content:flex-end;gap:6px}.filters button{padding:9px 12px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.52rem}.soft{color:#64727a!important;background:#edf1f3!important}.empty{margin-top:12px;padding:45px;text-align:center;background:#fff}.summary{margin-top:14px;padding:12px;display:grid;grid-template-columns:repeat(3,1fr);gap:8px;background:#fff}.summary div{display:grid;gap:3px;font-size:.52rem}.summary b{color:#728087}.scroll{margin-top:12px;overflow:auto;background:#fff}table{width:100%;min-width:700px;border-collapse:collapse;font-size:.52rem}th,td{padding:8px;border:1px solid #e1e7ea;text-align:left}thead{color:#fff;background:#354a55}.num{text-align:right;font-family:monospace}.center{text-align:center}.section{color:#fff;background:#2c3e50;font-weight:700}.total{background:#dce2e4;font-weight:700}.total td:first-child{text-align:right}.resume{max-width:700px;margin-left:auto}.resume tbody tr{font-weight:600}@media(max-width:700px){.filters,.summary{grid-template-columns:1fr}.filters footer{justify-content:flex-start}}
</style>
