<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import type { ClasificacionCuentaFlujo, TipoFlujoCuenta } from '../interfaces/cuenta-tesoreria.interface'
import { asignarTipoFlujoCaja, listarClasificacionFlujoCaja } from '../services/cuenta-tesoreria'
const rows = ref<ClasificacionCuentaFlujo[]>([]), search = ref(''), type = ref(''), loading = ref(false), error = ref(''), success = ref(''), selected = ref<ClasificacionCuentaFlujo | null>(null), selectedType = ref<TipoFlujoCuenta>('')
const filtered = computed(() => { const q = search.value.toLocaleUpperCase(); return rows.value.filter(x => (!q || `${x.cta_contable} ${x.descripcion}`.toLocaleUpperCase().includes(q)) && (!type.value || (type.value === 'N' ? !x.tipo_flujo_caja : x.tipo_flujo_caja === type.value))) })
const totals = computed(() => ({ ingresos: rows.value.filter(x => x.tipo_flujo_caja === 'I').length, egresos: rows.value.filter(x => x.tipo_flujo_caja === 'E').length, pendientes: rows.value.filter(x => !x.tipo_flujo_caja).length }))
const message = (e: unknown) => e instanceof Error ? e.message : 'No se pudo completar la operación.'
async function load() { loading.value = true; error.value = ''; try { rows.value = await listarClasificacionFlujoCaja() } catch (e) { error.value = message(e) } finally { loading.value = false } }
function configure(item: ClasificacionCuentaFlujo) { selected.value = item; selectedType.value = item.tipo_flujo_caja || '' }
async function save() { if (!selected.value || !confirm('¿Desea actualizar la clasificación de flujo de caja?')) return; loading.value = true; error.value = ''; try { await asignarTipoFlujoCaja(selected.value.id, selectedType.value); success.value = 'Clasificación actualizada correctamente.'; selected.value = null; await load() } catch (e) { error.value = message(e) } finally { loading.value = false } }
onMounted(load)
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / Administración / Finanzas / Clasificación para flujo de caja</nav><header class="hero"><div class="mark">IE</div><div><small>MIA · FINANZAS · CONFIGURACIÓN</small><h1>Clasificación para flujo de caja</h1><p>Establece las cuentas contables de ingreso y egreso utilizadas en el flujo de caja.</p></div><strong>{{rows.length}} cuentas de nivel 1</strong></header><p v-if="error" class="flash badmsg">{{error}}</p><p v-if="success" class="flash okmsg">{{success}}</p><section class="summary"><article class="income"><small>INGRESOS</small><b>{{totals.ingresos}}</b></article><article class="expense"><small>EGRESOS</small><b>{{totals.egresos}}</b></article><article class="pending"><small>NO CONFIGURADAS</small><b>{{totals.pendientes}}</b></article></section><section class="filters"><input v-model.trim="search" placeholder="Buscar cuenta o descripción"><select v-model="type"><option value="">Todas las clasificaciones</option><option value="I">Ingresos</option><option value="E">Egresos</option><option value="N">No configuradas</option></select><button class="soft" @click="search='';type=''">Limpiar</button></section><section class="card"><div v-if="loading" class="empty">Procesando…</div><div v-else-if="!filtered.length" class="empty">No se encontraron cuentas contables de nivel 1.</div><div v-else class="scroll"><table><thead><tr><th>ID</th><th>Cuenta</th><th>Descripción</th><th>Nivel</th><th>Naturaleza</th><th>Tipo flujo de caja</th><th>Estado</th><th>Acción</th></tr></thead><tbody><tr v-for="item in filtered" :key="item.id"><td>{{item.id}}</td><td><b>{{item.cta_contable}}</b></td><td>{{item.descripcion}}</td><td>{{item.nivel}}</td><td>{{item.naturaleza_label||'-'}}</td><td><span :class="item.tipo_flujo_caja==='I'?'good':item.tipo_flujo_caja==='E'?'bad':'neutral'">{{item.tipo_flujo_caja==='I'?'INGRESO':item.tipo_flujo_caja==='E'?'EGRESO':'NO CONFIGURADO'}}</span></td><td><span :class="item.activa?'good':'bad'">{{item.activa?'ACTIVA':'INACTIVA'}}</span></td><td><button @click="configure(item)">Configurar</button></td></tr></tbody></table></div></section><div v-if="selected" class="backdrop" @mousedown.self="selected=null"><form class="dialog" @submit.prevent="save"><header><div><small>CONFIGURAR FLUJO DE CAJA</small><h2>{{selected.cta_contable}}</h2></div><button type="button" @click="selected=null">×</button></header><dl><dt>Descripción</dt><dd>{{selected.descripcion}}</dd><dt>Nivel</dt><dd>{{selected.nivel}}</dd><dt>Naturaleza</dt><dd>{{selected.naturaleza_label||'-'}}</dd></dl><label>Clasificación<select v-model="selectedType"><option value="">No configurado</option><option value="I">Cuenta de ingreso</option><option value="E">Cuenta de egreso</option></select></label><footer><button type="button" class="soft" @click="selected=null">Cancelar</button><button :disabled="loading">Guardar clasificación</button></footer></form></div></div></template>
<style scoped>
.page{--a:#176d78;color:#344750}nav{margin-bottom:15px;color:#91a0a5;font-size:.68rem}nav a{color:var(--a)}.hero{display:flex;align-items:center;gap:14px;padding:20px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:50px;height:50px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero>div:nth-child(2){flex:1}.hero small,.dialog small{color:var(--a);font-size:.5rem;font-weight:800}.hero h1{margin:3px 0;font-size:1.3rem}.hero p{margin:0;color:#7c8b91;font-size:.65rem}.hero strong{font-size:.55rem}button{padding:8px 11px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.5rem;cursor:pointer}.soft{color:#607078;background:#edf2f3}.flash{padding:10px;border-radius:6px;font-size:.55rem}.badmsg{color:#9b3d48;background:#fdebee}.okmsg{color:#236c50;background:#e8f7ee}.summary{margin-top:11px;display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.summary article{padding:13px;border-left:4px solid;background:#fff}.summary small{font-size:.46rem;font-weight:800}.summary b{display:block;text-align:right;font-size:1.2rem}.income{color:#267153}.expense{color:#a4424b}.pending{color:#77858a}.filters{margin-top:10px;padding:13px;display:grid;grid-template-columns:1fr 1fr auto;gap:7px;background:#fff}.filters input,.filters select,.dialog select{box-sizing:border-box;width:100%;padding:9px;border:1px solid #d5dfe2;border-radius:6px;background:#fff;font-size:.51rem}.card{margin-top:10px;background:#fff}.scroll{overflow:auto}table{width:100%;min-width:950px;border-collapse:collapse;font-size:.5rem}th,td{padding:10px;border-bottom:1px solid #e3e9eb;text-align:left}th{color:#fff;background:#435d6c}.good,.bad,.neutral{padding:4px 8px;border-radius:10px;font-size:.43rem;font-weight:800}.good{color:#267153;background:#e5f7ec}.bad{color:#9d414a;background:#fdebed}.neutral{color:#68777d;background:#edf1f2}.empty{padding:50px;text-align:center}.backdrop{position:fixed;z-index:100;inset:0;padding:20px;display:grid;place-items:center;background:#172b3d88}.dialog{width:min(520px,100%);padding:20px;box-sizing:border-box;border-radius:12px;background:#fff}.dialog>header{display:flex}.dialog>header div{flex:1}.dialog h2{margin:3px 0 15px}.dialog>header button{color:#66757b;background:none;font-size:1.2rem}.dialog dl{display:grid;grid-template-columns:1fr 2fr;margin:0;font-size:.51rem}.dialog dt,.dialog dd{margin:0;padding:9px;border-bottom:1px solid #e2e9eb}.dialog dt{font-weight:700;background:#f2f6f7}.dialog label{display:grid;gap:5px;margin:15px 0;font-size:.52rem;font-weight:700}.dialog footer{display:flex;justify-content:center;gap:8px}@media(max-width:650px){.filters,.summary{grid-template-columns:1fr}.hero{flex-wrap:wrap}.mark{display:none}}
</style>
