<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import type { ConceptoCuenta, ConceptoCuentaPayload } from '../interfaces/concepto-cuenta.interface'
import { cambiarEstadoConceptoCuenta, eliminarConceptoCuenta, guardarConceptoCuenta, listarConceptosCuenta, obtenerConceptoCuenta } from '../services/concepto-cuenta'

const rows = ref<ConceptoCuenta[]>([]), search = ref(''), loading = ref(false), error = ref(''), success = ref(''), showForm = ref(false), editing = ref<number | null>(null)
const form = reactive<ConceptoCuentaPayload>({ nombre: '', descripcion: '', orden: 1 })
const message = (e: unknown) => e instanceof Error ? e.message : 'No se pudo completar la operación.'
async function load() { loading.value = true; error.value = ''; try { rows.value = await listarConceptosCuenta(search.value) } catch (e) { error.value = message(e) } finally { loading.value = false } }
function create() { editing.value = null; Object.assign(form, { nombre: '', descripcion: '', orden: Math.max(1, ...rows.value.map(x => x.orden + 1)) }); showForm.value = true }
async function edit(item: ConceptoCuenta) { loading.value = true; try { const value = await obtenerConceptoCuenta(item.id); editing.value = value.id; Object.assign(form, { nombre: value.nombre, descripcion: value.descripcion, orden: value.orden }); showForm.value = true } catch (e) { error.value = message(e) } finally { loading.value = false } }
async function save() { loading.value = true; error.value = ''; try { await guardarConceptoCuenta(editing.value, { ...form }); success.value = `Concepto de cuenta ${editing.value ? 'actualizado' : 'registrado'} correctamente.`; showForm.value = false; await load() } catch (e) { error.value = message(e) } finally { loading.value = false } }
async function toggle(item: ConceptoCuenta) { const action = item.activo ? 'desactivar' : 'activar'; if (!confirm(`¿Desea ${action} el concepto ${item.nombre}?`)) return; loading.value = true; try { await cambiarEstadoConceptoCuenta(item.id); success.value = `Concepto ${item.activo ? 'desactivado' : 'activado'} correctamente.`; await load() } catch (e) { error.value = message(e) } finally { loading.value = false } }
async function remove(item: ConceptoCuenta) { if (!confirm(`¿Eliminar el concepto ${item.nombre}? Esta operación lo retirará del catálogo.`)) return; loading.value = true; try { await eliminarConceptoCuenta(item.id); success.value = 'Concepto de cuenta eliminado correctamente.'; await load() } catch (e) { error.value = message(e) } finally { loading.value = false } }
function clear() { search.value = ''; load() }
onMounted(load)
</script>

<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / Administración / Finanzas / Conceptos de cuenta</nav><header class="hero"><div class="mark">CC</div><div><small>MIA · FINANZAS · MAESTROS</small><h1>Conceptos de cuenta</h1><p>Catálogo ordenado de conceptos utilizados en la gestión financiera.</p></div><strong>{{rows.length}} registros</strong><button @click="create">+ Nuevo concepto</button></header><p v-if="error" class="flash badmsg">{{error}}</p><p v-if="success" class="flash okmsg">{{success}}</p><form class="filters" @submit.prevent="load"><input v-model.trim="search" placeholder="Buscar por nombre, descripción u orden"><button>Buscar</button><button type="button" class="soft" @click="clear">Limpiar</button></form><section class="card"><div v-if="loading" class="empty">Procesando…</div><div v-else-if="!rows.length" class="empty">No se encontraron conceptos de cuenta.</div><div v-else class="grid"><article v-for="item in rows" :key="item.id" :class="{inactive:!item.activo}"><header><span class="order">{{item.orden}}</span><span :class="item.activo?'good':'bad'">{{item.activo?'ACTIVO':'INACTIVO'}}</span></header><h2>{{item.nombre}}</h2><p>{{item.descripcion}}</p><footer><button class="edit" @click="edit(item)">Editar</button><button :class="item.activo?'danger':'activate'" @click="toggle(item)">{{item.activo?'Desactivar':'Activar'}}</button><button class="delete" @click="remove(item)">Eliminar</button></footer></article></div></section><div v-if="showForm" class="backdrop" @mousedown.self="showForm=false"><form class="dialog" @submit.prevent="save"><header><div><small>{{editing?'EDICIÓN':'NUEVO REGISTRO'}}</small><h2>{{editing?'Editar':'Registrar'}} concepto de cuenta</h2></div><button type="button" @click="showForm=false">×</button></header><label>Nombre<input v-model.trim="form.nombre" maxlength="100" required placeholder="Nombre del concepto"></label><label>Descripción<textarea v-model.trim="form.descripcion" maxlength="150" rows="4" required placeholder="Descripción del concepto"></textarea></label><label>Orden<input v-model.number="form.orden" type="number" min="1" step="1" required></label><footer><button type="button" class="soft" @click="showForm=false">Cancelar</button><button :disabled="loading">Guardar</button></footer></form></div></div></template>

<style scoped>
.page{--a:#176d78;color:#344750}nav{margin-bottom:15px;color:#91a0a5;font-size:.68rem}nav a{color:var(--a)}.hero{display:flex;align-items:center;gap:14px;padding:20px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:50px;height:50px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero>div:nth-child(2){flex:1}.hero small,.dialog small{color:var(--a);font-size:.5rem;font-weight:800}.hero h1{margin:3px 0;font-size:1.3rem}.hero p{margin:0;color:#7c8b91;font-size:.65rem}.hero strong{font-size:.55rem}button{padding:8px 11px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.5rem;cursor:pointer}.soft{color:#607078;background:#edf2f3}.flash{padding:10px;border-radius:6px;font-size:.55rem}.badmsg{color:#9b3d48;background:#fdebee}.okmsg{color:#236c50;background:#e8f7ee}.filters{margin-top:11px;padding:13px;display:grid;grid-template-columns:1fr auto auto;gap:7px;background:#fff}.filters input,.dialog input,.dialog textarea{box-sizing:border-box;width:100%;padding:9px;border:1px solid #d5dfe2;border-radius:6px;background:#fff;font-size:.52rem}.card{margin-top:11px;background:#fff}.grid{padding:13px;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.grid article{display:flex;flex-direction:column;min-height:145px;padding:14px;border:1px solid #dce5e7;border-top:4px solid var(--a);border-radius:8px;background:#fff}.grid article.inactive{opacity:.72;border-top-color:#9ca8ac}.grid article header{display:flex;justify-content:space-between}.order{display:grid;place-items:center;width:26px;height:26px;border-radius:50%;color:#fff;background:#435d6c;font-size:.52rem;font-weight:800}.grid h2{margin:12px 0 5px;font-size:.75rem}.grid p{flex:1;margin:0;color:#718086;font-size:.52rem}.grid footer{display:flex;gap:5px;margin-top:15px}.good,.bad{padding:4px 8px;border-radius:10px;font-size:.43rem;font-weight:800}.good{color:#267153;background:#e5f7ec}.bad{color:#9d414a;background:#fdebed}.edit{background:#c98a24}.danger,.delete{background:#b74b54}.delete{margin-left:auto}.activate{background:#27875f}.empty{padding:50px;text-align:center}.backdrop{position:fixed;z-index:100;inset:0;padding:20px;display:grid;place-items:center;background:#172b3d88}.dialog{width:min(520px,100%);padding:20px;box-sizing:border-box;border-radius:12px;background:#fff}.dialog>header{display:flex}.dialog>header div{flex:1}.dialog h2{margin:3px 0 15px}.dialog>header button{color:#66757b;background:none;font-size:1.2rem}.dialog label{display:grid;gap:5px;margin:10px 0;color:#5d7078;font-size:.52rem;font-weight:700}.dialog footer{display:flex;justify-content:center;gap:8px;margin-top:15px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.grid,.filters{grid-template-columns:1fr}.hero{flex-wrap:wrap}.mark{display:none}}
</style>
