<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue'
import type {ConfiguracionTipoDocumento,ConfiguracionTipoDocumentoPayload} from '../interfaces/configuracion-tipo-documento.interface'
import {actualizarConfiguracionTipoDocumento,listarConfiguracionesTipoDocumento,obtenerConfiguracionTipoDocumento} from '../services/configuracion-tipo-documento'
const fields:[keyof ConfiguracionTipoDocumentoPayload,string][]=[['origen_suministro','Origen suministro'],['origen_personal','Origen personal'],['origen_bancos','Origen bancos'],['doc_viaticos','Documento de viáticos'],['doc_anticipos','Documento de anticipos'],['doc_detraccion','Documento de detracción'],['doc_descuento','Documento de descuento'],['doc_cts','Documento de CTS'],['doc_ctacte','Documento de cuenta corriente']]
const rows=ref<ConfiguracionTipoDocumento[]>([]),search=ref(''),page=ref(1),lastPage=ref(1),total=ref(0),loading=ref(false),error=ref(''),success=ref(''),modal=ref(false),editing=ref<ConfiguracionTipoDocumento|null>(null)
const blank=():ConfiguracionTipoDocumentoPayload=>({origen_suministro:false,origen_personal:false,origen_bancos:false,doc_viaticos:false,doc_anticipos:false,doc_detraccion:false,doc_descuento:false,doc_cts:false,doc_ctacte:false}),form=reactive<ConfiguracionTipoDocumentoPayload>(blank()),message=(e:unknown)=>e instanceof Error?e.message:'No se pudo completar la operación.'
async function load(next=1){loading.value=true;error.value='';try{const r=await listarConfiguracionesTipoDocumento(search.value,next);rows.value=r.data;page.value=r.current_page;lastPage.value=r.last_page;total.value=r.total}catch(e){error.value=message(e)}finally{loading.value=false}}
async function edit(row:ConfiguracionTipoDocumento){loading.value=true;try{const x=await obtenerConfiguracionTipoDocumento(row.id);editing.value={...row,...x};Object.assign(form,blank(),Object.fromEntries(fields.map(([key])=>[key,Boolean(x[key])])));modal.value=true}catch(e){error.value=message(e)}finally{loading.value=false}}
async function save(){if(!editing.value)return;loading.value=true;error.value='';try{await actualizarConfiguracionTipoDocumento(editing.value.id,{...form});success.value='Configuración financiera actualizada correctamente.';modal.value=false;await load(page.value)}catch(e){error.value=message(e)}finally{loading.value=false}}
const enabled=(row:ConfiguracionTipoDocumento)=>fields.filter(([key])=>Boolean(row[key])).map(([,label])=>label)
onMounted(()=>load())
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / Administración / Finanzas / Configuración de documentos</nav><header class="hero"><b>TD</b><div><small>MIA · FINANZAS · MAESTROS</small><h1>Configuración financiera de documentos</h1><p>Define el origen y uso financiero de cada tipo de documento contable.</p></div><strong>{{total}} documentos</strong></header><p v-if="error" class="flash bad">{{error}}</p><p v-if="success" class="flash ok">{{success}}</p><form class="filters" @submit.prevent="load(1)"><input v-model.trim="search" placeholder="Buscar por ID, nombre o diminutivo"><button>Buscar</button><button type="button" class="soft" @click="search='';load(1)">Limpiar</button></form><section class="card"><div v-if="loading" class="empty">Procesando…</div><div v-else-if="!rows.length" class="empty">No se encontraron tipos de documento.</div><div v-else class="grid"><article v-for="x in rows" :key="x.id"><header><b>{{x.diminutivo||'#'+x.id}}</b><button @click="edit(x)">Configurar</button></header><h3>{{x.nombre}}</h3><div class="tags"><i v-for="tag in enabled(x)" :key="tag">{{tag}}</i><span v-if="!enabled(x).length">Sin configuración financiera</span></div></article></div><footer v-if="lastPage>1" class="pager"><button :disabled="page<=1" @click="load(page-1)">Anterior</button><span>{{page}} / {{lastPage}}</span><button :disabled="page>=lastPage" @click="load(page+1)">Siguiente</button></footer></section><div v-if="modal&&editing" class="backdrop" @mousedown.self="modal=false"><form class="dialog" @submit.prevent="save"><header><div><small>TIPO DE DOCUMENTO</small><h2>{{editing.diminutivo}} · {{editing.nombre}}</h2></div><button type="button" @click="modal=false">×</button></header><section><label v-for="[key,label] in fields" :key="key" :class="{selected:form[key]}"><input v-model="form[key]" type="checkbox"><span>{{label}}</span></label></section><footer><button type="button" class="soft" @click="modal=false">Cancelar</button><button :disabled="loading">Guardar configuración</button></footer></form></div></div></template>
<style scoped>.page{--a:#176d78;color:#344750}nav{margin-bottom:15px;color:#91a0a5;font-size:.68rem}.hero{display:flex;align-items:center;gap:14px;padding:20px;border-left:5px solid var(--a);background:#fff}.hero>b{padding:16px;border-radius:10px;color:#fff;background:var(--a)}.hero>div{flex:1}.hero small,.dialog small{color:var(--a);font-size:.49rem}.hero h1{margin:3px 0;font-size:1.3rem}.hero p{margin:0;font-size:.65rem}button{padding:8px 11px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.5rem}.soft{color:#607078;background:#edf2f3}.flash{padding:10px}.bad{color:#9b3d48;background:#fdebee}.ok{color:#236c50;background:#e8f7ee}.filters{margin-top:11px;padding:13px;display:grid;grid-template-columns:1fr auto auto;gap:7px;background:#fff}.filters input{padding:9px;border:1px solid #d5dfe2;border-radius:6px}.card{margin-top:11px;background:#fff}.grid{padding:13px;display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.grid article{min-height:120px;padding:14px;border:1px solid #dce5e7;border-top:4px solid var(--a)}.grid article header{display:flex;justify-content:space-between}.grid h3{font-size:.62rem}.tags i{display:inline-block;margin:2px;padding:4px 7px;border-radius:10px;color:#267153;background:#e5f7ec;font-size:.41rem}.tags span{color:#98a5aa;font-size:.48rem}.empty{padding:50px;text-align:center}.pager{padding:12px;display:flex;justify-content:center;gap:8px}.backdrop{position:fixed;z-index:100;inset:0;display:grid;place-items:center;padding:20px;background:#172b3d88}.dialog{width:min(680px,100%);padding:20px;border-radius:12px;background:#fff}.dialog>header{display:flex}.dialog>header div{flex:1}.dialog h2{margin:3px 0 15px}.dialog>header button{color:#66757b;background:none;font-size:1.2rem}.dialog>section{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.dialog section label{display:flex;align-items:center;gap:7px;padding:12px;border:1px solid #dce5e7;border-radius:7px;font-size:.51rem}.dialog section label.selected{border-color:var(--a);background:#edf7f8}.dialog>footer{display:flex;justify-content:center;gap:8px;margin-top:15px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.grid,.filters,.dialog>section{grid-template-columns:1fr}.hero{flex-wrap:wrap}}</style>