<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import type { DestinoMovilidad, DestinoMovilidadPayload } from '../interfaces/destino-movilidad.interface'
import { cambiarEstadoDestinoMovilidad, guardarDestinoMovilidad, listarDestinosMovilidad, obtenerDestinoMovilidad } from '../services/destino-movilidad'
const rows = ref<DestinoMovilidad[]>([]), search = ref(''), state = ref(''), loading = ref(false), error = ref(''), success = ref(''), showForm = ref(false), editing = ref<number | null>(null)
const form = reactive<DestinoMovilidadPayload>({ codigo: '', denominacion: '' })
const filtered = computed(() => { const q = search.value.toLocaleUpperCase(); return rows.value.filter(x => (!q || `${x.codigo} ${x.denominacion}`.toLocaleUpperCase().includes(q)) && (state.value === '' || x.activo === (state.value === '1'))) })
const message = (e: unknown) => e instanceof Error ? e.message : 'No se pudo completar la operación.'
async function load() { loading.value = true; error.value = ''; try { rows.value = await listarDestinosMovilidad() } catch (e) { error.value = message(e) } finally { loading.value = false } }
function create() { editing.value = null; Object.assign(form, { codigo: '', denominacion: '' }); showForm.value = true }
async function edit(item: DestinoMovilidad) { loading.value = true; try { const value = await obtenerDestinoMovilidad(item.id); editing.value = value.id; Object.assign(form, { codigo: value.codigo, denominacion: value.denominacion }); showForm.value = true } catch (e) { error.value = message(e) } finally { loading.value = false } }
async function save() { loading.value = true; error.value = ''; try { await guardarDestinoMovilidad(editing.value, { ...form }); success.value = `Destino de movilidad ${editing.value ? 'actualizado' : 'registrado'} correctamente.`; showForm.value = false; await load() } catch (e) { error.value = message(e) } finally { loading.value = false } }
async function toggle(item: DestinoMovilidad) { const action = item.activo ? 'inactivar' : 'activar'; if (!confirm(`¿Desea ${action} ${item.denominacion}?`)) return; loading.value = true; try { await cambiarEstadoDestinoMovilidad(item.id); success.value = `Destino ${item.activo ? 'inactivado' : 'activado'} correctamente.`; await load() } catch (e) { error.value = message(e) } finally { loading.value = false } }
function clear() { search.value = ''; state.value = '' }
onMounted(load)
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / Administración / Finanzas / Destinos de movilidad</nav><header class="hero"><div class="mark">DM</div><div><small>MIA · FINANZAS · CAJA CHICA</small><h1>Destinos de movilidad</h1><p>Catálogo de destinos utilizados para registrar gastos de movilidad.</p></div><strong>{{filtered.length}} registros</strong><button @click="create">+ Nuevo destino</button></header><p v-if="error" class="flash badmsg">{{error}}</p><p v-if="success" class="flash okmsg">{{success}}</p><section class="filters"><input v-model.trim="search" placeholder="Buscar por código o denominación"><select v-model="state"><option value="">Todos los estados</option><option value="1">Activos</option><option value="0">Inactivos</option></select><button class="soft" @click="clear">Limpiar</button></section><section class="card"><div v-if="loading" class="empty">Procesando…</div><div v-else-if="!filtered.length" class="empty">No se encontraron destinos de movilidad.</div><div v-else class="grid"><article v-for="item in filtered" :key="item.id" :class="{inactive:!item.activo}"><header><b>{{item.codigo}}</b><span :class="item.activo?'good':'bad'">{{item.activo?'ACTIVO':'INACTIVO'}}</span></header><h2>{{item.denominacion}}</h2><footer><button class="edit" @click="edit(item)">Editar</button><button :class="item.activo?'danger':'activate'" @click="toggle(item)">{{item.activo?'Inactivar':'Activar'}}</button></footer></article></div></section><div v-if="showForm" class="backdrop" @mousedown.self="showForm=false"><form class="dialog" @submit.prevent="save"><header><div><small>{{editing?'EDICIÓN':'NUEVO REGISTRO'}}</small><h2>{{editing?'Editar':'Registrar'}} destino de movilidad</h2></div><button type="button" @click="showForm=false">×</button></header><label>Código<input v-model.trim="form.codigo" maxlength="10" required placeholder="Ej. DM-01"></label><label>Denominación<input v-model.trim="form.denominacion" maxlength="150" required placeholder="Nombre del destino"></label><footer><button type="button" class="soft" @click="showForm=false">Cancelar</button><button :disabled="loading">Guardar</button></footer></form></div></div></template>
<style scoped>
.page{--a:#176d78;color:#344750}nav{margin-bottom:15px;color:#91a0a5;font-size:.68rem}nav a{color:var(--a)}.hero{display:flex;align-items:center;gap:14px;padding:20px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:50px;height:50px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero>div:nth-child(2){flex:1}.hero small,.dialog small{color:var(--a);font-size:.5rem;font-weight:800}.hero h1{margin:3px 0;font-size:1.3rem}.hero p{margin:0;color:#7c8b91;font-size:.65rem}.hero strong{font-size:.55rem}button{padding:8px 11px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.5rem;cursor:pointer}.soft{color:#607078;background:#edf2f3}.flash{padding:10px;border-radius:6px;font-size:.55rem}.badmsg{color:#9b3d48;background:#fdebee}.okmsg{color:#236c50;background:#e8f7ee}.filters{margin-top:11px;padding:13px;display:grid;grid-template-columns:2fr 1fr auto;gap:7px;background:#fff}.filters input,.filters select,.dialog input{box-sizing:border-box;width:100%;padding:9px;border:1px solid #d5dfe2;border-radius:6px;background:#fff;font-size:.52rem}.card{margin-top:11px;background:#fff}.grid{padding:13px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.grid article{display:flex;flex-direction:column;min-height:110px;padding:14px;border:1px solid #dce5e7;border-top:4px solid var(--a);border-radius:8px}.grid article.inactive{opacity:.7;border-top-color:#99a5aa}.grid article header{display:flex;justify-content:space-between;align-items:center}.grid article header>b{color:var(--a);font-size:.62rem}.grid h2{flex:1;margin:14px 0;font-size:.68rem}.grid footer{display:flex;gap:5px}.good,.bad{padding:4px 8px;border-radius:10px;font-size:.42rem;font-weight:800}.good{color:#267153;background:#e5f7ec}.bad{color:#9d414a;background:#fdebed}.edit{background:#c98a24}.danger{background:#b74b54}.activate{background:#27875f}.empty{padding:50px;text-align:center}.backdrop{position:fixed;z-index:100;inset:0;padding:20px;display:grid;place-items:center;background:#172b3d88}.dialog{width:min(500px,100%);padding:20px;box-sizing:border-box;border-radius:12px;background:#fff}.dialog>header{display:flex}.dialog>header div{flex:1}.dialog h2{margin:3px 0 15px}.dialog>header button{color:#66757b;background:none;font-size:1.2rem}.dialog label{display:grid;gap:5px;margin:10px 0;font-size:.52rem;font-weight:700}.dialog footer{display:flex;justify-content:center;gap:8px;margin-top:15px}@media(max-width:950px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.filters,.grid{grid-template-columns:1fr}.hero{flex-wrap:wrap}.mark{display:none}}
</style>
