<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import type { FuenteFinanciamiento, FuenteFinanciamientoPayload } from '../interfaces/fuente-financiamiento.interface'
import { guardarFuenteFinanciamiento, inactivarFuenteFinanciamiento, listarFuentesFinanciamiento, obtenerFuenteFinanciamiento } from '../services/fuente-financiamiento'
const rows = ref<FuenteFinanciamiento[]>([]), search = ref(''), page = ref(1), lastPage = ref(1), total = ref(0), loading = ref(false), error = ref(''), success = ref(''), showForm = ref(false), editing = ref<number | null>(null)
const form = reactive<FuenteFinanciamientoPayload>({ nombre: '', descripcion: '', activo: true })
const message = (e: unknown) => e instanceof Error ? e.message : 'No se pudo completar la operación.'
async function load(next = 1) { loading.value = true; error.value = ''; try { const r = await listarFuentesFinanciamiento(search.value, next); rows.value = r.data; page.value = r.current_page; lastPage.value = r.last_page; total.value = r.total } catch (e) { error.value = message(e) } finally { loading.value = false } }
function create() { editing.value = null; Object.assign(form, { nombre: '', descripcion: '', activo: true }); showForm.value = true }
async function edit(item: FuenteFinanciamiento) { loading.value = true; try { const x = await obtenerFuenteFinanciamiento(item.id); editing.value = x.id; Object.assign(form, { nombre: x.nombre, descripcion: x.descripcion, activo: Boolean(x.activo) }); showForm.value = true } catch (e) { error.value = message(e) } finally { loading.value = false } }
async function save() { loading.value = true; error.value = ''; try { await guardarFuenteFinanciamiento(editing.value, { ...form }); success.value = `Fuente de financiamiento ${editing.value ? 'actualizada' : 'registrada'} correctamente.`; showForm.value = false; await load(page.value) } catch (e) { error.value = message(e) } finally { loading.value = false } }
async function deactivate(item: FuenteFinanciamiento) { if (!confirm(`¿Inactivar la fuente ${item.nombre}?`)) return; loading.value = true; try { await inactivarFuenteFinanciamiento(item.id); success.value = 'Fuente de financiamiento inactivada correctamente.'; await load(page.value) } catch (e) { error.value = message(e) } finally { loading.value = false } }
function clear() { search.value = ''; load(1) }
onMounted(() => load())
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / Administración / Finanzas / Fuentes de financiamiento</nav><header class="hero"><div class="mark">FF</div><div><small>MIA · FINANZAS · MAESTROS</small><h1>Fuentes de financiamiento</h1><p>Catálogo de recursos que financian las operaciones de tesorería.</p></div><strong>{{total}} registros</strong><button @click="create">+ Nueva fuente</button></header><p v-if="error" class="flash badmsg">{{error}}</p><p v-if="success" class="flash okmsg">{{success}}</p><form class="filters" @submit.prevent="load(1)"><input v-model.trim="search" placeholder="Buscar por código o descripción"><button>Buscar</button><button type="button" class="soft" @click="clear">Limpiar</button></form><section class="card"><div v-if="loading" class="empty">Procesando…</div><div v-else-if="!rows.length" class="empty">No se encontraron fuentes de financiamiento.</div><div v-else class="grid"><article v-for="item in rows" :key="item.id" :class="{inactive:!item.activo}"><header><b>{{item.nombre}}</b><span :class="item.activo?'good':'bad'">{{item.activo?'ACTIVA':'INACTIVA'}}</span></header><p>{{item.descripcion}}</p><footer><button class="edit" @click="edit(item)">Editar</button><button v-if="item.activo" class="danger" @click="deactivate(item)">Inactivar</button></footer></article></div><footer v-if="lastPage>1" class="pager"><button :disabled="page<=1" @click="load(page-1)">Anterior</button><span>{{page}} / {{lastPage}}</span><button :disabled="page>=lastPage" @click="load(page+1)">Siguiente</button></footer></section><div v-if="showForm" class="backdrop" @mousedown.self="showForm=false"><form class="dialog" @submit.prevent="save"><header><div><small>{{editing?'EDICIÓN':'NUEVO REGISTRO'}}</small><h2>{{editing?'Editar':'Registrar'}} fuente de financiamiento</h2></div><button type="button" @click="showForm=false">×</button></header><label>Código<input v-model.trim="form.nombre" maxlength="4" required placeholder="Máximo 4 caracteres"></label><label>Descripción<input v-model.trim="form.descripcion" maxlength="100" required></label><label class="check"><input v-model="form.activo" type="checkbox"> Fuente activa</label><footer><button type="button" class="soft" @click="showForm=false">Cancelar</button><button :disabled="loading">Guardar</button></footer></form></div></div></template>
<style scoped>
.page{--a:#176d78;color:#344750}nav{margin-bottom:15px;color:#91a0a5;font-size:.68rem}nav a{color:var(--a)}.hero{display:flex;align-items:center;gap:14px;padding:20px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:50px;height:50px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero>div:nth-child(2){flex:1}.hero small,.dialog small{color:var(--a);font-size:.49rem;font-weight:800}.hero h1{margin:3px 0;font-size:1.3rem}.hero p{margin:0;color:#7c8b91;font-size:.65rem}.hero strong{font-size:.55rem}button{padding:8px 11px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.5rem;cursor:pointer}.soft{color:#607078;background:#edf2f3}.flash{padding:10px;border-radius:6px;font-size:.55rem}.badmsg{color:#9b3d48;background:#fdebee}.okmsg{color:#236c50;background:#e8f7ee}.filters{margin-top:11px;padding:13px;display:grid;grid-template-columns:1fr auto auto;gap:7px;background:#fff}.filters input,.dialog input{box-sizing:border-box;width:100%;padding:9px;border:1px solid #d5dfe2;border-radius:6px;background:#fff;font-size:.52rem}.card{margin-top:11px;background:#fff}.grid{padding:13px;display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.grid article{display:flex;flex-direction:column;min-height:115px;padding:14px;border:1px solid #dce5e7;border-top:4px solid var(--a);border-radius:8px}.grid article.inactive{opacity:.7;border-top-color:#99a5aa}.grid article header{display:flex;justify-content:space-between}.grid article header>b{font-size:.72rem}.grid article p{flex:1;color:#6f7f85;font-size:.52rem}.grid footer{display:flex;gap:5px}.good,.bad{padding:4px 8px;border-radius:10px;font-size:.42rem;font-weight:800}.good{color:#267153;background:#e5f7ec}.bad{color:#9d414a;background:#fdebed}.edit{background:#c98a24}.danger{background:#b74b54}.empty{padding:50px;text-align:center}.pager{padding:12px;display:flex;justify-content:center;align-items:center;gap:8px;font-size:.5rem}.backdrop{position:fixed;z-index:100;inset:0;padding:20px;display:grid;place-items:center;background:#172b3d88}.dialog{width:min(500px,100%);padding:20px;box-sizing:border-box;border-radius:12px;background:#fff}.dialog>header{display:flex}.dialog>header div{flex:1}.dialog h2{margin:3px 0 15px}.dialog>header button{color:#66757b;background:none;font-size:1.2rem}.dialog label{display:grid;gap:5px;margin:10px 0;font-size:.52rem;font-weight:700}.dialog .check{display:flex;align-items:center}.dialog .check input{width:auto}.dialog footer{display:flex;justify-content:center;gap:8px;margin-top:15px}@media(max-width:950px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.filters,.grid{grid-template-columns:1fr}.hero{flex-wrap:wrap}.mark{display:none}}
</style>
