<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import type { ModalidadPago, ModalidadPagoPayload } from '../interfaces/modalidad-pago.interface'
import { desactivarModalidadPago, guardarModalidadPago, listarModalidadesPago, obtenerModalidadPago } from '../services/modalidad-pago'
const rows = ref<ModalidadPago[]>([]), search = ref(''), page = ref(1), lastPage = ref(1), total = ref(0), loading = ref(false), error = ref(''), success = ref(''), showForm = ref(false), editing = ref<number | null>(null)
const form = reactive<ModalidadPagoPayload>({ detalle: '', activo: true })
const message = (e: unknown) => e instanceof Error ? e.message : 'No se pudo completar la operación.'
async function load(next = 1) { loading.value = true; error.value = ''; try { const r = await listarModalidadesPago(search.value, next); rows.value = r.data; page.value = r.current_page; lastPage.value = r.last_page; total.value = r.total } catch (e) { error.value = message(e) } finally { loading.value = false } }
function create() { editing.value = null; Object.assign(form, { detalle: '', activo: true }); showForm.value = true }
async function edit(item: ModalidadPago) { loading.value = true; try { const x = await obtenerModalidadPago(item.id); editing.value = x.id; Object.assign(form, { detalle: x.detalle, activo: Boolean(x.activo) }); showForm.value = true } catch (e) { error.value = message(e) } finally { loading.value = false } }
async function save() { loading.value = true; error.value = ''; try { await guardarModalidadPago(editing.value, { ...form }); success.value = `Modalidad de pago ${editing.value ? 'actualizada' : 'registrada'} correctamente.`; showForm.value = false; await load(page.value) } catch (e) { error.value = message(e) } finally { loading.value = false } }
async function deactivate(item: ModalidadPago) { if (!confirm(`¿Desactivar la modalidad ${item.detalle}?`)) return; loading.value = true; try { await desactivarModalidadPago(item.id); success.value = 'Modalidad de pago desactivada correctamente.'; await load(page.value) } catch (e) { error.value = message(e) } finally { loading.value = false } }
function clear() { search.value = ''; load(1) }
onMounted(() => load())
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / Administración / Finanzas / Modalidades de pago</nav><header class="hero"><div class="mark">MP</div><div><small>MIA · FINANZAS · MAESTROS</small><h1>Modalidades de pago</h1><p>Catálogo de formas utilizadas para efectuar operaciones y pagos financieros.</p></div><strong>{{total}} registros</strong><button @click="create">+ Nueva modalidad</button></header><p v-if="error" class="flash badmsg">{{error}}</p><p v-if="success" class="flash okmsg">{{success}}</p><form class="filters" @submit.prevent="load(1)"><input v-model.trim="search" placeholder="Buscar por identificador o detalle"><button>Buscar</button><button type="button" class="soft" @click="clear">Limpiar</button></form><section class="card"><div v-if="loading" class="empty">Procesando…</div><div v-else-if="!rows.length" class="empty">No se encontraron modalidades de pago.</div><div v-else class="grid"><article v-for="item in rows" :key="item.id" :class="{inactive:!item.activo}"><header><b>#{{item.id}}</b><span :class="item.activo?'good':'bad'">{{item.activo?'ACTIVA':'INACTIVA'}}</span></header><h2>{{item.detalle}}</h2><footer><button class="edit" @click="edit(item)">Editar</button><button v-if="item.activo" class="danger" @click="deactivate(item)">Desactivar</button></footer></article></div><footer v-if="lastPage>1" class="pager"><button :disabled="page<=1" @click="load(page-1)">Anterior</button><span>{{page}} / {{lastPage}}</span><button :disabled="page>=lastPage" @click="load(page+1)">Siguiente</button></footer></section><div v-if="showForm" class="backdrop" @mousedown.self="showForm=false"><form class="dialog" @submit.prevent="save"><header><div><small>{{editing?'EDICIÓN':'NUEVO REGISTRO'}}</small><h2>{{editing?'Editar':'Registrar'}} modalidad de pago</h2></div><button type="button" @click="showForm=false">×</button></header><label>Detalle<input v-model.trim="form.detalle" maxlength="150" required placeholder="Nombre de la modalidad"></label><label class="check"><input v-model="form.activo" type="checkbox"> Modalidad activa</label><footer><button type="button" class="soft" @click="showForm=false">Cancelar</button><button :disabled="loading">Guardar</button></footer></form></div></div></template>
<style scoped>
.page{--a:#176d78;color:#344750}nav{margin-bottom:15px;color:#91a0a5;font-size:.68rem}nav a{color:var(--a)}.hero{display:flex;align-items:center;gap:14px;padding:20px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:50px;height:50px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero>div:nth-child(2){flex:1}.hero small,.dialog small{color:var(--a);font-size:.49rem;font-weight:800}.hero h1{margin:3px 0;font-size:1.3rem}.hero p{margin:0;color:#7c8b91;font-size:.65rem}.hero strong{font-size:.55rem}button{padding:8px 11px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.5rem;cursor:pointer}.soft{color:#607078;background:#edf2f3}.flash{padding:10px;border-radius:6px;font-size:.55rem}.badmsg{color:#9b3d48;background:#fdebee}.okmsg{color:#236c50;background:#e8f7ee}.filters{margin-top:11px;padding:13px;display:grid;grid-template-columns:1fr auto auto;gap:7px;background:#fff}.filters input,.dialog input{box-sizing:border-box;width:100%;padding:9px;border:1px solid #d5dfe2;border-radius:6px;background:#fff;font-size:.52rem}.card{margin-top:11px;background:#fff}.grid{padding:13px;display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.grid article{display:flex;flex-direction:column;min-height:105px;padding:14px;border:1px solid #dce5e7;border-top:4px solid var(--a);border-radius:8px}.grid article.inactive{opacity:.7;border-top-color:#99a5aa}.grid article header{display:flex;justify-content:space-between}.grid article header>b{color:var(--a);font-size:.55rem}.grid h2{flex:1;margin:17px 0;font-size:.68rem}.grid footer{display:flex;gap:5px}.good,.bad{padding:4px 8px;border-radius:10px;font-size:.42rem;font-weight:800}.good{color:#267153;background:#e5f7ec}.bad{color:#9d414a;background:#fdebed}.edit{background:#c98a24}.danger{background:#b74b54}.empty{padding:50px;text-align:center}.pager{padding:12px;display:flex;justify-content:center;align-items:center;gap:8px;font-size:.5rem}.backdrop{position:fixed;z-index:100;inset:0;padding:20px;display:grid;place-items:center;background:#172b3d88}.dialog{width:min(500px,100%);padding:20px;box-sizing:border-box;border-radius:12px;background:#fff}.dialog>header{display:flex}.dialog>header div{flex:1}.dialog h2{margin:3px 0 15px}.dialog>header button{color:#66757b;background:none;font-size:1.2rem}.dialog label{display:grid;gap:5px;margin:10px 0;font-size:.52rem;font-weight:700}.dialog .check{display:flex;align-items:center}.dialog .check input{width:auto}.dialog footer{display:flex;justify-content:center;gap:8px;margin-top:15px}@media(max-width:950px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.filters,.grid{grid-template-columns:1fr}.hero{flex-wrap:wrap}.mark{display:none}}
</style>
