<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import type { ReporteFila, ReporteFinancieroClave, ReporteFinancieroFiltros, ReporteFinancieroOpciones } from '../interfaces/reporte-financiero.interface'
import { descargarReporteFinanciero, obtenerOpcionesReporteFinanciero, previsualizarReporteFinanciero } from '../services/reporte-financiero'
type Column={key:string;label:string;number?:boolean}
const definitions:Record<ReporteFinancieroClave,{title:string;description:string;columns:Column[];amounts:string[]}>= {
 'comprobantes-tesoreria':{title:'Comprobantes de tesorería',description:'Movimientos, documentos, cargos y abonos por tipo de comprobante.',columns:[{key:'tipo',label:'Tipo'},{key:'comprobante',label:'Comprobante'},{key:'fecha',label:'Fecha'},{key:'documento',label:'Documento'},{key:'glosa',label:'Glosa'},{key:'cargos',label:'Cargos',number:true},{key:'abonos',label:'Abonos',number:true}],amounts:['cargos','abonos']},
 'estado-cuentas-bancarias':{title:'Estado de cuentas bancarias',description:'Saldos bancarios agrupados por concepto y cuenta contable.',columns:[{key:'concepto',label:'Concepto'},{key:'cuenta_contable',label:'Cuenta contable'},{key:'numero_cuenta_corriente',label:'N° Cta. Cte.'},{key:'saldo_anterior',label:'Saldo anterior',number:true},{key:'ingresos',label:'Ingresos',number:true},{key:'egresos',label:'Egresos',number:true},{key:'saldo',label:'Saldo',number:true}],amounts:['saldo_anterior','ingresos','egresos','saldo']},
 'libro-caja-banco':{title:'Libro caja y bancos',description:'Movimientos y saldos de las cuentas de caja y bancos.',columns:[{key:'cuenta',label:'Cuenta'},{key:'fecha',label:'Fecha'},{key:'concepto',label:'Concepto'},{key:'paguese_a',label:'Páguese a'},{key:'comprobante',label:'N° Comp.'},{key:'documento',label:'Doc. ref.'},{key:'cuenta_asociada',label:'Cuenta asociada'},{key:'debe',label:'Debe',number:true},{key:'haber',label:'Haber',number:true},{key:'saldo',label:'Saldo',number:true}],amounts:['debe','haber']},
 'estado-flujo-caja':{title:'Estado de flujo de caja',description:'Flujo de efectivo entre fechas, clasificado por actividad y concepto.',columns:[{key:'actividad',label:'Actividad'},{key:'codigo',label:'Código'},{key:'concepto',label:'Concepto'},{key:'importe',label:'Importe',number:true}],amounts:['importe']},
 'libro-mayor-auxiliar':{title:'Libro mayor auxiliar',description:'Movimientos contables consolidados por periodo y rango de cuentas.',columns:[{key:'cuenta',label:'Cuenta'},{key:'fecha',label:'Fecha'},{key:'comprobante',label:'Comprobante'},{key:'documento',label:'Documento'},{key:'glosa',label:'Glosa'},{key:'debe',label:'Debe',number:true},{key:'haber',label:'Haber',number:true},{key:'saldo',label:'Saldo',number:true}],amounts:['debe','haber']},
 'resumen-cuentas':{title:'Resumen de cuentas',description:'Saldos anteriores y movimientos mensuales por cuenta contable.',columns:[{key:'cuenta',label:'Cuenta'},{key:'descripcion',label:'Descripción'},{key:'saldo_anterior',label:'Saldo anterior',number:true},{key:'debe',label:'Debe',number:true},{key:'haber',label:'Haber',number:true},{key:'saldo_final',label:'Saldo final',number:true}],amounts:['saldo_anterior','debe','haber','saldo_final']}
}
const route=useRoute(),key=computed(()=>route.meta.reportKey as ReporteFinancieroClave),definition=computed(()=>definitions[key.value]),options=ref<ReporteFinancieroOpciones>({}),rows=ref<ReporteFila[]>([]),loading=ref(false),downloading=ref(''),error=ref(''),generated=ref(false)
const today=new Date(),firstDay=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-01`,currentDay=today.toISOString().slice(0,10)
const filters=reactive<ReporteFinancieroFiltros>({anio:'',mes:'',cuenta_desde:'',cuenta_hasta:'',fecha_inicio:firstDay,fecha_fin:currentDay,tipo_comprobante_id:'',orden:'numero'})
const usesDates=computed(()=>key.value==='comprobantes-tesoreria'||key.value==='estado-flujo-caja'),usesAccounts=computed(()=>key.value==='libro-caja-banco'||key.value==='resumen-cuentas'||key.value==='libro-mayor-auxiliar')
const money=(v:unknown)=>new Intl.NumberFormat('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v)||0),message=(e:unknown)=>e instanceof Error?e.message:'No se pudo completar la operación.'
const totals=computed(()=>Object.fromEntries(definition.value.amounts.map(k=>[k,rows.value.reduce((sum,x)=>sum+(Number(x[k])||0),0)])))
function normalize(value:unknown):ReporteFila[]{const data=(value&&typeof value==='object'&&'data'in value?(value as {data:unknown}).data:value) as any;if(key.value==='comprobantes-tesoreria')return (data?.tipos??[]).flatMap((t:any)=>(t.comprobantes??[]).map((x:any)=>({tipo:t.tipo_comprobante,comprobante:x.numero_comprobante_formato,fecha:x.fecha_comprobante,documento:`${x.tipo_documento??''} ${x.numero_documento??''}`.trim(),glosa:x.activo?x.glosa:'ANULADO',cargos:x.total_cargos,abonos:x.total_abonos})));if(key.value==='estado-flujo-caja')return (Array.isArray(data)?data:[]).map((x:any)=>({actividad:x.actividad,codigo:x.codigo,concepto:x.nombre??x.concepto,importe:x.importe}));if(key.value==='libro-mayor-auxiliar')return (Array.isArray(data)?data:[]).flatMap((g:any)=>(g.movimientos??g.detalles??[]).map((x:any)=>({cuenta:g.cta_contable??g.cuenta,fecha:x.fecha??x.fecha_comprobante,comprobante:x.numero_comprobante??x.comprobante,documento:x.numero_documento??x.documento,glosa:x.glosa??x.concepto,debe:x.debe,haber:x.haber,saldo:x.saldo})));if(key.value==='estado-cuentas-bancarias')return (Array.isArray(data)?data:[]).flatMap((g:any)=>(g.items??[]).map((x:any)=>({...x,concepto:g.concepto})));if(key.value==='libro-caja-banco')return (Array.isArray(data)?data:[]).flatMap((g:any)=>(g.movimientos??[]).map((x:any)=>({cuenta:g.cta_contable,fecha:x.fecha_comprobante,concepto:x.concepto,paguese_a:x.paguese_a,comprobante:x.numero_comprobante,documento:x.documento_referencia,cuenta_asociada:`${x.cuenta_asociada??''} ${x.cuenta_asociada_descripcion??''}`.trim(),debe:x.debe,haber:x.haber,saldo:x.saldo})));return (Array.isArray(data)?data:[]).map((x:any)=>({cuenta:x.cta_contable,descripcion:x.descripcion,saldo_anterior:x.saldo_anterior,debe:x.debe_mes,haber:x.haber_mes,saldo_final:x.saldo_final}))}
function validate(){if(usesDates.value){if(!filters.fecha_inicio||!filters.fecha_fin)return 'Seleccione el rango de fechas.';if(filters.fecha_inicio>filters.fecha_fin)return 'La fecha inicial no puede ser mayor que la fecha final.'}else if(!filters.anio||!filters.mes)return 'Seleccione el año y mes.';if(usesAccounts.value){if(!filters.cuenta_desde||!filters.cuenta_hasta)return 'Seleccione el rango de cuentas.';const accounts=options.value.cuentas??[],a=accounts.findIndex(x=>String(x.id)===filters.cuenta_desde),b=accounts.findIndex(x=>String(x.id)===filters.cuenta_hasta);if(a>b)return 'La cuenta desde no puede ser mayor que la cuenta hasta.'}return ''}
async function loadOptions(){loading.value=true;try{options.value=await obtenerOpcionesReporteFinanciero(key.value);const active=options.value.periodo_activo??options.value.periodos?.find(x=>x.estado);filters.anio=String(active?.anio??options.value.periodos?.[0]?.anio??'');filters.mes=String(options.value.meses?.[Math.min(today.getMonth(),(options.value.meses?.length??1)-1)]?.mes??today.getMonth()+1);filters.cuenta_desde=String(options.value.cuentas?.[0]?.id??'');filters.cuenta_hasta=String(options.value.cuentas?.at(-1)?.id??'')}catch(e){error.value=message(e)}finally{loading.value=false}}
async function preview(){const issue=validate();if(issue)return error.value=issue;loading.value=true;error.value='';try{const r=await previsualizarReporteFinanciero(key.value,filters);rows.value=normalize(r);generated.value=true}catch(e){error.value=message(e)}finally{loading.value=false}}
async function download(format:'pdf'|'excel'){const issue=validate();if(issue)return error.value=issue;downloading.value=format;error.value='';try{await descargarReporteFinanciero(key.value,format,filters)}catch(e){error.value=message(e)}finally{downloading.value=''}}
onMounted(loadOptions)
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / Administración / Finanzas / {{definition.title}}</nav><header class="hero"><div class="mark">RF</div><div><small>MIA · FINANZAS · REPORTES</small><h1>{{definition.title}}</h1><p>{{definition.description}}</p></div></header><p v-if="error" class="flash">{{error}}</p><section class="filters"><template v-if="usesDates"><label>Fecha inicio<input v-model="filters.fecha_inicio" type="date"></label><label>Fecha fin<input v-model="filters.fecha_fin" type="date"></label><label>Tipo de comprobante<select v-model="filters.tipo_comprobante_id"><option value="">Todos</option><option v-for="x in options.tipos_comprobante" :key="x.id" :value="x.id">{{x.codigo?`${x.codigo} · `:''}}{{x.detalle}}</option></select></label></template><template v-else><label>Año<select v-model="filters.anio"><option v-for="x in options.periodos" :key="x.anio" :value="x.anio">{{x.anio}}</option></select></label><label>Mes<select v-model="filters.mes"><option v-for="x in options.meses" :key="x.mes" :value="x.mes">{{x.nombre??x.mes}}</option></select></label><template v-if="usesAccounts"><label>Cuenta desde<select v-model="filters.cuenta_desde"><option v-for="x in options.cuentas" :key="x.id" :value="x.id">{{x.cta_contable}} · {{x.descripcion}}</option></select></label><label>Cuenta hasta<select v-model="filters.cuenta_hasta"><option v-for="x in options.cuentas" :key="x.id" :value="x.id">{{x.cta_contable}} · {{x.descripcion}}</option></select></label></template></template><div class="buttons"><button :disabled="loading" @click="preview">{{loading?'Generando…':'Generar'}}</button><button class="pdf" :disabled="!!downloading" @click="download('pdf')">{{downloading==='pdf'?'Descargando…':'PDF'}}</button><button class="excel" :disabled="!!downloading" @click="download('excel')">{{downloading==='excel'?'Descargando…':'Excel'}}</button></div></section><section class="card"><div v-if="loading" class="empty">Procesando reporte…</div><div v-else-if="!generated" class="empty">Seleccione los filtros y presione Generar.</div><div v-else-if="!rows.length" class="empty">No se encontraron registros.</div><div v-else class="scroll"><table><thead><tr><th v-for="c in definition.columns" :key="c.key" :class="{number:c.number}">{{c.label}}</th></tr></thead><tbody><tr v-for="(row,i) in rows" :key="i"><td v-for="c in definition.columns" :key="c.key" :class="{number:c.number}">{{c.number?money(row[c.key]):(row[c.key]??'—')}}</td></tr></tbody><tfoot><tr><th v-for="(c,i) in definition.columns" :key="c.key" :class="{number:c.number}">{{i===0?'TOTAL':c.number&&definition.amounts.includes(c.key)?money(totals[c.key]):''}}</th></tr></tfoot></table></div></section></div></template>
<style scoped>.page{--a:#176d78;color:#344750}nav{margin-bottom:15px;color:#91a0a5;font-size:.68rem}nav a{color:var(--a)}.hero{display:flex;gap:14px;padding:20px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:50px;height:50px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero small{color:var(--a);font-size:.48rem;font-weight:800}.hero h1{margin:3px 0;font-size:1.3rem}.hero p{margin:0;color:#7c8b91;font-size:.65rem}.flash{padding:10px;color:#9b3d48;background:#fdebee}.filters{margin-top:12px;padding:14px;display:flex;align-items:end;gap:9px;flex-wrap:wrap;background:#fff}.filters label{min-width:150px;flex:1;display:grid;gap:5px;font-size:.5rem;font-weight:700}.filters input,.filters select{box-sizing:border-box;width:100%;padding:9px;border:1px solid #d5dfe2;border-radius:6px;background:#fff}.buttons{display:flex;gap:6px}button{padding:9px 13px;border:0;border-radius:6px;color:#fff;background:var(--a);cursor:pointer}.pdf{background:#b74b54}.excel{background:#27875f}.card{margin-top:12px;background:#fff}.empty{padding:50px;text-align:center}.scroll{overflow:auto}table{width:100%;min-width:950px;border-collapse:collapse;font-size:.49rem}th,td{padding:9px;border-bottom:1px solid #e3e9eb;text-align:left}thead th{color:#fff;background:#435d6c}tfoot th{background:#eaf1f2}.number{text-align:right}@media(max-width:650px){.filters{display:grid}.buttons{justify-content:flex-end}.mark{display:none}}</style>
