<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue'
import type {TipoFondoCajaChica,TipoFondoPayload} from '../interfaces/tipo-fondo-caja-chica.interface'
import {cambiarEstadoTipoFondo,guardarTipoFondo,listarTiposFondo,obtenerTipoFondo} from '../services/tipo-fondo-caja-chica'
const rows=ref<TipoFondoCajaChica[]>([]),fuentes=ref<{id:number;nombre:string;descripcion?:string}[]>([]),search=ref(''),page=ref(1),lastPage=ref(1),total=ref(0),loading=ref(false),error=ref(''),success=ref(''),modal=ref(false),editing=ref<number|null>(null)
const blank=():TipoFondoPayload=>({codigo:'',detalle:'',cuenta_contable_id:null,fuente_financiamiento_id:null,rendicion_fondo_fijo:false,rendicion_gasto_directo:false,rendicion_anticipos_viaticos:false,activo:true}),form=reactive<TipoFondoPayload>(blank()),msg=(e:unknown)=>e instanceof Error?e.message:'No se pudo completar la operación.'
async function load(next=1){loading.value=true;error.value='';try{const r=await listarTiposFondo(search.value,next);rows.value=r.data;fuentes.value=r.fuentes??fuentes.value;page.value=r.current_page;lastPage.value=r.last_page;total.value=r.total}catch(e){error.value=msg(e)}finally{loading.value=false}}
function create(){editing.value=null;Object.assign(form,blank());modal.value=true}
async function edit(row:TipoFondoCajaChica){try{const x=await obtenerTipoFondo(row.id);editing.value=x.id;Object.assign(form,{codigo:x.codigo,detalle:x.detalle,cuenta_contable_id:x.cuenta_contable_id,fuente_financiamiento_id:x.fuente_financiamiento_id,rendicion_fondo_fijo:Boolean(x.rendicion_fondo_fijo),rendicion_gasto_directo:Boolean(x.rendicion_gasto_directo),rendicion_anticipos_viaticos:Boolean(x.rendicion_anticipos_viaticos),activo:Boolean(x.activo)});modal.value=true}catch(e){error.value=msg(e)}}
async function save(){if(!form.codigo||!form.detalle)return error.value='Código y descripción son obligatorios.';loading.value=true;try{await guardarTipoFondo(editing.value,{...form});modal.value=false;success.value='Tipo de fondo guardado correctamente.';await load(page.value)}catch(e){error.value=msg(e)}finally{loading.value=false}}
async function toggle(x:TipoFondoCajaChica){if(!confirm(`¿${x.activo?'Inactivar':'Activar'} ${x.codigo}?`))return;try{await cambiarEstadoTipoFondo(x.id);await load(page.value)}catch(e){error.value=msg(e)}}
onMounted(()=>load())
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / Administración / Finanzas / Tipos de fondo</nav><header class="hero"><b>TF</b><div><small>MIA · FINANZAS · CAJA CHICA</small><h1>Tipos de fondo de caja chica</h1><p>Fondos, cuentas y modalidades de rendición permitidas.</p></div><strong>{{total}} registros</strong><button @click="create">+ Nuevo fondo</button></header><p v-if="error" class="flash bad">{{error}}</p><p v-if="success" class="flash ok">{{success}}</p><form class="filters" @submit.prevent="load(1)"><input v-model="search" placeholder="Buscar por código o descripción"><button>Buscar</button></form><section class="card"><div v-if="loading" class="empty">Procesando…</div><div v-else class="grid"><article v-for="x in rows" :key="x.id" :class="{inactive:!x.activo}"><header><b>{{x.codigo}}</b><span>{{x.activo?'ACTIVO':'INACTIVO'}}</span></header><h3>{{x.detalle}}</h3><p>Cuenta: {{x.cuenta_contable?.cta_contable??'Sin asignar'}}<br>Fuente: {{x.fuente_financiamiento?.nombre??'Sin asignar'}}</p><div><i v-if="x.rendicion_fondo_fijo">Fondo fijo</i><i v-if="x.rendicion_gasto_directo">Gasto directo</i><i v-if="x.rendicion_anticipos_viaticos">Anticipos</i></div><footer><button class="edit" @click="edit(x)">Editar</button><button class="danger" @click="toggle(x)">{{x.activo?'Inactivar':'Activar'}}</button></footer></article></div><footer v-if="lastPage>1" class="pager"><button :disabled="page<=1" @click="load(page-1)">Anterior</button><span>{{page}} / {{lastPage}}</span><button :disabled="page>=lastPage" @click="load(page+1)">Siguiente</button></footer></section><div v-if="modal" class="backdrop" @mousedown.self="modal=false"><form class="dialog" @submit.prevent="save"><header><h2>{{editing?'Editar':'Registrar'}} tipo de fondo</h2><button type="button" @click="modal=false">×</button></header><label>Código *<input v-model.trim="form.codigo" maxlength="10" required></label><label>Descripción *<input v-model.trim="form.detalle" maxlength="150" required></label><label>Cuenta contable ID<input v-model.number="form.cuenta_contable_id" type="number" min="1" placeholder="Opcional"></label><label>Fuente de financiamiento<select v-model.number="form.fuente_financiamiento_id"><option :value="null">Sin asignar</option><option v-for="x in fuentes" :key="x.id" :value="x.id">{{x.nombre}} · {{x.descripcion}}</option></select></label><fieldset><legend>Rendiciones permitidas</legend><label><input v-model="form.rendicion_fondo_fijo" type="checkbox"> Fondo fijo</label><label><input v-model="form.rendicion_gasto_directo" type="checkbox"> Gasto directo</label><label><input v-model="form.rendicion_anticipos_viaticos" type="checkbox"> Anticipos y viáticos</label></fieldset><footer><button type="button" class="soft" @click="modal=false">Cancelar</button><button>Guardar</button></footer></form></div></div></template>
<style scoped>.page{--a:#176d78;color:#344750}nav{margin-bottom:15px;font-size:.68rem;color:#91a0a5}.hero{display:flex;align-items:center;gap:14px;padding:20px;border-left:5px solid var(--a);background:#fff}.hero>b{padding:16px;border-radius:10px;color:#fff;background:var(--a)}.hero>div{flex:1}.hero small{color:var(--a);font-size:.5rem}.hero h1{margin:3px 0;font-size:1.3rem}.hero p{margin:0;font-size:.65rem}button{padding:8px 11px;border:0;border-radius:6px;color:#fff;background:var(--a)}.flash{padding:10px}.bad{background:#fdebee;color:#9b3d48}.ok{background:#e8f7ee;color:#236c50}.filters{margin-top:11px;padding:13px;display:grid;grid-template-columns:1fr auto;gap:8px;background:#fff}input,select{box-sizing:border-box;width:100%;padding:9px;border:1px solid #d5dfe2;border-radius:6px}.card{margin-top:11px;background:#fff}.grid{padding:13px;display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.grid article{padding:14px;border:1px solid #dce5e7;border-top:4px solid var(--a)}.inactive{opacity:.6}.grid article header,.grid article footer,.dialog header{display:flex;justify-content:space-between}.grid p{font-size:.52rem}.grid i{display:inline-block;margin:2px;padding:4px;background:#e8f2f3;font-size:.44rem}.edit{background:#c98a24}.danger{background:#b74b54}.empty{padding:50px;text-align:center}.pager{padding:12px;display:flex;justify-content:center;gap:8px}.backdrop{position:fixed;z-index:100;inset:0;display:grid;place-items:center;background:#172b3d88}.dialog{width:min(560px,90%);padding:20px;background:#fff}.dialog label{display:grid;gap:5px;margin:10px 0}.dialog fieldset label{display:inline-flex}.dialog fieldset input{width:auto}.dialog>footer{display:flex;justify-content:center;gap:8px}.soft{color:#607078;background:#edf2f3}@media(max-width:700px){.grid{grid-template-columns:1fr}.hero{flex-wrap:wrap}}</style>