<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue'
import type { TipoCartaFianza,TipoCartaFianzaPayload } from '../interfaces/tipo-carta-fianza.interface'
import { cambiarEstadoTipoCartaFianza,guardarTipoCartaFianza,listarTiposCartaFianza,obtenerTipoCartaFianza } from '../services/tipo-carta-fianza'
const rows=ref<TipoCartaFianza[]>([]),texto=ref(''),estado=ref(''),page=ref(1),lastPage=ref(1),total=ref(0),loading=ref(false),error=ref(''),success=ref(''),showForm=ref(false),editing=ref<number|null>(null)
const form=reactive<TipoCartaFianzaPayload>({codigo:'',nombre:'',descripcion:''})
const message=(e:unknown)=>e instanceof Error?e.message:'No se pudo completar la operación.'
async function load(next=1){loading.value=true;error.value='';try{const r=await listarTiposCartaFianza(texto.value,estado.value,next);rows.value=r.data;page.value=r.current_page;lastPage.value=r.last_page;total.value=r.total}catch(e){error.value=message(e)}finally{loading.value=false}}
function create(){editing.value=null;Object.assign(form,{codigo:'',nombre:'',descripcion:''});showForm.value=true}
async function edit(item:TipoCartaFianza){loading.value=true;try{const x=await obtenerTipoCartaFianza(item.id);editing.value=x.id;Object.assign(form,{codigo:x.codigo,nombre:x.nombre,descripcion:x.descripcion||''});showForm.value=true}catch(e){error.value=message(e)}finally{loading.value=false}}
async function save(){loading.value=true;error.value='';try{await guardarTipoCartaFianza(editing.value,{...form});success.value=`Tipo de carta fianza ${editing.value?'actualizado':'registrado'} correctamente.`;showForm.value=false;await load(page.value)}catch(e){error.value=message(e)}finally{loading.value=false}}
async function toggle(item:TipoCartaFianza){const action=item.activo?'inactivar':'activar';if(!confirm(`¿Desea ${action} ${item.nombre}?`))return;loading.value=true;try{await cambiarEstadoTipoCartaFianza(item.id);success.value=`Registro ${action==='activar'?'activado':'inactivado'} correctamente.`;await load(page.value)}catch(e){error.value=message(e)}finally{loading.value=false}}
function clear(){texto.value='';estado.value='';load(1)}
onMounted(()=>load())
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / Administración / Finanzas / Tipos de Carta Fianza</nav><header class="hero"><div class="mark">TF</div><div><small>MIA · FINANZAS · MAESTROS</small><h1>Tipos de Carta Fianza</h1><p>Catálogo de tipos utilizados en el registro y gestión de garantías.</p></div><strong>{{total}} registros</strong><button @click="create">+ Nuevo tipo</button></header><p v-if="error" class="flash badmsg">{{error}}</p><p v-if="success" class="flash okmsg">{{success}}</p><form class="filters" @submit.prevent="load(1)"><input v-model.trim="texto" placeholder="Buscar por código, nombre o descripción"><select v-model="estado"><option value="">Todos los estados</option><option value="1">Activos</option><option value="0">Inactivos</option></select><button>Buscar</button><button type="button" class="soft" @click="clear">Limpiar</button></form><section class="card"><div v-if="loading" class="empty">Procesando…</div><div v-else-if="!rows.length" class="empty">No se encontraron tipos de carta fianza.</div><div v-else class="scroll"><table><thead><tr><th>#</th><th>Código</th><th>Nombre</th><th>Descripción</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><tr v-for="(item,index) in rows" :key="item.id"><td>{{(page-1)*15+index+1}}</td><td><b>{{item.codigo}}</b></td><td>{{item.nombre}}</td><td>{{item.descripcion||'-'}}</td><td><span :class="item.activo?'good':'bad'">{{item.activo?'ACTIVO':'INACTIVO'}}</span></td><td class="actions"><button class="edit" @click="edit(item)">Editar</button><button :class="item.activo?'danger':'activate'" @click="toggle(item)">{{item.activo?'Inactivar':'Activar'}}</button></td></tr></tbody></table></div><footer v-if="lastPage>1"><button :disabled="page<=1" @click="load(page-1)">Anterior</button><span>{{page}} / {{lastPage}}</span><button :disabled="page>=lastPage" @click="load(page+1)">Siguiente</button></footer></section><div v-if="showForm" class="backdrop" @mousedown.self="showForm=false"><form class="dialog" @submit.prevent="save"><header><div><small>{{editing?'EDICIÓN':'NUEVO REGISTRO'}}</small><h2>{{editing?'Editar':'Registrar'}} tipo de carta fianza</h2></div><button type="button" @click="showForm=false">×</button></header><label>Código<input v-model.trim="form.codigo" maxlength="10" required placeholder="Ej. FIEL"></label><label>Nombre<input v-model.trim="form.nombre" maxlength="100" required placeholder="Ej. Fiel cumplimiento"></label><label>Descripción<textarea v-model.trim="form.descripcion" maxlength="255" rows="4" placeholder="Descripción opcional"></textarea></label><footer><button type="button" class="soft" @click="showForm=false">Cancelar</button><button :disabled="loading">Guardar</button></footer></form></div></div></template>
<style scoped>
.page{--a:#176d78;color:#344750}nav{margin-bottom:15px;color:#91a0a5;font-size:.68rem}nav a{color:var(--a)}.hero{display:flex;align-items:center;gap:14px;padding:20px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:50px;height:50px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero>div:nth-child(2){flex:1}.hero small,.dialog small{color:var(--a);font-size:.5rem;font-weight:800}.hero h1{margin:3px 0;font-size:1.3rem}.hero p{margin:0;color:#7c8b91;font-size:.65rem}.hero strong{font-size:.55rem}button{padding:8px 11px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.5rem;cursor:pointer}.soft{color:#607078;background:#edf2f3}.flash{padding:10px;border-radius:6px;font-size:.55rem}.badmsg{color:#9b3d48;background:#fdebee}.okmsg{color:#236c50;background:#e8f7ee}.filters{margin-top:11px;padding:13px;display:grid;grid-template-columns:2fr 1fr auto auto;gap:7px;background:#fff}.filters input,.filters select,.dialog input,.dialog textarea{box-sizing:border-box;width:100%;padding:9px;border:1px solid #d5dfe2;border-radius:6px;background:#fff;font-size:.52rem}.card{margin-top:11px;background:#fff}.scroll{overflow:auto}table{width:100%;min-width:780px;border-collapse:collapse;font-size:.51rem}th,td{padding:10px;border-bottom:1px solid #e3e9eb;text-align:left}th{color:#fff;background:#435d6c}.good,.bad{display:inline-block;padding:4px 8px;border-radius:10px;font-size:.47rem;font-weight:800}.good{color:#267153;background:#e5f7ec}.bad{color:#9d414a;background:#fdebed}.actions{display:flex;gap:5px}.edit{background:#c98a24}.danger{background:#b74b54}.activate{background:#27875f}.empty{padding:45px;text-align:center}.card>footer,.dialog>footer{padding:12px;display:flex;justify-content:center;align-items:center;gap:8px}.backdrop{position:fixed;z-index:100;inset:0;padding:20px;display:grid;place-items:center;background:#172b3d88}.dialog{width:min(520px,100%);padding:20px;box-sizing:border-box;border-radius:12px;background:#fff}.dialog>header{display:flex}.dialog>header div{flex:1}.dialog h2{margin:3px 0 15px}.dialog>header button{color:#66757b;background:none;font-size:1.2rem}.dialog label{display:grid;gap:5px;margin:10px 0;color:#5d7078;font-size:.52rem;font-weight:700}.dialog textarea{resize:vertical}@media(max-width:650px){.filters{grid-template-columns:1fr}.hero{align-items:flex-start;flex-wrap:wrap}.hero .mark{display:none}}
</style>
