<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { listarAbastecimientos, registrarAccion } from '../services/abastecimientos'
import type { AbastecimientoProgramado } from '../interfaces/abastecimientos.interface'
const records=ref<AbastecimientoProgramado[]>([]),query=ref(''),loading=ref(false),processing=ref<number|null>(null),error=ref(''),success=ref(''),summary=reactive({total:0,dentro:0,vueltas:0,pendientes:0})
async function load(){loading.value=true;error.value='';try{const r=await listarAbastecimientos(query.value);records.value=r.data;Object.assign(summary,{total:r.total,dentro:r.dentro,vueltas:r.vueltas,pendientes:r.pendientes})}catch(e){error.value=message(e)}finally{loading.value=false}}
function limaParts(){const now=new Date();const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Lima',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(now);const value=(type:string)=>parts.find(p=>p.type===type)?.value??'';return{fecha:`${value('year')}-${value('month')}-${value('day')}`,hora:`${value('hour')}:${value('minute')}:${value('second')}`}}
async function act(item:AbastecimientoProgramado){const action:1|2=item.ultima_operacion===1?2:1;const label=action===1?'ingreso':'salida';if(!confirm(`¿Registrar ${label} de la cisterna ${item.placa}?`))return;processing.value=item.id_programacion_cisterna;error.value='';try{const time=limaParts();await registrarAccion({id_programacion_cisterna:item.id_programacion_cisterna,id_programacion:item.id_programacion,id_cisterna:item.id_cisterna,id_punto_abastecimiento:item.id_punto_abastecimiento,fecha:time.fecha,hora:time.hora,accion:action});success.value=`${label.charAt(0).toUpperCase()+label.slice(1)} registrado correctamente para ${item.placa}.`;await load()}catch(e){error.value=message(e)}finally{processing.value=null}}
function clear(){query.value='';load()}const formatDate=(date:string)=>new Date(`${date}T00:00:00`).toLocaleDateString('es-PE');const message=(e:unknown)=>e instanceof Error?e.message:'No se pudo completar la operación.'
onMounted(load)
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / Operaciones / Gestión de Cisternas / Abastecimientos</nav><header class="hero"><div class="mark">AB</div><div><small>DANA · GESTIÓN DE CISTERNAS</small><h1>Control de abastecimientos</h1><p>Registra el ingreso y salida de las unidades en los puntos de abastecimiento.</p></div><button @click="load">↻ Actualizar</button></header><p v-if="success" class="flash success">✓ {{success}}</p><p v-if="error" class="flash">{{error}}</p><section class="summary"><article><small>UNIDADES PROGRAMADAS</small><b>{{summary.total}}</b></article><article><small>EN ABASTECIMIENTO</small><b>{{summary.dentro}}</b></article><article><small>VUELTAS COMPLETADAS</small><b>{{summary.vueltas}}</b></article><article><small>PENDIENTES DE INGRESO</small><b>{{summary.pendientes}}</b></article></section><form class="filters" @submit.prevent="load"><label>Buscar cisterna<input v-model.trim="query" placeholder="Número de placa"></label><button>Buscar</button><button v-if="query" type="button" class="soft" @click="clear">Limpiar</button></form><div v-if="loading" class="empty">Consultando unidades programadas…</div><div v-else-if="!records.length" class="empty">No se encontraron cisternas programadas para ayer o el día de hoy.</div><section v-else class="cards"><article v-for="item in records" :key="item.id_programacion_cisterna" :class="{inside:item.ultima_operacion===1}"><header><div class="truck">▰</div><div><small>CISTERNA #{{item.id_cisterna}}</small><h2>{{item.placa}}</h2></div><span>{{item.ultima_operacion===1?'DENTRO DEL PUNTO':'FUERA DEL PUNTO'}}</span></header><div class="date"><small>FECHA PROGRAMADA</small><b>{{formatDate(item.fecha)}}</b></div><dl><div><dt>Programación</dt><dd>#{{item.id_programacion}}</dd></div><div><dt>Conductor</dt><dd>{{item.conductor||'—'}}</dd></div><div><dt>Punto de abastecimiento</dt><dd>{{item.punto_abastecimiento||'—'}}</dd></div><div><dt>Vueltas ejecutadas</dt><dd><strong>{{item.vueltas}}</strong><template v-if="item.vueltas_programadas!==undefined"> / {{item.vueltas_programadas}}</template></dd></div><div><dt>Última acción</dt><dd>{{item.ultima_accion||'Sin movimientos'}}</dd></div></dl><button :class="item.ultima_operacion===1?'exit':'enter'" :disabled="processing===item.id_programacion_cisterna" @click="act(item)">{{processing===item.id_programacion_cisterna?'Registrando…':item.ultima_operacion===1?'Registrar salida':'Registrar ingreso'}}</button></article></section></div></template>
<style scoped>
.page{--accent:#e38b2f;color:#35464e}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--accent);text-decoration:none}.hero{padding:20px 23px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--accent);border-radius:12px;background:#fff}.mark{width:48px;height:48px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--accent);font-size:.65rem;font-weight:800}.hero small,.summary small,.cards small{color:var(--accent);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.3rem}.hero p{margin:0;color:#7e8a90;font-size:.67rem}.hero button,.filters button{padding:9px 12px;border:0;border-radius:6px;color:#fff;background:var(--accent);font-size:.52rem}.hero>button{margin-left:auto}.flash{padding:9px;border-radius:7px;color:#a64046;background:#fff0f0;font-size:.6rem}.flash.success{color:#287052;background:#edf9f3}.summary{margin-top:10px;display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.summary article{padding:11px;display:grid;border-radius:8px;background:#fff}.summary b{font-size:.85rem}.filters{margin-top:8px;padding:12px;display:flex;align-items:end;gap:7px;border-radius:9px;background:#fff}.filters label{display:grid;flex:1;gap:4px;font-size:.47rem}.filters input{box-sizing:border-box;padding:8px;border:1px solid #d7dfe2;border-radius:6px;font:inherit;font-size:.5rem}.soft{color:#64727a!important;background:#edf1f3!important}.empty{margin-top:9px;padding:45px;text-align:center;border-radius:9px;background:#fff;font-size:.58rem}.cards{margin-top:9px;display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.cards article{padding:14px;border-top:4px solid #7d8c94;border-radius:9px;background:#fff}.cards article.inside{border-color:#3b9777}.cards header{display:flex;align-items:center;gap:8px}.truck{width:38px;height:38px;display:grid;place-items:center;border-radius:7px;color:#fff;background:#536d91}.cards h2{margin:2px 0;font-size:.78rem}.cards header>span{margin-left:auto;padding:4px 6px;border-radius:7px;color:#68767d;background:#edf1f3;font-size:.39rem}.cards .inside header>span{color:#287055;background:#e4f5ed}.date{margin:11px 0;padding:9px;display:flex;align-items:center;justify-content:space-between;border-radius:6px;background:#fff3db}.date b{color:#a66b15;font-size:.68rem}.cards dl{margin:0}.cards dl div{padding:6px 0;display:flex;justify-content:space-between;gap:10px;border-bottom:1px solid #e7ecee;font-size:.46rem}.cards dt{color:#7d898f}.cards dd{margin:0;max-width:65%;overflow-wrap:anywhere;text-align:right;font-weight:700}.cards dd strong{color:var(--accent);font-size:.65rem}.cards>article>button{width:100%;margin-top:11px;padding:9px;border:0;border-radius:6px;font-size:.5rem;font-weight:700}.enter{color:#fff;background:#3b9777}.exit{color:#7b510d;background:#ffd998}button:disabled{opacity:.45}@media(max-width:850px){.hero,.filters{flex-wrap:wrap}.hero>button{margin-left:0}.summary,.cards{grid-template-columns:1fr}.filters label{width:100%}}
</style>
