import { createRouter, createWebHistory } from 'vue-router'
import DashboardLayout from '@/layouts/DashboardLayout.vue'
import DashboardView from '@/views/DashboardView.vue'
import ModuleView from '@/views/ModuleView.vue'
import SectionView from '@/views/SectionView.vue'
import NotFoundView from '@/views/NotFoundView.vue'
import SeguimientoProcesoPage from '@/modules/enki/territorial/pages/SeguimientoProcesoPage.vue'
import { appModules } from '@/config/modules'

const optionPages = {
  'helpdesk-requerimientos-gestion': () => import('@/modules/helpdesk/requerimientos/pages/RequerimientosPage.vue'),
  'mat-expedientes-gestion': () => import('@/modules/mat/expedientes/pages/ExpedientesPage.vue'),
  'mat-pad-gestion': () => import('@/modules/mat/pad/pages/PadPage.vue'),
  'mat-pas-gestion': () => import('@/modules/mat/pas/pages/PasPage.vue'),
  'mat-convenios-gestion': () => import('@/modules/mat/convenios/pages/ConveniosPage.vue'),
  'mat-documentos-normativos-gestion': () => import('@/modules/mat/documentosNormativos/pages/DocumentosNormativosPage.vue'),
  'mia-logistica-pedidos': () => import('@/modules/mia/logistica/pages/PedidosPage.vue'),
  'mia-logistica-requerimientos-almacen': () => import('@/modules/mia/logistica/pages/RequerimientosAlmacenPage.vue'),
  'mia-logistica-evaluacion-tecnica': () => import('@/modules/mia/logistica/pages/EvaluacionTecnicaPage.vue'),
  'mia-logistica-procesos-compra': () => import('@/modules/mia/logistica/pages/ProcesosCompraPage.vue'),
  'mia-logistica-ordenes': () => import('@/modules/mia/logistica/pages/OrdenesPage.vue'),
  'mia-logistica-proveedores': () => import('@/modules/mia/logistica/pages/ProveedoresPage.vue'),
  'mia-logistica-evaluaciones-economicas': () => import('@/modules/mia/logistica/pages/EvaluacionesEconomicasPage.vue'),
  'mia-logistica-proformas': () => import('@/modules/mia/logistica/pages/ProformasPage.vue'),
  'mia-almacen-ingresos': () => import('@/modules/mia/almacen/pages/IngresosPage.vue'),
  'mia-almacen-salidas': () => import('@/modules/mia/almacen/pages/SalidasPage.vue'),
  'mia-almacen-stock': () => import('@/modules/mia/almacen/pages/StockPage.vue'),
  'mia-almacen-saldos': () => import('@/modules/mia/almacen/pages/SaldosPage.vue'),
  'mia-almacen-movimientos': () => import('@/modules/mia/almacen/pages/MovimientosPage.vue'),
  'mia-almacen-almacenes': () => import('@/modules/mia/almacen/pages/AlmacenesPage.vue'),
  'mia-almacen-tipos-transaccion': () => import('@/modules/mia/almacen/pages/TiposTransaccionPage.vue'),
  'mia-almacen-periodos': () => import('@/modules/mia/almacen/pages/PeriodosPage.vue'),
  'mia-almacen-estados': () => import('@/modules/mia/almacen/pages/EstadosPage.vue'),
  'mia-almacen-grupos-items': () => import('@/modules/mia/almacen/pages/GruposItemsPage.vue'),
  'mia-almacen-items': () => import('@/modules/mia/almacen/pages/ItemsPage.vue'),
  'mia-logistica-documentos-compra': () => import('@/modules/mia/almacen/pages/DocumentosCompraPage.vue'),
  'mia-presupuesto-formulaciones': () => import('@/modules/mia/presupuesto/pages/FormulacionesPage.vue'),
  'mia-recursos-productividad': () => import('@/modules/mia/recursos/pages/ProductividadPage.vue'),
  'mia-utilitarios-reporte-almacen': () => import('@/modules/mia/utilitarios/pages/ReporteAlmacenPage.vue'),
  'dana-infraestructura-sistemas': () => import('@/modules/dana/infraestructura/pages/SistemasPage.vue'),
  'dana-infraestructura-componentes': () => import('@/modules/dana/infraestructura/pages/ComponentesPage.vue'),
  'dana-infraestructura-planos': () => import('@/modules/dana/infraestructura/pages/PlanosPage.vue'),
  'dana-infraestructura-interrupciones': () => import('@/modules/dana/infraestructura/pages/InterrupcionesPage.vue'),
  'dana-catastro-tecnico-tipos': () => import('@/modules/dana/catastroTecnico/pages/TiposComponentePage.vue'),
  'dana-calidad-muestras': () => import('@/modules/dana/controlCalidad/pages/MuestrasPage.vue'),
  'dana-calidad-unidades': () => import('@/modules/dana/controlCalidad/pages/UnidadesPage.vue'),
  'dana-calidad-parametros': () => import('@/modules/dana/controlCalidad/pages/ParametrosPage.vue'),
  'dana-calidad-variables-sunass': () => import('@/modules/dana/controlCalidad/pages/VariablesSunassPage.vue'),
  'dana-calidad-resultados': () => import('@/modules/dana/controlCalidad/pages/ResultadosPage.vue'),
  'dana-cisternas-unidades': () => import('@/modules/dana/cisternas/pages/CisternasPage.vue'),
  'dana-cisternas-conductores': () => import('@/modules/dana/cisternas/pages/ConductoresPage.vue'),
  'dana-cisternas-programaciones': () => import('@/modules/dana/cisternas/pages/ProgramacionesPage.vue'),
  'dana-cisternas-abastecimientos': () => import('@/modules/dana/cisternas/pages/AbastecimientosPage.vue'),
  'dana-cisternas-recorridos': () => import('@/modules/dana/cisternas/pages/RecorridosPage.vue'),
  'dana-cisternas-evidencias': () => import('@/modules/dana/cisternas/pages/EvidenciasPage.vue'),
  'dana-cisternas-dashboard': () => import('@/modules/dana/cisternas/pages/DashboardCisternasPage.vue'),
  'dana-produccion-macromedidores': () => import('@/modules/dana/produccion/pages/MacromedidoresPage.vue'),
  'dana-produccion-lecturas': () => import('@/modules/dana/produccion/pages/LecturasPage.vue'),
  'dana-cuadrillas': () => import('@/modules/dana/cuadrillas/pages/CuadrillasPage.vue'),
  'aura-integridad-incidencias': () => import('@/modules/aura/integridad/pages/IncidenciasPage.vue'),
  'aura-comunicaciones-dashboard': () => import('@/modules/aura/comunicaciones/pages/DashboardComunicacionesPage.vue'),
  'aura-comunicaciones-noticias': () => import('@/modules/aura/comunicaciones/pages/NoticiasPage.vue'),
  'aura-comunicaciones-publicaciones': () => import('@/modules/aura/comunicaciones/pages/PublicacionesPage.vue'),
  'aura-comunicaciones-relaciones': () => import('@/modules/aura/comunicaciones/pages/RelacionesPage.vue'),
  'aura-comunicaciones-configuracion': () => import('@/modules/aura/comunicaciones/pages/ConfiguracionPage.vue'),
  'aura-comites-comites': () => import('@/modules/aura/comites/pages/ComitesPage.vue'),
  'aura-comites-reuniones': () => import('@/modules/aura/comites/pages/ReunionesPage.vue'),
  'aura-comites-acuerdos': () => import('@/modules/aura/comites/pages/AcuerdosPage.vue'),
  'aura-comites-tipos': () => import('@/modules/aura/comites/pages/TiposComitePage.vue'),
  'aura-bgc-estructura': () => import('@/modules/aura/bgc/pages/EstructuraBgcPage.vue'),
  'aura-bgc-procesos': () => import('@/modules/aura/bgc/pages/ProcesosEvidenciasPage.vue'),
  'aura-bgc-control-avance': () => import('@/modules/aura/bgc/pages/ControlAvancePage.vue'),
  'aura-directorio-acuerdos': () => import('@/modules/aura/directorio/pages/AcuerdosPage.vue'),
  'aura-directorio-disposiciones': () => import('@/modules/aura/directorio/pages/DisposicionesPage.vue'),
  'aura-directorio-pedidos': () => import('@/modules/aura/directorio/pages/PedidosPage.vue'),
  'aura-directorio-sesiones': () => import('@/modules/aura/directorio/pages/SesionesPage.vue'),
  'etrami-v2-reporte-documentos': () => import('@/modules/etrami/reportes/pages/ReporteDocumentosPage.vue'),
  'etrami-v2-firma-digital': () => import('@/modules/etrami/firma/pages/FirmaDigitalPage.vue'),
  'etrami-v2-externo-remitentes': () => import('@/modules/etrami/externo/pages/RemitentesExternosPage.vue'),
  'etrami-v2-externo-validar': () => import('@/modules/etrami/externo/pages/ValidarExternosPage.vue'),
  'etrami-v2-config-tipos-documento': () => import('@/modules/etrami/configuracion/pages/TiposDocumentoPage.vue'),
  'etrami-v2-config-correlativos': () => import('@/modules/etrami/configuracion/pages/CorrelativosPage.vue'),
  'etrami-v2-flujo-seguimiento': () => import('@/modules/etrami/flujo/pages/SeguimientoDocumentarioPage.vue'),
  'etrami-v2-registrar-documento': () => import('@/modules/etrami/documentos/pages/RegistrarDocumentoPage.vue'),
  'etrami-v2-anulados-rechazados': () => import('@/modules/etrami/documentos/pages/AnuladosRechazadosPage.vue'),
  'etrami-v2-por-recepcionar': () => import('@/modules/etrami/bandejas/pages/PorRecepcionarPage.vue'),
  'etrami-v2-en-bandeja': () => import('@/modules/etrami/bandejas/pages/EnBandejaPage.vue'),
  'etrami-v2-pendientes': () => import('@/modules/etrami/bandejas/pages/PendientesPage.vue'),
  'etrami-v2-propios': () => import('@/modules/etrami/bandejas/pages/PropiosPage.vue'),
  'etrami-v2-archivados': () => import('@/modules/etrami/bandejas/pages/ArchivadosPage.vue'),
  'evan-catastro-conexiones': () => import('@/modules/evan/catastro/pages/ConexionesPage.vue'),
  'evan-catastro-sectores': () => import('@/modules/evan/catastro/pages/SectoresPage.vue'),
  'evan-catastro-manzanas': () => import('@/modules/evan/catastro/pages/ManzanasPage.vue'),
  'evan-catastro-urbanizaciones': () => import('@/modules/evan/catastro/pages/UrbanizacionesPage.vue'),
  'evan-catastro-calles': () => import('@/modules/evan/catastro/pages/CallesPage.vue'),
  'evan-catastro-centros-poblados': () => import('@/modules/evan/catastro/pages/CentrosPobladosPage.vue'),
  'evan-catastro-predios': () => import('@/modules/evan/catastro/pages/PrediosPage.vue'),
  'evan-catastro-clientes': () => import('@/modules/evan/catastro/pages/ClientesPage.vue'),
  'evan-catastro-notificaciones': () => import('@/modules/evan/catastro/pages/NotificacionesPage.vue'),
  'evan-catastro-recategorizar': () => import('@/modules/evan/catastro/pages/RecategorizarPage.vue'),
  'evan-catastro-fichas': () => import('@/modules/evan/catastro/pages/FichasPage.vue'),
  'evan-catastro-tareas': () => import('@/modules/evan/catastro/pages/TareasPage.vue'),
  'evan-catastro-configuraciones': () => import('@/modules/evan/catastro/pages/ConfiguracionesPage.vue'),
  'evan-medicion-medidores': () => import('@/modules/evan/medicion/pages/MedidoresPage.vue'),
  'evan-atencion-expedientes': () => import('@/modules/evan/comercializacion/pages/ExpedientesPage.vue'),
  'evan-comercial-clientes': () => import('@/modules/evan/comercializacion/pages/ClientesPage.vue'),
  'evan-comercial-solicitudes': () => import('@/modules/evan/comercializacion/pages/SolicitudesPage.vue'),
  'evan-comercial-tramites': () => import('@/modules/evan/comercializacion/pages/TramitesPage.vue'),
  'evan-comercial-trabajos': () => import('@/modules/evan/comercializacion/pages/TrabajosPage.vue'),
  'evan-comercial-tareas': () => import('@/modules/evan/comercializacion/pages/TareasPage.vue'),
  'evan-comercial-atencion-externa': () => import('@/modules/evan/comercializacion/pages/AtencionExternaPage.vue'),
  'evan-comercial-call-center': () => import('@/modules/evan/comercializacion/pages/CallCenterPage.vue'),
  'evan-comercial-calculadora-consumo': () => import('@/modules/evan/comercializacion/pages/CalculadoraConsumoPage.vue'),
  'evan-comercial-estadisticas': () => import('@/modules/evan/comercializacion/pages/EstadisticasPage.vue'),
  'evan-comercial-tipos-atencion': () => import('@/modules/evan/comercializacion/pages/TiposAtencionPage.vue'),
  'evan-comercial-acciones': () => import('@/modules/evan/comercializacion/pages/AccionesPage.vue'),
  'evan-comercial-flujos-atencion': () => import('@/modules/evan/comercializacion/pages/FlujosAtencionPage.vue'),
  'evan-comercial-tipos-trabajo': () => import('@/modules/evan/comercializacion/pages/TiposTrabajoPage.vue'),
  'evan-comercial-acciones-flujo': () => import('@/modules/evan/comercializacion/pages/AccionesFlujoPage.vue'),
  'evan-comercial-motivos-expediente': () => import('@/modules/evan/comercializacion/pages/MotivosExpedientePage.vue'),
  'evan-facturacion-ciclos': () => import('@/modules/evan/facturacion/pages/CiclosPage.vue'),
  'evan-facturacion-critica': () => import('@/modules/evan/facturacion/pages/CriticaPage.vue'),
  'evan-cobranza-pagos': () => import('@/modules/evan/cobranza/pages/PagosPage.vue'),
  'evan-cobranza-verificar-cortados': () => import('@/modules/evan/cobranza/pages/VerificarCortadosPage.vue'),
  'evan-sici-conexiones': () => import('@/modules/evan/sici/pages/ConexionesPage.vue'),
  'evan-medicion-padron-lecturas': () => import('@/modules/evan/medicion/pages/PadronLecturasPage.vue'),
  'evan-medicion-lecturas': () => import('@/modules/evan/medicion/pages/LecturasPage.vue'),
  'evan-medicion-atipicos': () => import('@/modules/evan/medicion/pages/AtipicosPage.vue'),
  'evan-medicion-critica-lecturas': () => import('@/modules/evan/medicion/pages/CriticaLecturasPage.vue'),
  'evan-medicion-avisos-altos-consumidores': () => import('@/modules/evan/medicion/pages/AvisosAltosConsumidoresPage.vue'),
  'evan-medicion-avance-lecturas': () => import('@/modules/evan/medicion/pages/AvanceLecturasPage.vue'),
  'evan-medicion-tareas': () => import('@/modules/evan/medicion/pages/TareasPage.vue'),
  'evan-facturacion-tareas': () => import('@/modules/evan/facturacion/pages/TareasPage.vue'),
  'evan-vma-tareas': () => import('@/modules/evan/vma/pages/TareasPage.vue'),
  'evan-cobranza-tareas': () => import('@/modules/evan/cobranza/pages/TareasPage.vue'),
  'evan-operativo-tareas': () => import('@/modules/evan/operativo/pages/TareasPage.vue'),
  'sistema-usuarios-gestion': () => import('@/modules/sistema/usuarios/pages/UsuariosPage.vue'),
  'sistema-administrador-log-accesos': () => import('@/modules/sistema/administrador/pages/LogAccesosPage.vue'),
  'sistema-administrador-errores': () => import('@/modules/sistema/administrador/pages/ErroresSistemaPage.vue'),
  'sistema-administrador-copias-seguridad': () => import('@/modules/sistema/administrador/pages/CopiasSeguridadPage.vue'),
  'sistema-administrador-configuracion': () => import('@/modules/sistema/configuracion/pages/ConfiguracionSistemaPage.vue'),
  'sistema-administrador-tipos-documento': () => import('@/modules/sistema/administrador/pages/TiposDocumentoPage.vue'),
  'sistema-personas-gestion': () => import('@/modules/sistema/personas/pages/PersonasPage.vue'),
  'enki-territorial-procesos': () => import('@/modules/enki/territorial/pages/ProcesosPage.vue'),
  'enki-territorial-regularizacion': () => import('@/modules/enki/territorial/pages/RegularizacionPage.vue'),
  'enki-contratos-gestion': () => import('@/modules/enki/contratos/pages/ContratosPage.vue'),
}

const modules = appModules.map((module) => ({
  path: module.slug,
  name: `module-${module.slug}`,
  component: ModuleView,
  props: { moduleSlug: module.slug },
  children: module.sections.map((section) => ({
    path: section.slug,
    name: `${module.slug}-${section.slug}`,
    component: SectionView,
    props: { moduleSlug: module.slug, sectionSlug: section.slug },
    children: section.options?.map((option) => ({
      path: option.slug,
      name: `${module.slug}-${section.slug}-${option.slug}`,
      component: optionPages[option.page as keyof typeof optionPages],
    })),
  })),
}))

export default createRouter({
  history: createWebHistory(),
  scrollBehavior: () => ({ top: 0 }),
  routes: [
    { path:'/', component:DashboardLayout, children:[
      { path:'', redirect:'/inicio' },
      { path:'inicio', name:'dashboard', component:DashboardView },
      { path:'modulos/integracion/territorial/procesos/:id', name:'enki-territorial-seguimiento', component:SeguimientoProcesoPage, props:true },
      { path:'modulos', children:modules },
    ]},
    { path:'/:pathMatch(.*)*', component:NotFoundView },
  ],
})
