<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { crearProcesoPlanilla, listarProcesosPlanilla } from '../services/procesosPlanilla'
import type { ProcesoPlanillaPayload, RegimenPlanillaOption, TipoPlanillaOption } from '../interfaces/procesoPlanilla.interface'
const now=new Date(),router=useRouter(),form=reactive<ProcesoPlanillaPayload>({anio:now.getFullYear(),mes:now.getMonth()+1,regimen_id:0,tipo_planilla_id:0,fecha_calculo_inicio:'',fecha_calculo_fin:'',numdias:30,numdomingos:4,diasefectivos:26,comentarios:''}),regimenes=ref<RegimenPlanillaOption[]>([]),tipos=ref<TipoPlanillaOption[]>([]),loading=ref(false),saving=ref(false),error=ref('')
const tiposFiltrados=computed(()=>tipos.value.filter(t=>t.regimen_id===form.regimen_id)),message=(v:unknown)=>v instanceof Error?v.message:'No se pudo crear el proceso.'
async function load(){loading.value=true;try{const r=await listarProcesosPlanilla({q:'',anio:null,mes:null,estado:'',regimen_id:null,tipo_planilla_id:null},1);regimenes.value=r.regimenes;tipos.value=r.tipos_planilla}catch(v){error.value=message(v)}finally{loading.value=false}}
function changeRegimen(){form.tipo_planilla_id=0}
async function save(){error.value='';if(!form.regimen_id||!form.tipo_planilla_id||!form.fecha_calculo_inicio||!form.fecha_calculo_fin)return void(error.value='Complete todos los campos obligatorios.');if(form.fecha_calculo_fin<form.fecha_calculo_inicio)return void(error.value='La fecha Hasta debe ser mayor o igual a Desde.');if(form.numdomingos>form.numdias||form.diasefectivos>form.numdias)return void(error.value='Domingos y días efectivos no pueden superar el número de días.');if(form.comentarios.length>1000)return void(error.value='Los comentarios no pueden superar los 1000 caracteres.');saving.value=true;try{await crearProcesoPlanilla(form);await router.push('/modulos/administracion/recursos/procesos-planilla')}catch(v){error.value=message(v)}finally{saving.value=false}}
onMounted(load)
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/recursos/procesos-planilla">Procesos de planilla</RouterLink> / Crear</nav><header class="hero"><div class="mark">NP</div><div><small>MIA · RECURSOS HUMANOS · PLANILLAS</small><h1>Nuevo proceso de planilla</h1><p>Crea un borrador para seleccionar trabajadores y ejecutar posteriormente el cálculo.</p></div></header><p v-if="error" class="flash">{{error}}</p><div v-if="loading" class="empty">Cargando opciones de planilla…</div><form v-else class="form" @submit.prevent="save"><section><h2>Periodo y tipo de planilla</h2><div class="grid"><label>Año *<input v-model.number="form.anio" type="number" min="2000" max="2100" required></label><label>Mes *<select v-model.number="form.mes"><option v-for="m in 12" :key="m" :value="m">{{m}}</option></select></label><label>Régimen *<select v-model.number="form.regimen_id" @change="changeRegimen"><option :value="0">Seleccione</option><option v-for="r in regimenes" :key="r.id" :value="r.id">{{r.codigo?`${r.codigo} - `:''}}{{r.descripcion}}</option></select></label><label>Tipo de planilla *<select v-model.number="form.tipo_planilla_id" :disabled="!form.regimen_id"><option :value="0">Seleccione</option><option v-for="t in tiposFiltrados" :key="t.id" :value="t.id">{{t.codigo?`${t.codigo} - `:''}}{{t.descripcion}}</option></select></label></div></section><section><h2>Rango de cálculo</h2><div class="grid dates"><label>Desde *<input v-model="form.fecha_calculo_inicio" type="date" required></label><label>Hasta *<input v-model="form.fecha_calculo_fin" type="date" required></label></div></section><section><h2>Días del proceso</h2><div class="grid days"><label>Número de días *<input v-model.number="form.numdias" type="number" min="0"></label><label>Número de domingos *<input v-model.number="form.numdomingos" type="number" min="0"></label><label>Días efectivos *<input v-model.number="form.diasefectivos" type="number" min="0"></label></div></section><label>Comentarios<textarea v-model="form.comentarios" rows="4" maxlength="1000"></textarea><small>{{form.comentarios.length}} / 1000</small></label><footer><RouterLink to="/modulos/administracion/recursos/procesos-planilla" class="cancel">Cancelar</RouterLink><button :disabled="saving">{{saving?'Creando…':'Crear borrador'}}</button></footer></form></div></template>
<style scoped>
.page{--a:#2f91a0;color:#35464e;max-width:1000px}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--a);text-decoration:none}.hero{padding:20px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:48px;height:48px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero small{color:var(--a);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.3rem}.hero p{margin:0;color:#7e8a90;font-size:.67rem}.flash{padding:9px;color:#a64046;background:#fff0f0}.empty{margin-top:12px;padding:45px;text-align:center;background:#fff}.form{margin-top:12px;padding:20px;display:grid;gap:18px;background:#fff}.form section{padding-bottom:16px;border-bottom:1px solid #e5eaec}.form h2{margin:0 0 10px;color:var(--a);font-size:.7rem}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.dates{grid-template-columns:1fr 1fr}.days{grid-template-columns:repeat(3,1fr)}label{display:grid;gap:5px;font-size:.51rem}input,select,textarea{min-width:0;padding:10px;border:1px solid #d7dfe2;border-radius:6px;background:#fff;font:inherit;font-size:.53rem}textarea{resize:vertical}label small{text-align:right;color:#8a969b}.form>footer{display:flex;justify-content:flex-end;align-items:center;gap:8px}.form button,.cancel{padding:10px 14px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.53rem;text-decoration:none}.cancel{color:#64727a;background:#edf1f3}@media(max-width:750px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.grid{grid-template-columns:1fr}}
</style>
