<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ejecutarAccionProceso, obtenerProcesoPlanilla } from '../services/procesosPlanilla'
import type { ProcesoPlanilla } from '../interfaces/procesoPlanilla.interface'
const route=useRoute(),proceso=ref<ProcesoPlanilla|null>(null),loading=ref(false),working=ref(false),error=ref(''),success=ref(''),id=computed(()=>Number(route.query.id||0))
const message=(v:unknown)=>v instanceof Error?v.message:'No se pudo completar la operación.'
const date=(v:string|null)=>v?new Intl.DateTimeFormat('es-PE',{timeZone:'UTC'}).format(new Date(`${v.substring(0,10)}T00:00:00Z`)):'N/D'
const estadoInfo=computed(()=>({BORRADOR:'En edición',CALCULADO:'Listo para validar',VALIDADO:'Listo para cerrar',CERRADO:'Finalizado',ANULADO:'Proceso anulado'}[proceso.value?.estado??'']??''))
async function load(){if(!id.value)return void(error.value='Indique el proceso mediante el parámetro ?id=.');loading.value=true;error.value='';try{proceso.value=await obtenerProcesoPlanilla(id.value)}catch(v){error.value=message(v)}finally{loading.value=false}}
async function action(accion:'recalcular-todo'|'validar'|'cerrar'|'anular',label:string){if(!proceso.value||!confirm(`¿Confirma ${label.toLowerCase()} el proceso ${proceso.value.codigo_proceso}?`))return;working.value=true;error.value='';try{proceso.value=await ejecutarAccionProceso(proceso.value.id,accion);success.value=`Proceso ${label.toLowerCase()} correctamente.`}catch(v){error.value=message(v)}finally{working.value=false}}
onMounted(load)
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/recursos/procesos-planilla">Procesos de planilla</RouterLink> / Detalle</nav><div v-if="loading" class="empty">Cargando proceso…</div><template v-else-if="proceso"><header class="hero"><div class="mark">#{{proceso.id}}</div><div><small>MIA · RR. HH. · PLANILLAS</small><h1>{{proceso.codigo_proceso}}</h1><p>Detalle y control del proceso de planilla.</p></div><RouterLink to="/modulos/administracion/recursos/procesos-planilla">Volver</RouterLink></header><p v-if="success" class="flash success">✓ {{success}}</p><p v-if="error" class="flash error">{{error}}</p><section class="state" :data-state="proceso.estado"><b>Estado actual: {{proceso.estado}}</b><span>{{estadoInfo}}</span></section><main><section><h2>Información general</h2><div class="facts"><div><b>Periodo</b><span>{{proceso.mes}}/{{proceso.anio}}</span></div><div><b>Régimen</b><span>{{proceso.regimen?.descripcion??'TODOS'}}</span></div><div><b>Tipo de planilla</b><span>{{proceso.tipo_planilla?.descripcion??'N/D'}}</span></div><div><b>Total trabajadores</b><span class="count">{{proceso.total_trabajadores}}</span></div></div></section><section><h2>Fechas y días</h2><div class="facts"><div><b>Desde</b><span>{{date(proceso.fecha_calculo_inicio)}}</span></div><div><b>Hasta</b><span>{{date(proceso.fecha_calculo_fin)}}</span></div><div><b>Días laborales</b><span>{{proceso.numdias}} días</span></div><div><b>Distribución</b><span>{{proceso.numdomingos}} domingos · {{proceso.diasefectivos}} efectivos</span></div></div></section><section v-if="proceso.comentarios"><h2>Comentarios</h2><p>{{proceso.comentarios}}</p></section><section><h2>Acciones del proceso</h2><div class="actions"><button v-if="proceso.estado==='BORRADOR'" disabled title="La selección de trabajadores se migrará a continuación">Calcular / seleccionar trabajadores</button><button v-if="proceso.estado==='CALCULADO'" class="warning" :disabled="working" @click="action('recalcular-todo','Recalcular')">Recalcular todo</button><button v-if="proceso.estado==='CALCULADO'" class="success-btn" :disabled="working" @click="action('validar','Validar')">Validar</button><button v-if="proceso.estado==='VALIDADO'" class="dark" :disabled="working" @click="action('cerrar','Cerrar')">Cerrar</button><button v-if="['BORRADOR','CALCULADO','VALIDADO'].includes(proceso.estado)" class="danger" :disabled="working" @click="action('anular','Anular')">Anular</button></div></section></main></template><p v-else-if="error" class="flash error">{{error}}</p></div></template>
<style scoped>
.page{--a:#2f91a0;color:#35464e;max-width:1100px}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--a);text-decoration:none}.hero{padding:20px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{min-width:52px;height:48px;padding:0 7px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero>div:nth-child(2){flex:1}.hero small{color:var(--a);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.3rem}.hero p{margin:0;color:#7e8a90;font-size:.67rem}.hero>a{padding:8px 11px;color:#63737a;background:#edf1f3;border-radius:6px;text-decoration:none;font-size:.52rem}.flash{padding:9px}.success{color:#26704f;background:#eaf8f1}.error{color:#a64046;background:#fff0f0}.empty{padding:45px;text-align:center;background:#fff}.state{margin-top:12px;padding:13px;display:flex;gap:9px;background:#e8f5f6;font-size:.57rem}.state span{color:#6d7d83}main{margin-top:12px;padding:20px;display:grid;gap:22px;background:#fff}main section{padding-bottom:18px;border-bottom:1px solid #e5eaec}main section:last-child{border:0}h2{margin:0 0 12px;color:var(--a);font-size:.7rem}.facts{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.facts div{padding:11px;display:grid;gap:5px;background:#f6f8f9;font-size:.52rem}.facts b{color:#748289}.count{font-size:.8rem;font-weight:800}.actions{display:flex;flex-wrap:wrap;gap:8px}.actions button{padding:10px 13px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.53rem}.actions button:disabled{opacity:.55}.warning{background:#d18a28!important}.success-btn{background:#298b62!important}.dark{background:#34464f!important}.danger{background:#bd4f55!important}@media(max-width:750px){.facts{grid-template-columns:repeat(2,1fr)}}@media(max-width:450px){.facts{grid-template-columns:1fr}.hero{flex-wrap:wrap}}
</style>
