<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { crearProcesoPlanilla, listarProcesosPlanilla } from '../services/procesosPlanilla'
import type { EstadoPlanillaOption, FiltrosProcesosPlanilla, ProcesoPlanilla, ProcesoPlanillaPayload, RegimenPlanillaOption, TipoPlanillaOption } from '../interfaces/procesoPlanilla.interface'
const now=new Date(),filtros=reactive<FiltrosProcesosPlanilla>({q:'',anio:null,mes:null,estado:'',regimen_id:null,tipo_planilla_id:null}),form=reactive<ProcesoPlanillaPayload>({anio:now.getFullYear(),mes:now.getMonth()+1,regimen_id:0,tipo_planilla_id:0,fecha_calculo_inicio:'',fecha_calculo_fin:'',numdias:30,numdomingos:4,diasefectivos:26,comentarios:''}),rows=ref<ProcesoPlanilla[]>([]),regimenes=ref<RegimenPlanillaOption[]>([]),tipos=ref<TipoPlanillaOption[]>([]),estados=ref<EstadoPlanillaOption[]>([]),page=ref(1),lastPage=ref(1),total=ref(0),loading=ref(false),saving=ref(false),modal=ref(false),error=ref(''),success=ref('')
const tiposFiltrados=computed(()=>filtros.regimen_id?tipos.value.filter(t=>t.regimen_id===filtros.regimen_id):tipos.value)
const tiposForm=computed(()=>tipos.value.filter(t=>t.regimen_id===form.regimen_id))
const message=(v:unknown)=>v instanceof Error?v.message:'No se pudo consultar los procesos de planilla.'
const date=(v:string|null)=>v?new Intl.DateTimeFormat('es-PE',{timeZone:'UTC'}).format(new Date(`${v.substring(0,10)}T00:00:00Z`)):'N/D'
async function load(next=1){loading.value=true;error.value='';try{const r=await listarProcesosPlanilla(filtros,next);rows.value=r.data;regimenes.value=r.regimenes;tipos.value=r.tipos_planilla;estados.value=r.estados;page.value=r.current_page;lastPage.value=r.last_page;total.value=r.total}catch(v){error.value=message(v)}finally{loading.value=false}}
function changeRegimen(){if(filtros.tipo_planilla_id&&!tiposFiltrados.value.some(t=>t.id===filtros.tipo_planilla_id))filtros.tipo_planilla_id=null}
function open(){Object.assign(form,{anio:now.getFullYear(),mes:now.getMonth()+1,regimen_id:0,tipo_planilla_id:0,fecha_calculo_inicio:'',fecha_calculo_fin:'',numdias:30,numdomingos:4,diasefectivos:26,comentarios:''});error.value='';modal.value=true}
function changeFormRegimen(){form.tipo_planilla_id=0}
async function save(){error.value='';if(!form.regimen_id||!form.tipo_planilla_id||!form.fecha_calculo_inicio||!form.fecha_calculo_fin)return void(error.value='Complete todos los campos obligatorios.');if(form.fecha_calculo_fin<form.fecha_calculo_inicio)return void(error.value='La fecha Hasta debe ser mayor o igual a Desde.');if(form.numdomingos>form.numdias||form.diasefectivos>form.numdias)return void(error.value='Domingos y días efectivos no pueden superar el número de días.');if(form.comentarios.length>1000)return void(error.value='Los comentarios no pueden superar los 1000 caracteres.');saving.value=true;try{await crearProcesoPlanilla(form);modal.value=false;success.value='Proceso creado correctamente en estado BORRADOR.';await load(1)}catch(v){error.value=message(v)}finally{saving.value=false}}
function clear(){Object.assign(filtros,{q:'',anio:null,mes:null,estado:'',regimen_id:null,tipo_planilla_id:null});load(1)}
onMounted(()=>load())
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/recursos">Recursos Humanos</RouterLink> / Procesos de planilla</nav><header class="hero"><div class="mark">PP</div><div><small>MIA · RECURSOS HUMANOS · PLANILLAS</small><h1>Procesos de planilla</h1><p>Consulta los periodos procesados, su alcance, estado y cantidad de trabajadores.</p></div><strong>{{total}} procesos</strong></header><p v-if="error" class="flash">{{error}}</p><form class="filters" @submit.prevent="load(1)"><input v-model.trim="filtros.q" placeholder="Código o comentario"><input v-model.number="filtros.anio" type="number" min="2000" max="2100" placeholder="Año"><select v-model.number="filtros.mes"><option :value="null">Mes (todos)</option><option v-for="m in 12" :key="m" :value="m">{{m}}</option></select><select v-model="filtros.estado"><option value="">Estado (todos)</option><option v-for="e in estados" :key="e.codigo" :value="e.codigo">{{e.nombre}}</option></select><select v-model="filtros.regimen_id" @change="changeRegimen"><option :value="null">Régimen (todos)</option><option v-for="r in regimenes" :key="r.id" :value="r.id">{{r.descripcion}}</option></select><select v-model="filtros.tipo_planilla_id"><option :value="null">Tipo de planilla (todos)</option><option v-for="t in tiposFiltrados" :key="t.id" :value="t.id">{{t.descripcion}}</option></select><footer><button type="button" class="soft" @click="clear">Limpiar</button><button>Filtrar</button></footer></form><section class="table-card"><div v-if="loading" class="empty">Consultando procesos de planilla…</div><div v-else-if="!rows.length" class="empty">No hay procesos de planilla para los filtros seleccionados.</div><div v-else class="scroll"><table><thead><tr><th>ID</th><th>Código</th><th>Periodo</th><th>Régimen</th><th>Tipo planilla</th><th>Desde</th><th>Hasta</th><th>Días</th><th>Domingos</th><th>Efectivos</th><th>Estado</th><th>Trabajadores</th></tr></thead><tbody><tr v-for="p in rows" :key="p.id"><td>#{{p.id}}</td><td><b>{{p.codigo_proceso}}</b></td><td>{{p.mes}}/{{p.anio}}</td><td>{{p.regimen?.descripcion??'TODOS'}}</td><td>{{p.tipo_planilla?.descripcion??'N/D'}}</td><td>{{date(p.fecha_calculo_inicio)}}</td><td>{{date(p.fecha_calculo_fin)}}</td><td class="num">{{p.numdias??0}}</td><td class="num">{{p.numdomingos??0}}</td><td class="num">{{p.diasefectivos??0}}</td><td><span class="status">{{p.estado}}</span></td><td class="num"><b>{{p.total_trabajadores}}</b></td></tr></tbody></table></div><footer v-if="lastPage>1"><button :disabled="page<=1" @click="load(page-1)">Anterior</button><span>Página {{page}} de {{lastPage}}</span><button :disabled="page>=lastPage" @click="load(page+1)">Siguiente</button></footer></section></div></template>
<style scoped>
.page{--a:#2f91a0;color:#35464e}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--a);text-decoration:none}.hero{padding:20px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:48px;height:48px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero>div:nth-child(2){flex:1}.hero small{color:var(--a);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.3rem}.hero p{margin:0;color:#7e8a90;font-size:.67rem}.hero>strong{font-size:.56rem}.flash{padding:9px;color:#a64046;background:#fff0f0}.filters{margin-top:12px;padding:12px;display:grid;grid-template-columns:2fr .7fr .8fr 1fr 1.2fr 1.4fr;gap:7px;background:#fff}.filters input,.filters select{min-width:0;padding:9px;border:1px solid #d7dfe2;border-radius:6px;background:#fff;font:inherit;font-size:.5rem}.filters footer{grid-column:1/-1;display:flex;justify-content:flex-end;gap:6px}.filters button,.table-card button{padding:9px 12px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.52rem}.soft{color:#64727a!important;background:#edf1f3!important}.table-card{margin-top:12px;background:#fff}.empty{padding:45px;text-align:center}.scroll{overflow:auto}table{width:100%;min-width:1250px;border-collapse:collapse;font-size:.48rem}th,td{padding:8px;border:1px solid #e1e7ea;text-align:left}thead{color:#fff;background:#354a55}tbody tr:nth-child(even){background:#f7f9fa}.num{text-align:right}.status{display:inline-block;padding:3px 7px;border-radius:10px;color:#286b72;background:#dcf1f3;font-size:.44rem}.table-card>footer{padding:10px;display:flex;justify-content:center;align-items:center;gap:10px;font-size:.52rem}@media(max-width:950px){.filters{grid-template-columns:repeat(3,1fr)}}@media(max-width:550px){.filters{grid-template-columns:1fr}}
</style>
