<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { listarReporteConcepto } from '../services/reportesPlanilla'
import type { RegimenPlanillaOption } from '../interfaces/procesoPlanilla.interface'
import type { FiltrosReporteConcepto, ReporteConceptoItem, TrabajadorReporteOption } from '../interfaces/reporteConcepto.interface'

const now=new Date(),defaultPeriod=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`
const filtros=reactive<FiltrosReporteConcepto>({periodo:defaultPeriod,regimen_ids:[],datos_persona_ids:[]})
const rows=ref<ReporteConceptoItem[]>([]),regimenes=ref<RegimenPlanillaOption[]>([]),trabajadores=ref<TrabajadorReporteOption[]>([])
const page=ref(1),lastPage=ref(1),total=ref(0),totalMonto=ref(0),pdfUrl=ref<string|null>(null),excelUrl=ref<string|null>(null),loading=ref(false),error=ref('')
const money=(v:number)=>`S/ ${new Intl.NumberFormat('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))}`
const message=(v:unknown)=>v instanceof Error?v.message:'No se pudo cargar el reporte.'
const rubroClass=(r:string|null)=>{const value=(r||'').toUpperCase();return value.includes('DESCUENT')?'discount':value.includes('APORT')?'contribution':'income'}
async function load(next=1){loading.value=true;error.value='';try{const r=await listarReporteConcepto(filtros,next);rows.value=r.data;page.value=r.current_page;lastPage.value=r.last_page;total.value=r.total;totalMonto.value=r.total_monto;regimenes.value=r.regimenes;trabajadores.value=r.trabajadores_filtro;pdfUrl.value=r.pdf_url||null;excelUrl.value=r.excel_url||null}catch(v){error.value=message(v)}finally{loading.value=false}}
function clear(){filtros.periodo=defaultPeriod;filtros.regimen_ids=[];filtros.datos_persona_ids=[];load(1)}
onMounted(()=>load())
</script>

<template>
  <div class="page">
    <nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/recursos">Recursos Humanos</RouterLink> / Reporte por concepto</nav>
    <header class="hero"><div class="mark">RC</div><div><small>MIA · RR. HH. · PLANILLAS</small><h1>Reporte de planilla a nivel de concepto</h1><p>Conceptos calculados por trabajador, periodo y régimen.</p></div><strong>{{total}} registros</strong></header>
    <p v-if="error" class="flash">{{error}}</p>
    <form class="filters" @submit.prevent="load(1)"><label>Periodo<input v-model="filtros.periodo" type="month"></label><label>Regímenes<select v-model="filtros.regimen_ids" multiple><option v-for="r in regimenes" :key="r.id" :value="r.id">{{r.codigo?`${r.codigo} - `:''}}{{r.descripcion}}</option></select><small>Sin selección: todos</small></label><label>Trabajadores<select v-model="filtros.datos_persona_ids" multiple><option v-for="t in trabajadores" :key="t.id" :value="t.id">{{t.codigo_trabajador}} - {{t.nombre_completo}}</option></select><small>Sin selección: todos</small></label><div class="filter-actions"><button>Filtrar</button><button type="button" class="soft" @click="clear">Limpiar</button></div></form>
    <div class="exports"><a v-if="pdfUrl" :href="pdfUrl" target="_blank" class="pdf">Exportar PDF</a><a v-if="excelUrl" :href="excelUrl" class="excel">Exportar Excel</a><span v-if="!pdfUrl&&!excelUrl">Las exportaciones se habilitarán cuando el API entregue sus URLs.</span></div>
    <section class="card"><div v-if="loading" class="empty">Generando reporte…</div><div v-else-if="!rows.length" class="empty">No se encontraron registros para los filtros seleccionados.</div><div v-else class="scroll"><table><thead><tr><th>Cod. trab.</th><th>Apellidos y nombre</th><th>DNI</th><th>Régimen</th><th>Concepto</th><th>Rubro</th><th>Periodo</th><th class="num">Monto</th></tr></thead><tbody><tr v-for="item in rows" :key="item.id"><td>{{item.codigo_trabajador||'N/D'}}</td><td>{{item.persona_nombre||'N/D'}}</td><td>{{item.persona_dni||'N/D'}}</td><td>{{item.regimen_descripcion||'N/D'}}</td><td><b>{{item.codigo_concepto_snapshot}}</b><small>{{item.descripcion_concepto_snapshot}}</small></td><td><span :class="rubroClass(item.rubro)">{{item.rubro||'N/D'}}</span></td><td>{{item.periodo_texto||filtros.periodo}}</td><td class="num">{{money(item.monto_calculado)}}</td></tr></tbody><tfoot><tr><th colspan="7">Total</th><th class="num">{{money(totalMonto)}}</th></tr></tfoot></table></div><footer v-if="lastPage>1"><small>Mostrando {{rows.length}} registros en esta página.</small><div><button :disabled="page<=1" @click="load(page-1)">Anterior</button><span>{{page}} / {{lastPage}}</span><button :disabled="page>=lastPage" @click="load(page+1)">Siguiente</button></div></footer></section>
  </div>
</template>

<style scoped>
.page{--a:#2f91a0;color:#35464e}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--a);text-decoration:none}.hero{padding:20px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:48px;height:48px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero>div:nth-child(2){flex:1}.hero small{color:var(--a);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.2rem}.hero p{margin:0;color:#7e8a90;font-size:.58rem}.hero>strong{font-size:.55rem}.flash{padding:10px;color:#a64046;background:#fff0f0}.filters{margin-top:12px;padding:14px;display:grid;grid-template-columns:180px 1fr 1.4fr auto;gap:10px;align-items:end;background:#fff}.filters label{display:grid;gap:5px;font-size:.52rem;font-weight:700}.filters input,.filters select{padding:8px;border:1px solid #d7dfe2;border-radius:6px;background:#fff;font:inherit;font-size:.5rem}.filters select{min-height:74px}.filters small{color:#929da2;font-size:.43rem;font-weight:400}button,.exports a{padding:9px 12px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.5rem;text-decoration:none;cursor:pointer}.filter-actions{display:flex;gap:6px}.soft{color:#64727a;background:#edf1f3}.exports{padding:12px 0;display:flex;justify-content:flex-end;align-items:center;gap:7px}.exports span{color:#8c989e;font-size:.48rem}.exports .pdf{background:#bd4650}.exports .excel{background:#31825e}.card{background:#fff}.empty{padding:45px;text-align:center}.scroll{overflow:auto}table{width:100%;min-width:1050px;border-collapse:collapse;font-size:.48rem}th,td{padding:8px;border:1px solid #e1e7ea;text-align:left}thead{background:#f3f4f6}td small{display:block;margin-top:3px;color:#8b969b}td>span{display:inline-block;padding:4px 7px;border-radius:10px;font-weight:700}.income{color:#1d4ed8;background:#e8f1ff}.discount{color:#b42318;background:#fdecec}.contribution{color:#1f6f3d;background:#e8f7ed}.num{text-align:right}tfoot{background:#f3f6f7}tfoot th:first-child{text-align:right}.card>footer{padding:10px;display:flex;justify-content:space-between;align-items:center}.card>footer div{display:flex;align-items:center;gap:8px;font-size:.5rem}@media(max-width:900px){.filters{grid-template-columns:1fr 1fr}.filter-actions{align-self:end}}@media(max-width:550px){.filters{grid-template-columns:1fr}.hero>strong{display:none}.exports{justify-content:flex-start}}
</style>
