<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { obtenerResumenProcesoPlanilla } from '../services/procesosPlanilla'
import type { ProcesoPlanilla } from '../interfaces/procesoPlanilla.interface'
const route=useRoute(),id=computed(()=>Number(route.query.id||0)),proceso=ref<ProcesoPlanilla|null>(null),loading=ref(false),error=ref('')
const calculado=computed(()=>Boolean(proceso.value&&['CALCULADO','VALIDADO','CERRADO'].includes(proceso.value.estado))),money=(v:number|undefined)=>`S/ ${new Intl.NumberFormat('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0))}`,message=(v:unknown)=>v instanceof Error?v.message:'No se pudo cargar el resumen.'
async function load(){if(!id.value)return void(error.value='Indique el proceso mediante el parámetro ?id=.');loading.value=true;try{proceso.value=await obtenerResumenProcesoPlanilla(id.value)}catch(v){error.value=message(v)}finally{loading.value=false}}
onMounted(load)
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/recursos/procesos-planilla">Procesos</RouterLink> / Resumen</nav><div v-if="loading" class="empty">Cargando resumen…</div><template v-else-if="proceso"><header class="hero"><div class="mark">RP</div><div><small>MIA · RR. HH. · PLANILLAS</small><h1>Resumen del proceso #{{proceso.id}}</h1><p>{{proceso.codigo_proceso}} · Periodo {{proceso.mes}}/{{proceso.anio}}</p></div><span>{{proceso.estado}}</span></header><p v-if="!calculado" class="warning">El proceso está en estado <b>{{proceso.estado}}</b>. Los totales se mostrarán una vez que se ejecute el cálculo.</p><main><article class="workers"><small>Total trabajadores</small><strong>{{proceso.total_trabajadores}}</strong><span>Personas incluidas en el proceso</span></article><article class="income"><small>Ingresos</small><strong>{{money(proceso.total_ingresos)}}</strong><span>Remuneraciones y otros ingresos</span></article><article class="discount"><small>Descuentos</small><strong>{{money(proceso.total_descuentos)}}</strong><span>Retenciones y deducciones</span></article><article class="net"><small>Neto</small><strong>{{money(proceso.total_neto)}}</strong><span>Monto total a pagar</span></article></main><section class="balance"><div><b>Ingresos</b><span>{{money(proceso.total_ingresos)}}</span></div><i>−</i><div><b>Descuentos</b><span>{{money(proceso.total_descuentos)}}</span></div><i>=</i><div><b>Neto calculado</b><span>{{money(proceso.total_neto)}}</span></div></section><footer><RouterLink :to="`/modulos/administracion/recursos/detalle-proceso-planilla?id=${proceso.id}`">Volver al proceso</RouterLink></footer></template><p v-else-if="error" class="error">{{error}}</p></div></template>
<style scoped>
.page{--a:#2f91a0;color:#35464e;max-width:1100px}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--a);text-decoration:none}.hero{padding:20px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:48px;height:48px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero>div:nth-child(2){flex:1}.hero small{color:var(--a);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.25rem}.hero p{margin:0;color:#7e8a90;font-size:.62rem}.hero>span{padding:5px 9px;border-radius:12px;color:#28717a;background:#dcf1f3;font-size:.5rem}.empty,.error{padding:45px;text-align:center;background:#fff}.error{color:#a64046}.warning{padding:11px;color:#8b681e;background:#fff5d9;font-size:.55rem}main{margin-top:14px;display:grid;grid-template-columns:repeat(4,1fr);gap:10px}article{padding:17px;display:grid;gap:7px;border-top:4px solid;background:#fff}article small{color:#748188;font-size:.5rem}article strong{font-size:1.15rem}article span{color:#8b969b;font-size:.48rem}.workers{border-color:#3d72a9}.income{border-color:#32936f}.discount{border-color:#c65a62}.net{border-color:#2f91a0}.balance{margin-top:14px;padding:20px;display:flex;align-items:center;justify-content:center;gap:20px;background:#fff}.balance div{display:grid;gap:4px;text-align:center;font-size:.55rem}.balance span{font-size:.8rem;font-weight:800}.balance i{color:#879399;font-size:1rem}.page>footer{margin-top:14px}.page>footer a{display:inline-block;padding:10px 13px;border-radius:6px;color:#64727a;background:#edf1f3;text-decoration:none;font-size:.53rem}@media(max-width:750px){main{grid-template-columns:repeat(2,1fr)}.balance{flex-direction:column}}@media(max-width:430px){main{grid-template-columns:1fr}}
</style>
