<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { cambiarEstadoActividad, guardarActividad, listarActividades } from '../services/actividades'
import type { Actividad, ActividadPayload, SubProcesoOption } from '../interfaces/actividad.interface'
const rows=ref<Actividad[]>([]),subprocesos=ref<SubProcesoOption[]>([]),criterio=ref(''),page=ref(1),lastPage=ref(1),total=ref(0),loading=ref(false),saving=ref(false),error=ref(''),success=ref(''),modal=ref(false),editing=ref<number|null>(null)
const form=reactive<ActividadPayload>({nombre:'',descripcion:'',sub_proceso_id:0})
const message=(v:unknown)=>v instanceof Error?v.message:'No se pudo completar la operación.'
async function load(next=1){loading.value=true;error.value='';try{const r=await listarActividades(criterio.value,next);rows.value=r.data;subprocesos.value=r.subprocesos??[];page.value=r.current_page;lastPage.value=r.last_page;total.value=r.total}catch(v){error.value=message(v)}finally{loading.value=false}}
function open(item?:Actividad){editing.value=item?.id??null;form.nombre=item?.nombre??'';form.descripcion=item?.descripcion??'';form.sub_proceso_id=item?.sub_proceso_id??0;error.value='';modal.value=true}
async function save(){const nombre=form.nombre.trim(),descripcion=form.descripcion.trim();if(!form.sub_proceso_id)return void(error.value='Debe seleccionar un subproceso.');if(nombre.length<2||nombre.length>45)return void(error.value='El nombre debe tener entre 2 y 45 caracteres.');if(descripcion.length>100)return void(error.value='La descripción no puede superar los 100 caracteres.');saving.value=true;error.value='';try{await guardarActividad(editing.value,{nombre:nombre.toUpperCase(),descripcion:descripcion.toUpperCase(),sub_proceso_id:form.sub_proceso_id});modal.value=false;success.value=`Actividad ${editing.value?'actualizada':'registrada'} correctamente.`;await load(editing.value?page.value:1)}catch(v){error.value=message(v)}finally{saving.value=false}}
async function toggle(item:Actividad){if(!confirm(`¿Desea ${item.activo?'desactivar':'activar'} la actividad ${item.nombre}?`))return;try{await cambiarEstadoActividad(item.id);success.value='Estado actualizado correctamente.';await load(page.value)}catch(v){error.value=message(v)}}
onMounted(()=>load())
</script>
<template><div class="page" style="--a:#d08b32"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/contabilidad">Contabilidad</RouterLink> / <RouterLink to="/modulos/administracion/contabilidad/parametros-costos">Parámetros de costos</RouterLink> / Actividades</nav><header class="hero"><div class="mark">AC</div><div><small>MIA · CONTABILIDAD · COSTOS</small><h1>Actividades</h1><p>Administra las actividades específicas ejecutadas dentro de cada subproceso.</p></div><strong>{{total}} registros</strong><button @click="open()">+ Nueva actividad</button></header><p v-if="success" class="flash success">✓ {{success}}</p><p v-if="error" class="flash error">{{error}}</p><form class="filters" @submit.prevent="load(1)"><input v-model.trim="criterio" placeholder="Buscar por nombre o descripción"><button>Buscar</button><button type="button" class="soft" @click="criterio='';load(1)">Limpiar</button></form><section class="table-card"><div v-if="loading" class="empty">Consultando actividades…</div><div v-else-if="!rows.length" class="empty">No se encontraron actividades.</div><div v-else class="scroll"><table><thead><tr><th>ID</th><th>Nombre</th><th>Descripción</th><th>Subproceso</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><tr v-for="item in rows" :key="item.id"><td>#{{item.id}}</td><td><b>{{item.nombre}}</b></td><td>{{item.descripcion||'—'}}</td><td>{{item.sub_proceso?.nombre||'—'}}</td><td><span :class="item.activo?'ok':'bad'">{{item.activo?'Activo':'Inactivo'}}</span></td><td class="actions"><button class="edit" @click="open(item)">Editar</button><button class="soft" @click="toggle(item)">{{item.activo?'Desactivar':'Activar'}}</button></td></tr></tbody></table></div><footer v-if="lastPage>1"><button :disabled="page<=1" @click="load(page-1)">Anterior</button><span>{{page}} / {{lastPage}}</span><button :disabled="page>=lastPage" @click="load(page+1)">Siguiente</button></footer></section><div v-if="modal" class="backdrop" @mousedown.self="modal=false"><form class="dialog" @submit.prevent="save"><header><div><small>PARÁMETROS DE COSTOS</small><h2>{{editing?'Editar':'Nueva'}} actividad</h2></div><button type="button" @click="modal=false">×</button></header><label>Subproceso *<select v-model.number="form.sub_proceso_id" required><option :value="0">Seleccione</option><option v-for="item in subprocesos" :key="item.id" :value="item.id">{{item.nombre}}</option></select></label><label>Nombre *<input v-model="form.nombre" required minlength="2" maxlength="45" @input="form.nombre=form.nombre.toUpperCase()"></label><label>Descripción<input v-model="form.descripcion" maxlength="100" @input="form.descripcion=form.descripcion.toUpperCase()"></label><footer><button type="button" class="soft" @click="modal=false">Cancelar</button><button :disabled="saving">{{saving?'Guardando…':'Guardar'}}</button></footer></form></div></div></template>
<style scoped src="./costCrud.css"></style>
