<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { cambiarEstadoInductor, guardarInductor, listarInductores } from '../services/inductores'
import type { Inductor, InductorPayload, OrigenComprobanteOption } from '../interfaces/inductor.interface'
const rows=ref<Inductor[]>([]),origenes=ref<OrigenComprobanteOption[]>([]),criterio=ref(''),page=ref(1),lastPage=ref(1),total=ref(0),loading=ref(false),saving=ref(false),error=ref(''),success=ref(''),modal=ref(false),editing=ref<number|null>(null)
const form=reactive<InductorPayload>({nombre:'',descripcion:'',origen_comprobante_id:0})
const message=(v:unknown)=>v instanceof Error?v.message:'No se pudo completar la operación.'
async function load(next=1){loading.value=true;error.value='';try{const r=await listarInductores(criterio.value,next);rows.value=r.data;origenes.value=r.origenes??[];page.value=r.current_page;lastPage.value=r.last_page;total.value=r.total}catch(v){error.value=message(v)}finally{loading.value=false}}
function open(item?:Inductor){editing.value=item?.id??null;form.nombre=item?.nombre??'';form.descripcion=item?.descripcion??'';form.origen_comprobante_id=item?.origen_comprobante_id??0;error.value='';modal.value=true}
async function save(){const nombre=form.nombre.trim(),descripcion=form.descripcion.trim();if(!form.origen_comprobante_id)return void(error.value='Debe seleccionar un origen de comprobante.');if(nombre.length<2||nombre.length>45)return void(error.value='El nombre debe tener entre 2 y 45 caracteres.');if(descripcion.length>100)return void(error.value='La descripción no puede superar los 100 caracteres.');saving.value=true;error.value='';try{await guardarInductor(editing.value,{nombre:nombre.toUpperCase(),descripcion:descripcion.toUpperCase(),origen_comprobante_id:form.origen_comprobante_id});modal.value=false;success.value=`Inductor ${editing.value?'actualizado':'registrado'} correctamente.`;await load(editing.value?page.value:1)}catch(v){error.value=message(v)}finally{saving.value=false}}
async function toggle(item:Inductor){if(!confirm(`¿Desea ${item.activo?'desactivar':'activar'} el inductor ${item.nombre}?`))return;try{await cambiarEstadoInductor(item.id);success.value='Estado actualizado correctamente.';await load(page.value)}catch(v){error.value=message(v)}}
onMounted(()=>load())
</script>
<template><div class="page" style="--a:#268c86"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/contabilidad">Contabilidad</RouterLink> / <RouterLink to="/modulos/administracion/contabilidad/parametros-costos">Parámetros de costos</RouterLink> / Inductores</nav><header class="hero"><div class="mark">IN</div><div><small>MIA · CONTABILIDAD · COSTOS</small><h1>Inductores</h1><p>Define los factores empleados para asignar y distribuir los costos institucionales.</p></div><strong>{{total}} registros</strong><button @click="open()">+ Nuevo inductor</button></header><p v-if="success" class="flash success">✓ {{success}}</p><p v-if="error" class="flash error">{{error}}</p><form class="filters" @submit.prevent="load(1)"><input v-model.trim="criterio" placeholder="Buscar por nombre o descripción"><button>Buscar</button><button type="button" class="soft" @click="criterio='';load(1)">Limpiar</button></form><section class="table-card"><div v-if="loading" class="empty">Consultando inductores…</div><div v-else-if="!rows.length" class="empty">No se encontraron inductores.</div><div v-else class="scroll"><table><thead><tr><th>ID</th><th>Nombre</th><th>Descripción</th><th>Origen de comprobante</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><tr v-for="item in rows" :key="item.id"><td>#{{item.id}}</td><td><b>{{item.nombre}}</b></td><td>{{item.descripcion||'—'}}</td><td>{{item.origen_comprobante?.nombre||'—'}}</td><td><span :class="item.activo?'ok':'bad'">{{item.activo?'Activo':'Inactivo'}}</span></td><td class="actions"><button class="edit" @click="open(item)">Editar</button><button class="soft" @click="toggle(item)">{{item.activo?'Desactivar':'Activar'}}</button></td></tr></tbody></table></div><footer v-if="lastPage>1"><button :disabled="page<=1" @click="load(page-1)">Anterior</button><span>{{page}} / {{lastPage}}</span><button :disabled="page>=lastPage" @click="load(page+1)">Siguiente</button></footer></section><div v-if="modal" class="backdrop" @mousedown.self="modal=false"><form class="dialog" @submit.prevent="save"><header><div><small>PARÁMETROS DE COSTOS</small><h2>{{editing?'Editar':'Nuevo'}} inductor</h2></div><button type="button" @click="modal=false">×</button></header><label>Origen de comprobante *<select v-model.number="form.origen_comprobante_id" required><option :value="0">Seleccione</option><option v-for="item in origenes" :key="item.id" :value="item.id">{{item.nombre}}</option></select></label><label>Nombre *<input v-model="form.nombre" required minlength="2" maxlength="45" @input="form.nombre=form.nombre.toUpperCase()"></label><label>Descripción<input v-model="form.descripcion" maxlength="100" @input="form.descripcion=form.descripcion.toUpperCase()"></label><footer><button type="button" class="soft" @click="modal=false">Cancelar</button><button :disabled="saving">{{saving?'Guardando…':'Guardar'}}</button></footer></form></div></div></template>
<style scoped src="./costCrud.css"></style>
