<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { cambiarEstadoProceso, guardarProceso, listarProcesos } from '../services/procesos'
import type { MacroProcesoOption, Proceso, ProcesoPayload } from '../interfaces/proceso.interface'
const rows=ref<Proceso[]>([]),macroprocesos=ref<MacroProcesoOption[]>([]),criterio=ref(''),page=ref(1),lastPage=ref(1),total=ref(0),loading=ref(false),saving=ref(false),error=ref(''),success=ref(''),modal=ref(false),editing=ref<number|null>(null)
const form=reactive<ProcesoPayload>({nombre:'',descripcion:'',macro_proceso_id:0})
const message=(v:unknown)=>v instanceof Error?v.message:'No se pudo completar la operación.'
async function load(next=1){loading.value=true;error.value='';try{const r=await listarProcesos(criterio.value,next);rows.value=r.data;macroprocesos.value=r.macroprocesos??[];page.value=r.current_page;lastPage.value=r.last_page;total.value=r.total}catch(v){error.value=message(v)}finally{loading.value=false}}
function open(item?:Proceso){editing.value=item?.id??null;form.nombre=item?.nombre??'';form.descripcion=item?.descripcion??'';form.macro_proceso_id=item?.macro_proceso_id??0;error.value='';modal.value=true}
async function save(){const nombre=form.nombre.trim(),descripcion=form.descripcion.trim();if(!form.macro_proceso_id)return void(error.value='Debe seleccionar un macroproceso.');if(nombre.length<2||nombre.length>45)return void(error.value='El nombre debe tener entre 2 y 45 caracteres.');if(descripcion.length>100)return void(error.value='La descripción no puede superar los 100 caracteres.');saving.value=true;error.value='';try{await guardarProceso(editing.value,{nombre:nombre.toUpperCase(),descripcion:descripcion.toUpperCase(),macro_proceso_id:form.macro_proceso_id});modal.value=false;success.value=`Proceso ${editing.value?'actualizado':'registrado'} correctamente.`;await load(editing.value?page.value:1)}catch(v){error.value=message(v)}finally{saving.value=false}}
async function toggle(item:Proceso){if(!confirm(`¿Desea ${item.activo?'desactivar':'activar'} el proceso ${item.nombre}?`))return;try{await cambiarEstadoProceso(item.id);success.value='Estado actualizado correctamente.';await load(page.value)}catch(v){error.value=message(v)}}
onMounted(()=>load())
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/contabilidad">Contabilidad</RouterLink> / <RouterLink to="/modulos/administracion/contabilidad/parametros-costos">Parámetros de costos</RouterLink> / Procesos</nav><header class="hero"><div class="mark">PR</div><div><small>MIA · CONTABILIDAD · COSTOS</small><h1>Procesos</h1><p>Administra los procesos vinculados a cada macroproceso institucional.</p></div><strong>{{total}} registros</strong><button @click="open()">+ Nuevo proceso</button></header><p v-if="success" class="flash success">✓ {{success}}</p><p v-if="error" class="flash error">{{error}}</p><form class="filters" @submit.prevent="load(1)"><input v-model.trim="criterio" placeholder="Buscar por nombre o descripción"><button>Buscar</button><button type="button" class="soft" @click="criterio='';load(1)">Limpiar</button></form><section class="table-card"><div v-if="loading" class="empty">Consultando procesos…</div><div v-else-if="!rows.length" class="empty">No se encontraron procesos.</div><div v-else class="scroll"><table><thead><tr><th>ID</th><th>Nombre</th><th>Descripción</th><th>Macroproceso</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><tr v-for="item in rows" :key="item.id"><td>#{{item.id}}</td><td><b>{{item.nombre}}</b></td><td>{{item.descripcion||'—'}}</td><td>{{item.macro_proceso?.nombre||'—'}}</td><td><span :class="item.activo?'ok':'bad'">{{item.activo?'Activo':'Inactivo'}}</span></td><td class="actions"><button class="edit" @click="open(item)">Editar</button><button class="soft" @click="toggle(item)">{{item.activo?'Desactivar':'Activar'}}</button></td></tr></tbody></table></div><footer v-if="lastPage>1"><button :disabled="page<=1" @click="load(page-1)">Anterior</button><span>{{page}} / {{lastPage}}</span><button :disabled="page>=lastPage" @click="load(page+1)">Siguiente</button></footer></section><div v-if="modal" class="backdrop" @mousedown.self="modal=false"><form class="dialog" @submit.prevent="save"><header><div><small>PARÁMETROS DE COSTOS</small><h2>{{editing?'Editar':'Nuevo'}} proceso</h2></div><button type="button" @click="modal=false">×</button></header><label>Macroproceso *<select v-model.number="form.macro_proceso_id" required><option :value="0">Seleccione</option><option v-for="item in macroprocesos" :key="item.id" :value="item.id">{{item.nombre}}</option></select></label><label>Nombre *<input v-model="form.nombre" required minlength="2" maxlength="45" @input="form.nombre=form.nombre.toUpperCase()"></label><label>Descripción<input v-model="form.descripcion" maxlength="100" @input="form.descripcion=form.descripcion.toUpperCase()"></label><footer><button type="button" class="soft" @click="modal=false">Cancelar</button><button :disabled="saving">{{saving?'Guardando…':'Guardar'}}</button></footer></form></div></div></template>
<style scoped>
.page{--a:#32936f;color:#35464e}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--a);text-decoration:none}.hero{padding:20px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:48px;height:48px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero small,.dialog small{color:var(--a);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.3rem}.hero p{margin:0;color:#7e8a90;font-size:.67rem}.hero strong{margin-left:auto;font-size:.55rem}.hero button,.filters button,.table-card footer button,.dialog button{padding:9px 12px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.52rem}.flash{padding:9px;border-radius:7px;font-size:.6rem}.success{color:#287052;background:#edf9f3}.error{color:#a64046;background:#fff0f0}.filters{margin-top:10px;padding:13px;display:flex;gap:7px;background:#fff}.filters input,.dialog input,.dialog select{width:100%;box-sizing:border-box;padding:9px;border:1px solid #d7dfe2;border-radius:6px;font:inherit;font-size:.55rem;background:#fff}.filters input{margin-right:auto}.soft{color:#64727a!important;background:#edf1f3!important}.table-card{margin-top:10px;background:#fff;overflow:hidden}.scroll{overflow:auto}table{width:100%;min-width:760px;border-collapse:collapse;font-size:.52rem}th,td{padding:10px;border-bottom:1px solid #e8ecee;text-align:left}th{color:#fff;background:#4c627e}.ok,.bad{padding:4px 7px;border-radius:10px;font-size:.43rem}.ok{color:#287154;background:#e6f7ee}.bad{color:#9d4046;background:#fdebed}.actions{display:flex;gap:4px}.actions button{padding:6px;border:0;border-radius:5px;font-size:.44rem}.edit{color:var(--a);background:#e8eff8}.empty{padding:45px;text-align:center}.table-card>footer{padding:10px;display:flex;justify-content:center;align-items:center;gap:9px}.backdrop{position:fixed;z-index:100;inset:0;padding:20px;display:grid;place-items:center;background:#172b3d88}.dialog{width:min(560px,100%);padding:20px;box-sizing:border-box;border-radius:12px;background:#fff}.dialog>header{display:flex;justify-content:space-between}.dialog h2{margin:3px 0 14px;font-size:.9rem}.dialog>header button{color:#59666c;background:none;font-size:1.1rem}.dialog label{display:grid;margin-top:10px;gap:5px;font-size:.5rem}.dialog footer{margin-top:16px;display:flex;justify-content:flex-end;gap:6px}@media(max-width:720px){.hero,.filters{flex-wrap:wrap}.hero strong{margin-left:0}}
</style>
