<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { cambiarEstadoQuiebreCuenta, guardarQuiebreCuenta, listarQuiebresCuenta } from '../services/quiebresCuenta'
import type { QuiebreCuenta, QuiebreCuentaPayload } from '../interfaces/quiebresCuenta.interface'
const rows=ref<QuiebreCuenta[]>([]),criterio=ref(''),page=ref(1),lastPage=ref(1),total=ref(0),loading=ref(false),saving=ref(false),error=ref(''),success=ref(''),modal=ref(false),editing=ref<number|null>(null),form=reactive<QuiebreCuentaPayload>({posicion:1,descripcion:''})
const message=(v:unknown)=>v instanceof Error?v.message:'No se pudo completar la operación.'
async function load(next=1){loading.value=true;error.value='';try{const r=await listarQuiebresCuenta(criterio.value,next);rows.value=r.data;page.value=r.current_page;lastPage.value=r.last_page;total.value=r.total}catch(v){error.value=message(v)}finally{loading.value=false}}
function open(item?:QuiebreCuenta){editing.value=item?.id??null;form.posicion=item?.posicion??1;form.descripcion=item?.descripcion??'';error.value='';modal.value=true}
async function save(){const descripcion=form.descripcion.trim();if(!Number.isInteger(form.posicion)||form.posicion<1||form.posicion>127)return void(error.value='La posición debe ser un entero entre 1 y 127.');if(descripcion.length<3||descripcion.length>50)return void(error.value='La descripción debe tener entre 3 y 50 caracteres.');saving.value=true;try{await guardarQuiebreCuenta(editing.value,{posicion:form.posicion,descripcion:descripcion.toUpperCase()});modal.value=false;success.value=`Quiebre ${editing.value?'actualizado':'registrado'} correctamente.`;await load(editing.value?page.value:1)}catch(v){error.value=message(v)}finally{saving.value=false}}
async function toggle(item:QuiebreCuenta){if(!confirm(`¿Desea ${item.activo?'desactivar':'activar'} el quiebre de la posición ${item.posicion}?`))return;try{await cambiarEstadoQuiebreCuenta(item.id);success.value='Estado actualizado correctamente.';await load(page.value)}catch(v){error.value=message(v)}}
onMounted(()=>load())
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/contabilidad">Contabilidad</RouterLink> / Quiebre de cuentas</nav><header class="hero"><div class="mark">QC</div><div><small>MIA · CONTABILIDAD · MAESTROS</small><h1>Quiebre de cuentas</h1><p>Configura las posiciones de corte utilizadas para segmentar cuentas contables.</p></div><strong>{{total}} posiciones</strong><button @click="open()">+ Nuevo quiebre</button></header><p v-if="success" class="flash success">✓ {{success}}</p><p v-if="error" class="flash error">{{error}}</p><form class="filters" @submit.prevent="load(1)"><input v-model.trim="criterio" placeholder="Buscar por descripción"><button>Buscar</button><button type="button" class="soft" @click="criterio='';load(1)">Limpiar</button></form><section class="table-card"><div v-if="loading" class="empty">Consultando quiebres…</div><div v-else-if="!rows.length" class="empty">No se encontraron quiebres de cuenta.</div><div v-else class="scroll"><table><thead><tr><th>Posición</th><th>Descripción</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><tr v-for="item in rows" :key="item.id"><td><b>#{{item.posicion}}</b></td><td>{{item.descripcion}}</td><td><span :class="item.activo?'ok':'bad'">{{item.activo?'Activo':'Inactivo'}}</span></td><td class="actions"><button class="edit" @click="open(item)">Editar</button><button class="soft" @click="toggle(item)">Estado</button></td></tr></tbody></table></div><footer v-if="lastPage>1"><button :disabled="page<=1" @click="load(page-1)">Anterior</button><span>{{page}} / {{lastPage}}</span><button :disabled="page>=lastPage" @click="load(page+1)">Siguiente</button></footer></section><div v-if="modal" class="backdrop" @mousedown.self="modal=false"><form class="dialog" @submit.prevent="save"><header><div><small>QUIEBRE DE CUENTA</small><h2>{{editing?'Editar':'Nuevo'}} quiebre</h2></div><button type="button" @click="modal=false">×</button></header><label>Posición *<input v-model.number="form.posicion" type="number" min="1" max="127"><small>Número de orden único entre 1 y 127.</small></label><label>Descripción *<input v-model="form.descripcion" minlength="3" maxlength="50" @input="form.descripcion=form.descripcion.toUpperCase()"></label><footer><button type="button" class="soft" @click="modal=false">Cancelar</button><button :disabled="saving">Guardar</button></footer></form></div></div></template>
<style scoped>
.page{--a:#385d8a;color:#35464e}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--a);text-decoration:none}.hero{padding:20px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:48px;height:48px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-weight:800}.hero small,.dialog>header small{color:var(--a);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.3rem}.hero p{margin:0;color:#7e8a90;font-size:.67rem}.hero strong{margin-left:auto;font-size:.55rem}.hero button,.filters button,.table-card footer button,.dialog button{padding:9px 12px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.52rem}.flash{padding:9px;border-radius:7px;font-size:.6rem}.success{color:#287052;background:#edf9f3}.error{color:#a64046;background:#fff0f0}.filters{margin-top:10px;padding:13px;display:flex;gap:7px;background:#fff}.filters input,.dialog input{width:100%;box-sizing:border-box;padding:9px;border:1px solid #d7dfe2;border-radius:6px;font:inherit;font-size:.55rem}.filters input{margin-right:auto}.soft{color:#64727a!important;background:#edf1f3!important}.table-card{margin-top:10px;background:#fff;overflow:hidden}.scroll{overflow:auto}table{width:100%;min-width:650px;border-collapse:collapse;font-size:.52rem}th,td{padding:10px;border-bottom:1px solid #e8ecee;text-align:left}th{color:#fff;background:#4c627e}.ok,.bad{padding:4px 7px;border-radius:10px;font-size:.43rem}.ok{color:#287154;background:#e6f7ee}.bad{color:#9d4046;background:#fdebed}.actions{display:flex;gap:4px}.actions button{padding:6px;border:0;border-radius:5px;font-size:.44rem}.edit{color:#385d8a;background:#e8eff8}.empty{padding:45px;text-align:center}.table-card>footer{padding:10px;display:flex;justify-content:center;gap:9px}.backdrop{position:fixed;z-index:100;inset:0;padding:20px;display:grid;place-items:center;background:#172b3d88}.dialog{width:min(520px,100%);padding:20px;box-sizing:border-box;border-radius:12px;background:#fff}.dialog>header{display:flex;justify-content:space-between}.dialog h2{margin:3px 0 14px;font-size:.9rem}.dialog>header button{color:#59666c;background:none;font-size:1.1rem}.dialog label{display:grid;margin-top:10px;gap:5px;font-size:.5rem}.dialog label small{color:#849096;font-size:.44rem}.dialog footer{margin-top:16px;display:flex;justify-content:flex-end;gap:6px}@media(max-width:720px){.hero,.filters{flex-wrap:wrap}}
</style>
