<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { cambiarEstadoSucursal, guardarSucursal, listarDistritosSucursal, listarSucursales } from '../services/sucursales'
import type { DistritoSucursalOption, NivelSucursal, SucursalContable, SucursalContablePayload } from '../interfaces/sucursales.interface'
const rows=ref<SucursalContable[]>([]),distritos=ref<DistritoSucursalOption[]>([]),criterio=ref(''),page=ref(1),lastPage=ref(1),total=ref(0),loading=ref(false),saving=ref(false),error=ref(''),success=ref(''),modal=ref(false),editing=ref<number|null>(null)
const hoy=()=>new Date().toISOString().slice(0,10)
const form=reactive<SucursalContablePayload>({distrito_id:0,nombre:'',fecha_contable:hoy(),nivel:'L'})
const niveles:{value:NivelSucursal;label:string}[]=[{value:'E',label:'Empresa'},{value:'Z',label:'Zonal'},{value:'L',label:'Local'}]
const message=(value:unknown)=>value instanceof Error?value.message:'No se pudo completar la operación.'
const nivelLabel=(value:NivelSucursal)=>niveles.find(item=>item.value===value)?.label??value
const formatDate=(value:string)=>value?new Intl.DateTimeFormat('es-PE',{timeZone:'UTC'}).format(new Date(`${value.slice(0,10)}T00:00:00Z`)):'N/D'
async function load(next=1){loading.value=true;error.value='';try{const response=await listarSucursales(criterio.value,next);rows.value=response.data;page.value=response.current_page;lastPage.value=response.last_page;total.value=response.total}catch(value){error.value=message(value)}finally{loading.value=false}}
async function options(){try{distritos.value=await listarDistritosSucursal()}catch(value){error.value=message(value)}}
function open(item?:SucursalContable){editing.value=item?.id??null;form.distrito_id=item?.distrito_id??0;form.nombre=item?.nombre??'';form.fecha_contable=item?.fecha_contable?.slice(0,10)??hoy();form.nivel=item?.nivel??'L';error.value='';modal.value=true}
async function save(){const nombre=form.nombre.trim();if(nombre.length<2||nombre.length>45)return void(error.value='El nombre debe tener entre 2 y 45 caracteres.');if(!form.distrito_id)return void(error.value='Seleccione un distrito.');if(!form.fecha_contable)return void(error.value='Ingrese la fecha contable.');saving.value=true;try{await guardarSucursal(editing.value,{...form,nombre:nombre.toUpperCase()});modal.value=false;success.value=`Sucursal ${editing.value?'actualizada':'registrada'} correctamente.`;await load(editing.value?page.value:1)}catch(value){error.value=message(value)}finally{saving.value=false}}
async function toggle(item:SucursalContable){if(!confirm(`¿Desea ${item.estado?'desactivar':'activar'} la sucursal ${item.nombre}?`))return;try{await cambiarEstadoSucursal(item.id);success.value='Estado actualizado correctamente.';await load(page.value)}catch(value){error.value=message(value)}}
onMounted(()=>{void load();void options()})
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/contabilidad">Contabilidad</RouterLink> / Sucursales</nav><header class="hero"><div class="mark">SU</div><div><small>MIA · CONTABILIDAD · MAESTROS</small><h1>Sucursales</h1><p>Administra las sedes y su fecha operativa para los procesos contables.</p></div><strong>{{total}} sucursales</strong><button @click="open()">+ Nueva sucursal</button></header><p v-if="success" class="flash success">✓ {{success}}</p><p v-if="error" class="flash error">{{error}}</p><form class="filters" @submit.prevent="load(1)"><input v-model.trim="criterio" placeholder="Buscar por nombre o nivel"><button>Buscar</button><button type="button" class="soft" @click="criterio='';load(1)">Limpiar</button></form><section class="table-card"><div v-if="loading" class="empty">Consultando sucursales…</div><div v-else-if="!rows.length" class="empty">No se encontraron sucursales.</div><div v-else class="scroll"><table><thead><tr><th>Nombre</th><th>Distrito</th><th>Nivel</th><th>Fecha contable</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><tr v-for="item in rows" :key="item.id"><td><b>{{item.nombre}}</b></td><td>{{item.distrito_nombre||distritos.find(d=>d.id===item.distrito_id)?.nombre||'N/D'}}</td><td>{{nivelLabel(item.nivel)}}</td><td>{{formatDate(item.fecha_contable)}}</td><td><span :class="item.estado?'ok':'bad'">{{item.estado?'Activo':'Inactivo'}}</span></td><td class="actions"><button class="edit" @click="open(item)">Editar</button><button class="soft" @click="toggle(item)">{{item.estado?'Desactivar':'Activar'}}</button></td></tr></tbody></table></div><footer v-if="lastPage>1"><button :disabled="page<=1" @click="load(page-1)">Anterior</button><span>{{page}} / {{lastPage}}</span><button :disabled="page>=lastPage" @click="load(page+1)">Siguiente</button></footer></section><div v-if="modal" class="backdrop" @mousedown.self="modal=false"><form class="dialog" @submit.prevent="save"><header><div><small>SUCURSAL</small><h2>{{editing?'Editar':'Nueva'}} sucursal</h2></div><button type="button" @click="modal=false">×</button></header><label>Nombre *<input v-model="form.nombre" minlength="2" maxlength="45" @input="form.nombre=form.nombre.toUpperCase()"></label><label>Distrito *<select v-model="form.distrito_id"><option :value="0">Seleccione…</option><option v-for="option in distritos" :key="option.id" :value="option.id">{{option.nombre}}</option></select></label><div class="grid"><label>Nivel *<select v-model="form.nivel"><option v-for="option in niveles" :key="option.value" :value="option.value">{{option.label}}</option></select></label><label>Fecha contable *<input v-model="form.fecha_contable" type="date"></label></div><footer><button type="button" class="soft" @click="modal=false">Cancelar</button><button :disabled="saving">Guardar</button></footer></form></div></div></template>
<style scoped>
.page{--a:#385d8a;color:#35464e}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--a);text-decoration:none}.hero{padding:20px 23px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--a);border-radius:12px;background:#fff}.mark{width:48px;height:48px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--a);font-size:.65rem;font-weight:800}.hero small,.dialog small{color:var(--a);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.3rem}.hero p{margin:0;color:#7e8a90;font-size:.67rem}.hero strong{margin-left:auto;color:var(--a);font-size:.55rem}.hero button,.filters button,.table-card footer button,.dialog button{padding:9px 12px;border:0;border-radius:6px;color:#fff;background:var(--a);font-size:.52rem}.flash{padding:9px;border-radius:7px;font-size:.6rem}.success{color:#287052;background:#edf9f3}.error{color:#a64046;background:#fff0f0}.filters{margin-top:10px;padding:13px;display:flex;gap:7px;border-radius:9px;background:#fff}.filters input,.dialog input,.dialog select{width:100%;box-sizing:border-box;padding:9px;border:1px solid #d7dfe2;border-radius:6px;font:inherit;font-size:.55rem}.filters input{margin-right:auto}.soft{color:#64727a!important;background:#edf1f3!important}.table-card{margin-top:10px;border-radius:10px;background:#fff;overflow:hidden}.scroll{overflow:auto}table{width:100%;min-width:850px;border-collapse:collapse;font-size:.53rem}th,td{padding:10px;border-bottom:1px solid #e8ecee;text-align:left}th{color:#fff;background:#4c627e}.ok,.bad{padding:4px 7px;border-radius:10px;font-size:.43rem}.ok{color:#287154;background:#e6f7ee}.bad{color:#9d4046;background:#fdebed}.actions{display:flex;gap:4px}.actions button{padding:6px 7px;border:0;border-radius:5px;font-size:.45rem}.edit{color:#385d8a;background:#e8eff8}.empty{padding:45px;text-align:center;font-size:.6rem}.table-card>footer{padding:10px;display:flex;justify-content:center;align-items:center;gap:9px;font-size:.52rem}.backdrop{position:fixed;z-index:100;inset:0;padding:20px;display:grid;place-items:center;background:#172b3d88}.dialog{width:min(560px,100%);padding:20px;box-sizing:border-box;border-radius:12px;background:#fff}.dialog header{display:flex;justify-content:space-between}.dialog h2{margin:3px 0 15px;font-size:.9rem}.dialog header button{color:#59666c;background:none;font-size:1.1rem}.dialog label{display:grid;margin-top:10px;font-size:.52rem}.dialog input,.dialog select{margin-top:5px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.dialog footer{margin-top:17px;display:flex;justify-content:flex-end;gap:6px}@media(max-width:720px){.hero,.filters{flex-wrap:wrap}.hero strong{margin-left:0}.filters input{flex-basis:100%}.grid{grid-template-columns:1fr}}
</style>
