<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { cambiarEstadoTipoDocumento, guardarTipoDocumento, listarTiposComprobanteActivos, listarTiposDocumento } from '../services/tiposDocumento'
import type { TipoComprobanteOption, TipoDocumentoContable, TipoDocumentoContablePayload } from '../interfaces/tiposDocumento.interface'

const rows=ref<TipoDocumentoContable[]>([]),comprobantes=ref<TipoComprobanteOption[]>([]),criterio=ref(''),page=ref(1),lastPage=ref(1),total=ref(0),loading=ref(false),saving=ref(false),error=ref(''),success=ref(''),modal=ref(false),editing=ref<number|null>(null)
const form=reactive<TipoDocumentoContablePayload>({nombre:'',tipo_comprobante_id:0,diminutivo:''})
const message=(value:unknown)=>value instanceof Error?value.message:'No se pudo completar la operación.'
async function load(next=1){loading.value=true;error.value='';try{const response=await listarTiposDocumento(criterio.value,next);rows.value=response.data;page.value=response.current_page;lastPage.value=response.last_page;total.value=response.total}catch(value){error.value=message(value)}finally{loading.value=false}}
async function loadOptions(){try{comprobantes.value=await listarTiposComprobanteActivos()}catch(value){error.value=message(value)}}
function open(item?:TipoDocumentoContable){editing.value=item?.id??null;form.nombre=item?.nombre??'';form.tipo_comprobante_id=item?.tipo_comprobante_id??0;form.diminutivo=item?.diminutivo??'';error.value='';modal.value=true}
async function save(){const nombre=form.nombre.trim(),diminutivo=form.diminutivo.trim();if(nombre.length<2||nombre.length>45)return void(error.value='El nombre debe tener entre 2 y 45 caracteres.');if(!form.tipo_comprobante_id)return void(error.value='Seleccione el tipo de comprobante.');if(!diminutivo||diminutivo.length>5)return void(error.value='El diminutivo es obligatorio y admite hasta 5 caracteres.');saving.value=true;try{await guardarTipoDocumento(editing.value,{nombre:nombre.toUpperCase(),tipo_comprobante_id:form.tipo_comprobante_id,diminutivo:diminutivo.toUpperCase()});modal.value=false;success.value=`Tipo de documento ${editing.value?'actualizado':'registrado'} correctamente.`;await load(editing.value?page.value:1)}catch(value){error.value=message(value)}finally{saving.value=false}}
async function toggle(item:TipoDocumentoContable){if(!confirm(`¿Desea ${item.estado?'desactivar':'activar'} el tipo de documento ${item.nombre}?`))return;try{await cambiarEstadoTipoDocumento(item.id);success.value='Estado actualizado correctamente.';await load(page.value)}catch(value){error.value=message(value)}}
onMounted(()=>{void load();void loadOptions()})
</script>

<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / <RouterLink to="/modulos/administracion/contabilidad">Contabilidad</RouterLink> / Tipos de documento</nav><header class="hero"><div class="mark">TD</div><div><small>MIA · CONTABILIDAD · MAESTROS</small><h1>Tipos de documento</h1><p>Administra los documentos asociados a los tipos de comprobante contable.</p></div><strong>{{total}} registros</strong><button @click="open()">+ Nuevo tipo</button></header><p v-if="success" class="flash success">✓ {{success}}</p><p v-if="error" class="flash error">{{error}}</p><form class="filters" @submit.prevent="load(1)"><input v-model.trim="criterio" placeholder="Buscar por nombre o diminutivo"><button>Buscar</button><button type="button" class="soft" @click="criterio='';load(1)">Limpiar</button></form><section class="table-card"><div v-if="loading" class="empty">Consultando tipos de documento…</div><div v-else-if="!rows.length" class="empty">No se encontraron tipos de documento.</div><div v-else class="scroll"><table><thead><tr><th>Nombre</th><th>Comprobante</th><th>Diminutivo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><tr v-for="item in rows" :key="item.id"><td><b>{{item.nombre}}</b></td><td>{{item.tipo_comprobante?.nombre||'N/D'}}</td><td><code>{{item.diminutivo}}</code></td><td><span :class="item.estado?'ok':'bad'">{{item.estado?'Activo':'Inactivo'}}</span></td><td class="actions"><button class="edit" @click="open(item)">Editar</button><button class="soft" @click="toggle(item)">{{item.estado?'Desactivar':'Activar'}}</button></td></tr></tbody></table></div><footer v-if="lastPage>1"><button :disabled="page<=1" @click="load(page-1)">Anterior</button><span>{{page}} / {{lastPage}}</span><button :disabled="page>=lastPage" @click="load(page+1)">Siguiente</button></footer></section><div v-if="modal" class="backdrop" @mousedown.self="modal=false"><form class="dialog" @submit.prevent="save"><header><div><small>TIPO DE DOCUMENTO</small><h2>{{editing?'Editar':'Nuevo'}} tipo de documento</h2></div><button type="button" @click="modal=false">×</button></header><label>Nombre *<input v-model="form.nombre" minlength="2" maxlength="45" @input="form.nombre=form.nombre.toUpperCase()"></label><label>Tipo de comprobante *<select v-model="form.tipo_comprobante_id"><option :value="0">Seleccione…</option><option v-for="option in comprobantes" :key="option.id" :value="option.id">{{option.nombre}}</option></select></label><label>Diminutivo *<input v-model="form.diminutivo" maxlength="5" @input="form.diminutivo=form.diminutivo.toUpperCase()"></label><footer><button type="button" class="soft" @click="modal=false">Cancelar</button><button :disabled="saving">Guardar</button></footer></form></div></div></template>

<style scoped>
.page{--accent:#385d8a;color:#35464e}nav{margin-bottom:16px;color:#929fa5;font-size:.68rem}nav a{color:var(--accent);text-decoration:none}.hero{padding:20px 23px;display:flex;align-items:center;gap:14px;border-left:5px solid var(--accent);border-radius:12px;background:#fff}.mark{width:48px;height:48px;display:grid;place-items:center;border-radius:10px;color:#fff;background:var(--accent);font-size:.65rem;font-weight:800}.hero small,.dialog small{color:var(--accent);font-size:.48rem;font-weight:800}.hero h1{margin:2px 0;font-size:1.3rem}.hero p{margin:0;color:#7e8a90;font-size:.67rem}.hero strong{margin-left:auto;color:var(--accent);font-size:.55rem}.hero button,.filters button,.table-card footer button,.dialog button{padding:9px 12px;border:0;border-radius:6px;color:#fff;background:var(--accent);font-size:.52rem}.flash{padding:9px;border-radius:7px;font-size:.6rem}.success{color:#287052;background:#edf9f3}.error{color:#a64046;background:#fff0f0}.filters{margin-top:10px;padding:13px;display:flex;gap:7px;border-radius:9px;background:#fff}.filters input,.dialog input,.dialog select{width:100%;box-sizing:border-box;padding:9px;border:1px solid #d7dfe2;border-radius:6px;font:inherit;font-size:.55rem}.filters input{margin-right:auto}.soft{color:#64727a!important;background:#edf1f3!important}.table-card{margin-top:10px;border-radius:10px;background:#fff;overflow:hidden}.scroll{overflow:auto}table{width:100%;min-width:780px;border-collapse:collapse;font-size:.53rem}th,td{padding:10px;border-bottom:1px solid #e8ecee;text-align:left}th{color:#fff;background:#4c627e}code{font-size:.5rem}.ok,.bad{padding:4px 7px;border-radius:10px;font-size:.43rem}.ok{color:#287154;background:#e6f7ee}.bad{color:#9d4046;background:#fdebed}.actions{display:flex;gap:4px}.actions button{padding:6px 7px;border:0;border-radius:5px;font-size:.45rem}.edit{color:#385d8a;background:#e8eff8}.empty{padding:45px;text-align:center;font-size:.6rem}.table-card>footer{padding:10px;display:flex;justify-content:center;align-items:center;gap:9px;font-size:.52rem}.backdrop{position:fixed;z-index:100;inset:0;padding:20px;display:grid;place-items:center;background:#172b3d88}.dialog{width:min(520px,100%);padding:20px;box-sizing:border-box;border-radius:12px;background:#fff}.dialog header{display:flex;justify-content:space-between}.dialog h2{margin:3px 0 15px;font-size:.9rem}.dialog header button{color:#59666c;background:none;font-size:1.1rem}.dialog label{display:grid;margin-top:10px;font-size:.52rem}.dialog input,.dialog select{margin-top:5px}.dialog footer{margin-top:17px;display:flex;justify-content:flex-end;gap:6px}@media(max-width:720px){.hero,.filters{flex-wrap:wrap}.hero strong{margin-left:0}.filters input{flex-basis:100%}}
</style>
