<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { dashboard, exportar } from '../services/comunicaciones'
import type { DashboardData } from '../interfaces/comunicaciones.interface'
const now=new Date(),filters=reactive({desde:`${now.getFullYear()}-01-01`,hasta:now.toISOString().slice(0,10)}),data=ref<DashboardData|null>(null),loading=ref(false),error=ref('')
async function load(){loading.value=true;error.value='';try{data.value=await dashboard(filters.desde,filters.hasta)}catch(cause){error.value=cause instanceof Error?cause.message:'No se pudo cargar el dashboard.'}finally{loading.value=false}}
function max(items:Array<{total:number}>){return Math.max(...items.map(x=>x.total),1)}onMounted(load)
</script>
<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / Institucional / Comunicaciones / Dashboard</nav><header class="hero"><div class="mark">COM</div><div><small>AURA · Comunicaciones</small><h1>Dashboard de comunicaciones</h1><p>Indicadores consolidados de la gestión institucional.</p></div><button @click="exportar('noticias')">Reporte de noticias</button></header><section class="filters"><label>Desde<input v-model="filters.desde" type="date"></label><label>Hasta<input v-model="filters.hasta" type="date"></label><button @click="load">Actualizar</button></section><p v-if="error" class="error">{{error}}</p><div v-if="loading" class="empty">Procesando indicadores…</div><template v-else-if="data"><section class="kpis"><article><small>Noticias</small><b>{{data.totales.noticias}}</b></article><article><small>Publicaciones</small><b>{{data.totales.publicaciones}}</b></article><article><small>Stakeholders</small><b>{{data.totales.stakeholders}}</b></article><article><small>Reuniones</small><b>{{data.totales.reuniones}}</b></article><article><small>Acuerdos</small><b>{{data.totales.acuerdos}}</b></article></section><section class="panels"><article><h2>Noticias por temática</h2><div v-for="item in data.tematicas" :key="item.nombre" class="bar"><span>{{item.nombre}}</span><i><b :style="{width:`${item.total*100/max(data.tematicas)}%`}"></b></i><em>{{item.total}}</em></div></article><article><h2>Noticias por medio</h2><div v-for="item in data.medios" :key="item.nombre" class="bar"><span>{{item.nombre}}</span><i><b :style="{width:`${item.total*100/max(data.medios)}%`}"></b></i><em>{{item.total}}</em></div></article><article><h2>Estado de comunicaciones</h2><div v-for="item in data.estados" :key="item.nombre" class="bar"><span>{{item.nombre}}</span><i><b :style="{width:`${item.total*100/max(data.estados)}%`}"></b></i><em>{{item.total}}</em></div></article></section></template></div></template>
<style scoped>
.page{--accent:#7257c8;color:#35464e}nav{margin-bottom:17px;color:#98a4aa;font-size:.7rem}nav a{color:var(--accent);text-decoration:none}.hero{padding:22px 25px;display:flex;align-items:center;gap:15px;border-left:5px solid var(--accent);border-radius:13px;background:#fff}.mark{width:52px;height:52px;display:grid;place-items:center;border-radius:11px;color:#fff;background:var(--accent);font-size:.62rem;font-weight:700}.hero small,.kpis small{color:var(--accent);font-size:.55rem;font-weight:700;text-transform:uppercase}.hero h1{margin:2px 0;font-size:1.35rem}.hero p{margin:0;color:#7d898f;font-size:.7rem}.hero button,.filters button{margin-left:auto;padding:8px 11px;border:0;border-radius:6px;color:#fff;background:var(--accent);font-size:.59rem}.filters{margin-top:14px;padding:12px;display:flex;align-items:end;gap:9px;border-radius:9px;background:#fff}.filters label{font-size:.57rem}.filters input{display:block;margin-top:4px;padding:7px;border:1px solid #d9e0e4;border-radius:6px}.filters button{margin-left:0}.kpis{margin-top:13px;display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.kpis article{padding:14px;border:1px solid #e1e5e8;border-top:3px solid var(--accent);border-radius:8px;background:#fff}.kpis b{display:block;margin-top:5px;font-size:1.35rem}.panels{margin-top:12px;display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.panels>article{padding:15px;border:1px solid #e1e5e8;border-radius:9px;background:#fff}.panels h2{font-size:.7rem}.bar{margin:10px 0;display:grid;grid-template-columns:90px 1fr 25px;align-items:center;gap:6px;font-size:.52rem}.bar i{height:7px;border-radius:4px;background:#eceff1}.bar i b{height:100%;display:block;border-radius:4px;background:var(--accent)}.bar em{font-style:normal;text-align:right}.error,.empty{margin-top:12px;padding:30px;text-align:center;border-radius:8px;background:#fff;font-size:.64rem}.error{color:#a13f43;background:#fff0f0}@media(max-width:850px){.kpis{grid-template-columns:repeat(2,1fr)}.panels{grid-template-columns:1fr}.hero{flex-wrap:wrap}.hero button{margin-left:0}}
</style>
