<script setup lang="ts">
import{computed,onMounted,ref}from'vue'
import{descargarCopia,listarCopias,type ArchivoBackup}from'../services/copiasSeguridad'

const principal=ref<ArchivoBackup[]>([]),company=ref<ArchivoBackup[]>([]),companyName=ref('Empresa activa'),database=ref(''),updated=ref(''),query=ref(''),loading=ref(false),downloading=ref(''),error=ref(''),success=ref('')
const principalRows=computed(()=>filter(principal.value)),companyRows=computed(()=>filter(company.value)),total=computed(()=>principal.value.length+company.value.length)
function filter(rows:ArchivoBackup[]){const text=query.value.toLowerCase();return text?rows.filter(x=>x.nombre.toLowerCase().includes(text)):rows}
async function load(){loading.value=true;error.value='';try{const response=await listarCopias();principal.value=response.principal;company.value=response.empresa;companyName.value=response.empresa_nombre||'Empresa activa';database.value=response.base_empresa||'';updated.value=response.ultima_actualizacion||''}catch(e){error.value=e instanceof Error?e.message:'No se pudo consultar las copias de seguridad.'}finally{loading.value=false}}
async function download(item:ArchivoBackup){downloading.value=`${item.origen}:${item.nombre}`;error.value='';success.value='';try{await descargarCopia(item);success.value=`Se inició la descarga de ${item.nombre}.`}catch(e){error.value=e instanceof Error?e.message:'No se pudo descargar la copia de seguridad.'}finally{downloading.value=''}}
function size(item:ArchivoBackup){if(item.tamanio)return item.tamanio;if(item.tamanio_bytes===undefined)return'—';const units=['B','KB','MB','GB'];let value=item.tamanio_bytes,index=0;while(value>=1024&&index<units.length-1){value/=1024;index++}return`${value.toFixed(index?1:0)} ${units[index]}`}
function isDownloading(item:ArchivoBackup){return downloading.value===`${item.origen}:${item.nombre}`}
onMounted(load)
</script>

<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / Sistema / Administrador / Copias de seguridad</nav><header class="hero"><div class="mark">BK</div><div><small>ADMINISTRACIÓN GENERAL</small><h1>Copias de seguridad</h1><p>Respaldos disponibles de la intranet y de la empresa activa.</p></div><div class="metric"><b>{{total}}</b><span>archivos disponibles</span></div><button @click="load">Actualizar lista</button></header><div v-if="success" class="flash good">✓ {{success}}</div><div v-if="error" class="flash bad">{{error}}</div><section class="toolbar"><label>Buscar respaldo<input v-model.trim="query" placeholder="Nombre del archivo"></label><span v-if="updated">Última consulta: {{updated}}</span></section><div v-if="loading" class="empty">Consultando carpetas de respaldo…</div><template v-else><section class="backup-group principal"><header><div class="database">DB</div><div><small>INTRANET</small><h2>Base de datos principal</h2><p>Respaldo de usuarios, empresas y configuración central.</p></div><strong>{{principalRows.length}} archivos</strong></header><div v-if="!principalRows.length" class="empty inner">No hay copias disponibles.</div><article v-for="item in principalRows" :key="item.nombre"><div class="file">7Z</div><div><b>{{item.nombre}}</b><small>{{item.fecha_modificacion||'Fecha no disponible'}}</small></div><span>{{size(item)}}</span><button :disabled="!!downloading" @click="download(item)">{{isDownloading(item)?'Descargando…':'Descargar'}}</button></article></section><section class="backup-group company"><header><div class="database">DB</div><div><small>{{database||'BASE DE EMPRESA'}}</small><h2>{{companyName}}</h2><p>Respaldo operativo correspondiente a la empresa seleccionada.</p></div><strong>{{companyRows.length}} archivos</strong></header><div v-if="!companyRows.length" class="empty inner">No hay copias disponibles.</div><article v-for="item in companyRows" :key="item.nombre"><div class="file">7Z</div><div><b>{{item.nombre}}</b><small>{{item.fecha_modificacion||'Fecha no disponible'}}</small></div><span>{{size(item)}}</span><button :disabled="!!downloading" @click="download(item)">{{isDownloading(item)?'Descargando…':'Descargar'}}</button></article></section><aside><b>Acceso administrativo</b><span>Los respaldos pueden contener información sensible. Descárgalos únicamente en equipos y ubicaciones autorizadas.</span></aside></template></div></template>

<style scoped>
.page{--a:#334a61;color:#35444c}nav{margin-bottom:16px;color:#96a0a5;font-size:.7rem}nav a{color:var(--a)}.hero{padding:22px 25px;display:flex;align-items:center;gap:15px;border-left:5px solid var(--a);border-radius:13px;background:#fff}.mark{width:52px;height:52px;display:grid;place-items:center;border-radius:11px;color:#fff;background:var(--a);font-weight:800}.hero small{color:var(--a);font-size:.52rem;font-weight:700}.hero h1{margin:2px 0;font-size:1.28rem}.hero p{margin:0;color:#7c898f;font-size:.62rem}.metric{margin-left:auto;text-align:right}.metric b,.metric span{display:block}.metric b{font-size:1rem}.metric span{color:#849096;font-size:.42rem}.hero button,.backup-group article button{padding:8px 10px;border:0;border-radius:5px;color:#fff;background:var(--a);font-size:.47rem}.flash{padding:10px;font-size:.6rem}.good{color:#267359;background:#eaf8f1}.bad{color:#a13e43;background:#fff0f0}.toolbar{margin-top:12px;padding:12px;display:flex;align-items:end;gap:15px;background:#fff}.toolbar label{flex:1;font-size:.47rem}.toolbar span{color:#89949a;font-size:.42rem}input{width:100%;padding:8px;border:1px solid #d7e0e3;border-radius:5px;font:inherit;font-size:.52rem}.backup-group{margin-top:12px;border-top:3px solid #267359;background:#fff}.backup-group.company{border-color:#4a5791}.backup-group>header{padding:15px;display:flex;align-items:center;gap:10px;border-bottom:1px solid #e6ebed}.database{width:42px;height:42px;display:grid;place-items:center;border-radius:10px;color:#267359;background:#e6f5ed;font-weight:800}.company .database{color:#4a5791;background:#e9ebf7}.backup-group header small{color:#89949a;font-size:.4rem}.backup-group h2{margin:2px 0;font-size:.76rem}.backup-group header p{margin:0;color:#89949a;font-size:.46rem}.backup-group header strong{margin-left:auto;font-size:.45rem}.backup-group article{padding:10px 15px;display:grid;grid-template-columns:38px 1fr .6fr auto;align-items:center;gap:10px;border-bottom:1px solid #edf0f1;font-size:.48rem}.file{width:34px;height:34px;display:grid;place-items:center;border-radius:7px;color:#8f3e43;background:#fae9ea;font-size:.45rem;font-weight:800}.backup-group article b,.backup-group article small{display:block}.backup-group article small{color:#89949a;font-size:.4rem}.backup-group article>span{color:#68777e}.backup-group button:disabled{opacity:.55}.empty{margin-top:12px;padding:45px;text-align:center;background:#fff;font-size:.58rem}.empty.inner{margin:0;background:#fafbfb}aside{margin-top:12px;padding:11px;display:flex;gap:8px;border:1px solid #ead393;border-radius:7px;color:#73591e;background:#fff7df;font-size:.48rem}aside span{margin-left:auto}@media(max-width:650px){.hero{flex-wrap:wrap}.metric{margin-left:0;text-align:left}.toolbar{align-items:stretch;flex-direction:column}.backup-group article{grid-template-columns:38px 1fr auto}.backup-group article>span{display:none}aside{display:block}aside span{display:block;margin-top:4px}}
</style>
