<script setup lang="ts">
import{onMounted,reactive,ref}from'vue'
import{listarAccesos,type Acceso,type AccesosFilters}from'../services/logAccesos'

const rows=ref<Acceso[]>([]),total=ref(0),last=ref(1),loading=ref(false),error=ref('')
const filters=reactive<AccesosFilters>({criterio:'',ip:'',desde:'',hasta:'',page:1})

async function load(page=1){filters.page=page;loading.value=true;error.value='';try{const response=await listarAccesos(filters);rows.value=response.data;total.value=response.total;last.value=response.last_page}catch(e){error.value=e instanceof Error?e.message:'No se pudo obtener el registro de accesos.'}finally{loading.value=false}}
function clear(){Object.assign(filters,{criterio:'',ip:'',desde:'',hasta:'',page:1});load()}
function initials(row:Acceso){return(row.nombre_completo||row.username||'U').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
onMounted(()=>load())
</script>

<template><div class="page"><nav><RouterLink to="/inicio">Inicio</RouterLink> / Sistema / Administrador / Log de accesos</nav><header class="hero"><div class="mark">LA</div><div><small>ADMINISTRACIÓN GENERAL</small><h1>Registro de ingresos al sistema</h1><p>Auditoría de accesos de los usuarios de la empresa actual.</p></div><strong>{{total}} ingresos</strong></header><p v-if="error" class="flash">{{error}}</p><section class="filters"><label>Usuario<input v-model.trim="filters.criterio" placeholder="Usuario o nombre" @keyup.enter="load()"></label><label>Dirección IP<input v-model.trim="filters.ip" placeholder="Ej. 192.168.1.10" @keyup.enter="load()"></label><label>Desde<input v-model="filters.desde" type="date"></label><label>Hasta<input v-model="filters.hasta" type="date"></label><div><button @click="load()">Consultar</button><button class="clear" @click="clear">Limpiar</button></div></section><div v-if="loading" class="empty">Cargando registro de accesos…</div><div v-else-if="!rows.length" class="empty"><b>Sin ingresos registrados</b><span>No se encontraron accesos para los filtros seleccionados.</span></div><section v-else class="list"><article v-for="row in rows" :key="row.id"><div class="avatar">{{initials(row)}}</div><div class="identity"><b>{{row.username}}</b><small>{{row.nombre_completo||'Usuario del sistema'}}</small></div><div><small>FECHA Y HORA</small><b>{{row.fecha}}</b></div><div><small>DIRECCIÓN IP</small><b class="ip">{{row.ip||'—'}}</b></div></article></section><footer v-if="last>1" class="pages"><button :disabled="filters.page<=1" @click="load(filters.page-1)">Anterior</button><span>Página {{filters.page}} de {{last}}</span><button :disabled="filters.page>=last" @click="load(filters.page+1)">Siguiente</button></footer></div></template>

<style scoped>
.page{--a:#334a61;color:#35444c}nav{margin-bottom:16px;color:#96a0a5;font-size:.7rem}nav a{color:var(--a)}.hero{padding:22px 25px;display:flex;align-items:center;gap:15px;border-left:5px solid var(--a);border-radius:13px;background:#fff}.mark{width:52px;height:52px;display:grid;place-items:center;border-radius:11px;color:#fff;background:var(--a);font-weight:800}.hero small{color:var(--a);font-size:.52rem;font-weight:700}.hero h1{margin:2px 0;font-size:1.28rem}.hero p{margin:0;color:#7c898f;font-size:.62rem}.hero strong{margin-left:auto;font-size:.52rem}.flash{padding:10px;color:#a13e43;background:#fff0f0;font-size:.6rem}.filters{margin-top:12px;padding:12px;display:grid;grid-template-columns:1.2fr 1fr .8fr .8fr auto;align-items:end;gap:8px;background:#fff}.filters label{font-size:.47rem}input{width:100%;padding:8px;border:1px solid #d7e0e3;border-radius:5px;font:inherit;font-size:.52rem}.filters button,.pages button{padding:8px 10px;border:0;border-radius:5px;color:#fff;background:var(--a);font-size:.47rem}.filters .clear{margin-left:4px;color:#68767c;background:#edf1f2}.list{margin-top:12px;background:#fff}.list article{padding:12px 16px;display:grid;grid-template-columns:42px 1.4fr 1fr .8fr;align-items:center;gap:12px;border-bottom:1px solid #e9edee;font-size:.5rem}.avatar{width:38px;height:38px;display:grid;place-items:center;border-radius:50%;color:#fff;background:#60778c;font-size:.55rem;font-weight:800}.list b,.list small{display:block}.list small{margin-bottom:2px;color:#89949a;font-size:.4rem}.identity b{font-size:.58rem}.ip{width:max-content;padding:4px 7px;border-radius:10px;color:#745b20;background:#fff4d6;font-family:monospace}.empty{margin-top:12px;padding:48px;display:grid;gap:5px;text-align:center;background:#fff;font-size:.58rem}.empty span{color:#89949a;font-size:.48rem}.pages{display:flex;justify-content:center;align-items:center;gap:10px;font-size:.48rem}@media(max-width:820px){.filters{grid-template-columns:1fr 1fr}.list article{grid-template-columns:42px 1fr 1fr}}@media(max-width:540px){.hero{flex-wrap:wrap}.hero strong{margin-left:0}.filters,.list article{grid-template-columns:1fr}.avatar{display:none}}
</style>
